import test from 'node:test';import assert from 'node:assert/strict';
import { fixture,until } from './helpers.js';import { importConfiguration,saveConfig,bindConfig,resolveConfig,stable,adaptToNovel } from '../src/config.js';
import { compilePrompt,macroEnvironment,requestDiff } from '../src/compiler.js';import { regexRuleSchema,nativePresets } from '../src/config-contracts.js';import { transformText } from '../src/text-pipeline.js';
import { Runner } from '../src/runtime.js';import { DemoProvider } from '../src/demo.js';import { type ModelRequest,DshProvider } from '../src/provider.js';import { requestList } from '../src/requests.js';import { buildContext } from '../src/context.js';import { hash,Store } from '../src/store.js';import { DatabaseSync } from 'node:sqlite';import { mkdtempSync,rmSync } from 'node:fs';import { tmpdir } from 'node:os';import { join } from 'node:path';
const raw=JSON.stringify({temperature:0.8,top_p:0.7,prompts:[{identifier:'a',content:'对白简短 {{char}} / {{user}} / {{unknown}}',role:'system'},{identifier:'b',content:'文学样例',role:'assistant'},{identifier:'off',content:'禁用内容',role:'user'},{identifier:'tail',content:'不输出解释',role:'user',injection_position:1,injection_depth:0},{identifier:'depth',content:'不可映射',role:'system',injection_position:1,injection_depth:4}],prompt_order:[{character_id:100001,order:[{identifier:'b',enabled:true},{identifier:'a',enabled:true},{identifier:'off',enabled:false},{identifier:'tail',enabled:true},{identifier:'depth',enabled:true}]}]});
test('upgrade B/F: imported roles/order/macros and frozen scope are compiled; literature cannot change structured protocols',async()=>{
 const f=fixture(),v=saveConfig(f.store,importConfiguration(raw,'兼容测试'));assert.equal(resolveConfig(f.store,f.p.id).config.enabled,false);bindConfig(f.store,'project:'+f.p.id,v.id,null);
 const t=f.task({configuration:{patch:{bindings:{characterId:f.a.id,authorName:'作者甲'}}}});const a=await compilePrompt(f.domain,t,'write',{goal:t.goal});assert.deepEqual(a.messages.filter(m=>['文学样例','不输出解释'].includes(m.text)).map(m=>m.role),['assistant','user']);assert.ok(a.messages.some(m=>m.text.includes('沈砚 / 作者甲 / {{unknown}}')));assert.ok(a.warnings.some(w=>w.includes('{{unknown}}')));assert.ok(!a.messages.some(m=>m.text.includes('不可映射')||m.text.includes('禁用内容')));assert.equal(a.sampling.temperature,0.8);assert.ok(v.report.some(r=>r.field==='top_p'&&r.status==='UNSUPPORTED'));
 const next=saveConfig(f.store,importConfiguration(JSON.stringify({format:'dsh-novel-config',config:nativePresets[2].config}),'新文风'));bindConfig(f.store,'project:'+f.p.id,next.id,v.id);assert.equal((await compilePrompt(f.domain,t,'write',{goal:t.goal})).hash,a.hash);
 const dynamic=await compilePrompt(f.domain,t,'write',{goal:'完全不同的当前目标'});assert.equal(dynamic.stableHash,a.stableHash);assert.notEqual(dynamic.hash,a.hash);
 for(const key of ['plan','review','extract','summarize'] as const){const c=await compilePrompt(f.domain,t,key,{draft:'正文',goal:t.goal});assert.ok(c.system.includes('JSON Schema'));assert.ok(!c.messages.some(m=>m.text.includes('不输出解释')||m.text.includes('文学样例')));assert.deepEqual(c.sampling,{});}
 const second=await compilePrompt(f.domain,t,'write',{goal:t.goal});assert.equal(second.localCompilationCache,'HIT');assert.equal(second.hash,a.hash);assert.equal(stable(second.messages),stable(a.messages));assert.equal(adaptToNovel(v).config.strategy,'novel');assert.equal(v.config.strategy,'compatible');
 const diff=requestDiff({messages:a.messages},{messages:[...a.messages,{role:'user',text:'下一章'}]});assert.ok(diff.firstChangedPath?.startsWith('$.messages'));f.store.close();
});
test('upgrade C: Chinese multiline captures, display isolation, clean replay, invalid regex and worker termination',async()=>{
 const rule=regexRuleSchema.parse({id:'r',name:'换行对白',pattern:'(她说)[\\s\\S]*?(你好)',flags:'gu',replacement:'$1：“$2。”',stage:'after'});const input='她说\n你好';const a=await transformText(input,[rule],'after','prose');assert.equal(a.text,'她说：“你好。”');assert.equal(a.trace[0].matches[0].start,0);assert.equal((await transformText(input,[rule],'after','prose')).text,a.text);assert.equal((await transformText(input,[rule],'display','prose')).text,input);
 const invalid=await transformText('abc',[{...rule,pattern:'['}],'after','prose',{test:true});assert.ok(invalid.trace[0].error);let ticks=0;const interval=setInterval(()=>ticks++,5);const evil=await transformText('a'.repeat(30000)+'!',[{...rule,pattern:'(a+)+$',replacement:''}],'after','prose',{test:true,timeoutMs:150});clearInterval(interval);assert.ok(evil.trace[0].error?.includes('终止'));assert.ok(ticks>2,'HTTP thread remains responsive');assert.equal(evil.text,'a'.repeat(30000)+'!');
 assert.ok((await transformText('中'.repeat(1002),[{...rule,pattern:'中'}],'after','prose',{test:true})).trace[0].error?.includes('次数'));
});
test('upgrade B: config formats/credentials and readonly variables are explicit, previews never mutate',()=>{
 assert.equal(importConfiguration('{"input_sequence":"abc"}','instruct').applicable,false);assert.throws(()=>importConfiguration('{"api_key":"do-not-save"}','key'),/凭据字段/);const f=fixture(),t=f.task({configuration:{patch:{enabled:true,bindings:{variables:{key:'银钥匙'}},native:{base:'{{date}} {{random::晴::雨}}'}}}});const before=f.domain.backup(f.p.id).checksum;const env=macroEnvironment(f.domain,t,t.configSnapshot!,{});assert.equal(env.expand('{{getvar::key}}'),'银钥匙');assert.equal(env.expand('{{random::晴::雨}}'),env.expand('{{random::晴::雨}}'));assert.equal(env.expand('{{setvar::key::铜钥匙}}'),'{{setvar::key::铜钥匙}}');assert.equal(f.domain.backup(f.p.id).checksum,before);f.store.close();
});
test('upgrade A: additive schema migration and v1/v2 backups preserve prose, versions and config isolation',()=>{
 const dir=mkdtempSync(join(tmpdir(),'novel-migration-'));const path=join(dir,'copy.sqlite');const old=new DatabaseSync(path);old.exec("CREATE TABLE meta(key TEXT PRIMARY KEY,value TEXT);INSERT INTO meta VALUES('schema','1');CREATE TABLE projects(id TEXT PRIMARY KEY,data TEXT NOT NULL);");old.close();const f=fixture(path);assert.equal(f.store.db.prepare("SELECT value FROM meta WHERE key='schema'").get()?.value,'4');f.domain.saveChapter(f.p.id,f.chapter.id,f.chapter.revision,'旧稿保留\n空白  原样');const payload:any=f.domain.backup(f.p.id).payload;payload.schema=1;delete payload.configurations;delete payload.effectiveConfiguration;delete payload.requests;delete payload.memories;const restored=f.domain.restoreBackup({payload,checksum:hash(payload)});assert.equal(f.domain.chapters(restored.id)[0].body,'旧稿保留\n空白  原样');const v=saveConfig(f.store,importConfiguration(JSON.stringify({format:'dsh-novel-config',config:nativePresets[0].config}),'克制'));bindConfig(f.store,'project:'+f.p.id,v.id,null);const copy=f.domain.restoreBackup(f.domain.backup(f.p.id));assert.equal(resolveConfig(f.store,copy.id).config.native?.base,nativePresets[0].config.native?.base);assert.equal(f.store.list('versions',copy.id).length,1);assert.equal(resolveConfig(f.store,restored.id).config.enabled,false);f.store.close();rmSync(dir,{recursive:true});
});
test('upgrade G: pipeline preserves raw response, review sees candidate and late config updates cannot change running task',async()=>{
 const f=fixture();const rule=regexRuleSchema.parse({id:'r',name:'移除前缀',pattern:'^RAW_PREFIX',flags:'u',replacement:'',stage:'after'});const v=saveConfig(f.store,importConfiguration(JSON.stringify({format:'dsh-novel-config',config:{...nativePresets[0].config,regex:[rule]}}),'工作流配置'));bindConfig(f.store,'project:'+f.p.id,v.id,null);const demo=new DemoProvider();let written='',reviewed='';const provider={info:()=>demo.info(),async generate(r:ModelRequest){const result=await demo.generate(r);if(r.prompt==='write'){written='RAW_PREFIX'+result.text;result.text=written;}if(r.prompt==='review')reviewed=r.input.draft;return result;}};const runner=new Runner(f.domain,provider,provider);const t=f.task({});runner.start(t.id);await runner.idle(t.id);assert.equal(f.domain.task(f.p.id,t.id).status,'COMPLETED',JSON.stringify(f.domain.task(f.p.id,t.id).error));const requests=requestList(f.store,f.p.id);const request=requests.find(r=>r.compiled.role==='Writer')!;assert.equal(request.rawResponse,written);assert.ok(!reviewed.includes('RAW_PREFIX'));assert.equal(request.candidate,reviewed);const a=f.store.list('artifacts',f.p.id).find(a=>a.type==='chapter')!;assert.equal(a.data.generation.rawResponse,written);assert.equal(f.domain.object(f.p.id,f.chapter.id).body,reviewed);assert.equal(request.usage?.serverCache,'UNKNOWN');f.store.close();
});
test('upgrade F: observable DSH request and disjoint cache accounting never invent missing cache writes',async()=>{
 const f=fixture();const t=f.task({});const compiled=await compilePrompt(f.domain,t,'write',{goal:'test'});let observed:any;const provider=new DshProvider({async *stream(options:any){assert.equal(options.system,compiled.system);yield {type:'text-delta' as const,index:0,text:'实际文本'};yield {type:'usage' as const,usage:{inputTokens:100,cacheReadTokens:900,outputTokens:20,totalTokens:1020}};yield {type:'finish' as const,reason:{kind:'stop' as const}};}},()=>({provider:'test-deepseek',model:'test'}));const result=await provider.generate({prompt:'write',input:{},compiled,task:t,maxTokens:1000,signal:new AbortController().signal,onDelta:()=>{},onRequest:r=>{observed=r;}});assert.equal(result.usage?.inputTokens,1000);assert.equal(result.usage?.uncachedInputTokens,100);assert.equal(result.usage?.cacheReadTokens,900);assert.equal(result.usage?.cacheWriteTokens,undefined);assert.ok(observed.messages);assert.ok(!JSON.stringify(observed).includes('api_key'));f.store.close();
});

test('upgrade F: DSH preserves usage on failed stream and final schema budget stops before the call',async()=>{
 const f=fixture(),t=f.task({}),compiled=await compilePrompt(f.domain,t,'review',{draft:'正文'});let called=false;
 const provider=new DshProvider({async *stream(){called=true;yield {type:'usage' as const,usage:{inputTokens:10,cacheReadTokens:100,outputTokens:20,totalTokens:130}};yield {type:'finish' as const,reason:{kind:'max-tokens' as const}};}},()=>({provider:'test',model:'test'}));
 const request={prompt:'review' as const,input:{},compiled,task:t,maxTokens:1000,signal:new AbortController().signal,onDelta:()=>{}};
 await assert.rejects(provider.generate({...request,compiled:{...compiled,budget:20}}),(e:any)=>e.code==='PROMPT_BUDGET');assert.equal(called,false);
 await assert.rejects(provider.generate(request),(e:any)=>e.outputTokens===20&&e.usage.cacheReadTokens===100&&e.usage.elapsedMs>=0);assert.equal(called,true);f.store.close();
});
