import test from 'node:test';import assert from 'node:assert/strict';import { fixture,until } from './helpers.js';import { sourceFor,installMemory,memoryStatus,memoryList,recallMemory,editMemory,validMemory,rollingPlanning } from '../src/memory.js';import { temporalObjects,worldRecall } from '../src/temporal.js';import { previewLorebook,acceptLorebook } from '../src/lorebook.js';import { buildContext } from '../src/context.js';import { Runner } from '../src/runtime.js';import { DemoProvider } from '../src/demo.js';import { type ModelRequest } from '../src/provider.js';import { oldInput } from '../src/domain.js';import { saveConfig,importConfiguration,bindConfig } from '../src/config.js';

function synthetic(){const f=fixture();const person=f.add({kind:'character',title:'邝昶',status:'accepted',fields:{aliases:['阿晷'],voice:'把问句说完才停'}});const chapters=[];for(let n=1;n<=40;n++){let c=n===1?f.chapter:f.add({kind:'chapter',title:`合成第${n}章`,parentId:f.volume.id,order:n,status:'planned'});const event=n===1?'阿晷因渡口封锁，把唯一铜钥匙交给闻溪，约定退潮后在钟楼取回。':n===3?'邝昶误把白帆看作求救信号，后来在维修日志发现这是潮位标志；他尚未告诉闻溪。':n===6?'闻溪说，修好第七码头后会归还蓝色信封。':n===38?'尚未总结的最新事件：码头钟声突然停止。':`第${n}章里，邝昶逐个核对潮位记录，闻溪沿岸维护灯座。`;
 c=f.domain.saveChapter(f.p.id,c.id,c.revision,event+'\n\n'+Array.from({length:12},(_,i)=>`【合成测试记录 ${n}-${i}】街区${n}的测绘数字与船次${i}已登记；这是检索规模测试数据，不是模型生成的小说。`).join('\n'));chapters.push(c);
 if(n<=37)f.store.transaction(()=>installMemory(f.domain,f.p.id,sourceFor(f.domain,c),{summary:event,scenes:[{summary:event,quote:event,entityIds:[person.id],knownByIds:[person.id],time:'相对时间',location:n===1?'渡口':'码头',cause:n===1?'渡口封锁':'未证实',effect:n===1?'钥匙交给闻溪':'见引文',importance:n<=6?3:1}],obligations:n===1?[{content:'退潮后到钟楼取回铜钥匙',quote:event,entityIds:[person.id],state:'open'}]:[]},'deterministic-synthetic-fixture'));
 }return {...f,person,chapters};}
test('upgrade E: forty-chapter fixture recalls rare Chinese aliases, early causes and evidence; gaps remain and versions are bounded',()=>{const f=synthetic();const hits=recallMemory(f.domain,f.p.id,{goal:'阿晷在钟楼取回铜钥匙的约定与渡口封锁',asOf:40,limit:6});assert.ok(hits.some(h=>h.chapterId===f.chapters[0].id&&h.quote.includes('渡口封锁')));assert.ok(hits.every(h=>f.domain.object(f.p.id,h.chapterId).body.slice(h.start,h.end)===h.quote));const status=memoryStatus(f.domain,f.p.id);assert.equal(status.covered,37);assert.equal(status.gaps.length,3);assert.equal(status.waterline,37);assert.equal(status.memories.filter(m=>m.kind==='checkpoint'&&m.status==='valid').length,7);
 const pack=buildContext(f.domain,f.p.id,{goal:'阿晷在钟楼取回铜钥匙的约定',memory:{enabled:true,recallLimit:6},maxChars:18000});assert.ok(pack.text.includes('尚未总结的最新事件'));assert.ok(pack.items.some(i=>i.kind==='memory-evidence'&&i.version===f.chapters[0].fields.currentVersion));assert.ok(pack.used<=18000);assert.ok(pack.text.length<f.chapters.reduce((n,c)=>n+c.body.length,0));assert.ok(pack.items.some(i=>i.kind==='memory-checkpoint'));
 const side=f.add({kind:'chapter',title:'其他分支',parentId:f.volume.id,status:'planned',order:41,fields:{branch:'side'}});f.domain.saveChapter(f.p.id,side.id,side.revision,'阿晷在钟楼得知 ONLY_SIDE_SECRET。');const future=f.add({kind:'chapter',title:'未来正文',parentId:f.volume.id,status:'planned',order:42});f.domain.saveChapter(f.p.id,future.id,future.revision,'阿晷在钟楼读到 ONLY_FUTURE_SECRET。');const scoped=recallMemory(f.domain,f.p.id,{goal:'阿晷 钟楼 ONLY_SIDE_SECRET ONLY_FUTURE_SECRET',asOf:40});assert.ok(!JSON.stringify(scoped).includes('ONLY_SIDE_SECRET'));assert.ok(!JSON.stringify(scoped).includes('ONLY_FUTURE_SECRET'));f.store.close();
});
test('upgrade E/I: accepted source change rejects late summary; edit/lock/restore never changes canon, rollback and repeat install do not duplicate',()=>{const f=fixture();let c=f.domain.saveChapter(f.p.id,f.chapter.id,f.chapter.revision,'沈砚把唯一铜钥匙交给闻溪，约定明天归还。');const source=sourceFor(f.domain,c),content={summary:'钥匙交接',scenes:[{summary:'交接',quote:c.body,entityIds:[f.a.id,f.b.id]}],obligations:[]};let m=f.store.transaction(()=>installMemory(f.domain,f.p.id,source,content,'test'));const before=f.store.objects(f.p.id,'fact').length;const repeated=f.store.transaction(()=>installMemory(f.domain,f.p.id,source,content,'test'));assert.equal(repeated.id,m.id);assert.equal(memoryList(f.store,f.p.id).length,1);
 m=editMemory(f.domain,f.p.id,m.id,m.revision,{content:{...m.content,summary:'作者校订的摘要'}});assert.equal(f.store.objects(f.p.id,'fact').length,before);m=editMemory(f.domain,f.p.id,m.id,m.revision,{locked:true});assert.throws(()=>editMemory(f.domain,f.p.id,m.id,m.revision,{content:m.content}),/解锁/);m=editMemory(f.domain,f.p.id,m.id,m.revision,{locked:false});m=editMemory(f.domain,f.p.id,m.id,m.revision,{restoreRevision:1});assert.equal(m.content.summary,'钥匙交接');
 c=f.domain.object(f.p.id,c.id);c=f.domain.saveChapter(f.p.id,c.id,c.revision,'作者修订：铜钥匙没有转交，仍在沈砚手中。');assert.equal(memoryStatus(f.domain,f.p.id).covered,0);assert.throws(()=>installMemory(f.domain,f.p.id,source,content,'late'),/旧结果/);assert.equal(memoryList(f.store,f.p.id)[0].content.summary,'钥匙交接');const rolled=f.domain.rollback(f.p.id,c.id,c.revision,source.versionId);assert.notEqual(rolled.fields.currentVersion,source.versionId);assert.ok(!validMemory(f.domain,m));assert.equal(memoryList(f.store,f.p.id).length,1);f.store.close();
});
test('upgrade D: temporal directed relationships retain asymmetric knowledge; world lookup is selective and recursively bounded',()=>{const f=fixture();let r=f.add({kind:'relationship',title:'单向信任',status:'accepted',fields:{fromId:f.a.id,toId:f.b.id,type:'信任',state:'信任',perspectiveFrom:'相信她',perspectiveTo:'隐瞒真实身份'},source:{type:'user',fromChapter:1}});r=f.domain.updateObject(f.p.id,r.id,r.revision,{...oldInput(r),fields:{...r.fields,state:'决裂'},source:{type:'user',fromChapter:10}});const early=temporalObjects(f.domain,f.p.id,{asOfChapter:3}).objects.find(o=>o.id===r.id)!;assert.equal(early.fields.state,'信任');assert.equal(temporalObjects(f.domain,f.p.id,{asOfChapter:12}).objects.find(o=>o.id===r.id)?.fields.state,'决裂');
 const secret=f.add({kind:'world',title:'导师秘密',status:'accepted',locked:true,body:'导师是寂潮族的末裔',fields:{visibility:'hidden',knownByIds:[f.b.id],keys:['导师']}});const seen=temporalObjects(f.domain,f.p.id,{asOfChapter:3,viewpointId:f.a.id,audience:'character'});assert.ok(!JSON.stringify(seen.objects).includes(secret.body));assert.ok(!JSON.stringify(seen.objects.find(o=>o.id===r.id)).includes('隐瞒真实身份'));assert.ok(temporalObjects(f.domain,f.p.id,{asOfChapter:3,viewpointId:f.b.id,audience:'character'}).objects.some(o=>o.id===secret.id));
 const raw=JSON.stringify({entries:{0:{uid:0,comment:'潮灯规则',key:['潮灯'],content:'潮灯只有自愿交出记忆才能点亮，一般不接受陌生记忆；亲属授权是例外且需要双倍代价。节点1',constant:true},...Object.fromEntries(Array.from({length:35},(_,i)=>[i+1,{uid:i+1,key:[`节点${i+1}`],content:`节点${i+2} 节点${i+3}`,comment:`节点${i+1}`}]))}});const preview=previewLorebook(raw,'原创WorldInfoFixture');acceptLorebook(f.domain,f.p.id,f.domain.project(f.p.id).revision,raw,preview.name,preview.sourceHash);const originalCount=f.store.objects(f.p.id,'world').length;assert.equal(acceptLorebook(f.domain,f.p.id,f.domain.project(f.p.id).revision,raw,preview.name,preview.sourceHash).reused,true);assert.equal(f.store.objects(f.p.id,'world').length,originalCount);const world=worldRecall(f.store.objects(f.p.id,'world'),'潮灯',new Set(),5);assert.ok(world.entries.length<=5);assert.ok(world.entries.every(e=>e.depth<=2));assert.ok(world.entries.some(e=>e.object.body.includes('一般不接受')));f.store.close();
});
test('upgrade G: accepted chapter updates memory atomically, neutral summarizer backfills after takeover and late summaries are isolated',async()=>{const f=fixture();const cfg=saveConfig(f.store,importConfiguration(JSON.stringify({format:'dsh-novel-config',config:{enabled:true,native:{base:'克制叙述'},memory:{enabled:true}}}),'有记忆的文风'));bindConfig(f.store,'project:'+f.p.id,cfg.id,null);const t=f.task({});f.runner.start(t.id);await f.runner.idle(t.id);assert.equal(f.domain.task(f.p.id,t.id).status,'COMPLETED',JSON.stringify(f.domain.task(f.p.id,t.id).error));assert.equal(memoryStatus(f.domain,f.p.id).covered,1);let c=f.domain.object(f.p.id,f.chapter.id);c=f.domain.takeover(f.p.id,c.id,c.revision);c=f.domain.saveChapter(f.p.id,c.id,c.revision,'最新接受正文：沈砚把信留在蓝柜中。');assert.equal(memoryStatus(f.domain,f.p.id).covered,0);const s=f.task({kind:'summarize',chapterId:c.id});f.runner.start(s.id);await f.runner.idle(s.id);assert.equal(f.domain.task(f.p.id,s.id).status,'COMPLETED',JSON.stringify(f.domain.task(f.p.id,s.id).error));assert.equal(memoryStatus(f.domain,f.p.id).covered,1);
 let release!:(x:any)=>void,ready=false;const demo=new DemoProvider(),provider={info:()=>demo.info(),async generate(r:ModelRequest){if(r.prompt==='summarize'){ready=true;return new Promise<any>(resolve=>{release=resolve;});}return demo.generate(r);}};const runner=new Runner(f.domain,provider,provider,2000);const late=f.task({kind:'summarize',chapterId:c.id});runner.start(late.id);await until(()=>ready);c=f.domain.object(f.p.id,c.id);c=f.domain.takeover(f.p.id,c.id,c.revision);c=f.domain.saveChapter(f.p.id,c.id,c.revision,'作者再次改为绿色柜子。');release({text:JSON.stringify({summary:'旧蓝柜',scenes:[],obligations:[]}),outputTokens:20});await runner.idle(late.id);assert.ok(f.store.list('artifacts',f.p.id).some(a=>a.taskId===late.id&&a.status==='stale'));assert.equal(memoryStatus(f.domain,f.p.id).covered,0);assert.equal(f.domain.object(f.p.id,c.id).body,'作者再次改为绿色柜子。');f.store.close();
});

test('upgrade D/E: relation replacement keeps one temporal edge; chapter move invalidates projections and branch mismatch is fenced',()=>{
 const f=fixture();let c=f.domain.saveChapter(f.p.id,f.chapter.id,f.chapter.revision,'沈砚信任闻溪。');const m=f.store.transaction(()=>installMemory(f.domain,f.p.id,sourceFor(f.domain,c),{summary:'信任',scenes:[{summary:'信任',quote:c.body}]} ,'test'));
 const early=f.add({kind:'relationship',title:'信任起点',status:'accepted',fields:{fromId:f.a.id,toId:f.b.id,type:'信任',state:'信任'},source:{type:'user',fromChapter:1}});
 const later=f.add({kind:'relationship',title:'信任变化',status:'accepted',fields:{fromId:f.a.id,toId:f.b.id,type:'信任',state:'决裂',edgeKey:`${f.a.id}:${f.b.id}:信任`},source:{type:'user',fromChapter:5}});
 assert.equal(temporalObjects(f.domain,f.p.id,{asOfChapter:3}).objects.filter(o=>o.kind==='relationship').at(-1)?.id,early.id);
 const relations=temporalObjects(f.domain,f.p.id,{asOfChapter:6}).objects.filter(o=>o.kind==='relationship');assert.equal(relations.length,1);assert.equal(relations[0].id,later.id);
 const chain=Array.from({length:4},(_,n)=>f.add({kind:'character',title:`链路角色${n}`,status:'accepted'}));for(let n=0;n<chain.length;n++)f.add({kind:'relationship',title:`链路${n}`,status:'accepted',fields:{fromId:n?chain[n-1].id:f.a.id,toId:chain[n].id,type:'合作'}});const bounded=buildContext(f.domain,f.p.id,{chapterId:c.id,goal:'沈砚核对钥匙'});assert.ok(!bounded.items.some(i=>i.kind==='character'&&i.id===chain[3].id),'关系扩展必须有界，不能随存储顺序不断连锁');
 c=f.domain.object(f.p.id,c.id);c=f.domain.updateObject(f.p.id,c.id,c.revision,{...oldInput(c),order:9,fields:{...c.fields,branch:'alternate'}});assert.equal(c.fields.summaryVersion,'');assert.equal(c.fields.extractionPending,true);assert.equal(validMemory(f.domain,m),false);
 assert.throws(()=>f.task({kind:'extract',chapterId:c.id,perspective:{branch:'main'}}),/分支/);const task=f.task({kind:'extract',chapterId:c.id});assert.equal(task.perspective?.branch,'alternate');f.store.close();
});
