import test from 'node:test';import assert from 'node:assert/strict';import { fixture,until } from './helpers.js';
import { Runner } from '../src/runtime.js';import { DemoProvider,firstChapter } from '../src/demo.js';import { type ModelRequest } from '../src/provider.js';import { Store } from '../src/store.js';import { Domain } from '../src/domain.js';import { mkdtempSync,rmSync } from 'node:fs';import { tmpdir } from 'node:os';import { join } from 'node:path';
test('B/F: real domain workflow with explicit deterministic model, two chapters inherit latest versions',async()=>{const f=fixture();const t=f.task({count:1});f.runner.start(t.id);await f.runner.idle(t.id);assert.equal(f.domain.task(f.p.id,t.id).status,'COMPLETED',JSON.stringify(f.domain.task(f.p.id,t.id).error));let c=f.domain.object(f.p.id,f.chapter.id);c=f.domain.takeover(f.p.id,c.id,c.revision);c=f.domain.saveChapter(f.p.id,c.id,c.revision,c.body.replaceAll('铜钥匙','银钥匙'));const v=c.fields.currentVersion;const second=f.task({goal:'根据作者修改后的银钥匙继续下一章'});f.runner.start(second.id);await f.runner.idle(second.id);const result=f.domain.task(f.p.id,second.id);assert.equal(result.status,'COMPLETED',JSON.stringify(result.error));assert.ok(result.steps.some(s=>JSON.stringify(s.output).includes('银钥匙')));const a=f.store.list('artifacts',f.p.id).find(a=>a.taskId===second.id&&a.status==='accepted')!;assert.ok(a.data.context.items.some((i:any)=>i.version===v));assert.ok(a.data.content.includes('银钥匙'));assert.ok(result.usage.calls<=result.budget.calls);assert.ok(result.usage.outputTokens<=result.budget.outputTokens);f.store.close();});
test('C: late ignored-abort result cannot overwrite takeover',async()=>{const f=fixture();let release!:(value:any)=>void;let generating=false;const base=new DemoProvider();const provider={info:()=>base.info(),generate:(r:ModelRequest)=>{if(r.prompt==='write'){generating=true;return new Promise<any>(resolve=>{release=resolve;});}return base.generate(r);}};const runner=new Runner(f.domain,provider,provider,2000);const t=f.task({});runner.start(t.id);await until(()=>generating);let c=f.domain.object(f.p.id,f.chapter.id);c=f.domain.takeover(f.p.id,c.id,c.revision);c=f.domain.saveChapter(f.p.id,c.id,c.revision,'作者接管后的重要事实。');release({text:firstChapter(),outputTokens:700});await runner.idle(t.id);assert.equal(f.domain.object(f.p.id,c.id).body,'作者接管后的重要事实。');assert.ok(f.store.list('artifacts',f.p.id).some(a=>a.status==='stale'));assert.equal(f.domain.task(f.p.id,t.id).status,'PAUSED');f.store.close();});
test('F/H: chapter/call/output budgets stay finite',async()=>{const f=fixture();assert.throws(()=>f.task({count:4}));const t=f.task({budget:{calls:1,outputTokens:20000,contextChars:18000}});f.runner.start(t.id);await f.runner.idle(t.id);const result=f.domain.task(f.p.id,t.id);assert.equal(result.status,'PAUSED');assert.equal(result.error?.code,'BUDGET_EXHAUSTED');assert.equal(result.usage.calls,1);assert.equal(f.domain.object(f.p.id,f.chapter.id).body,'');f.store.close();});
test('H: malformed structured output exhausts bounded retries and preserves diagnostic',async()=>{const f=fixture();const provider={info:()=>({available:true,name:'test-invalid',detail:'test'}),async generate(){return {text:'invalid JSON'};}};const runner=new Runner(f.domain,provider,provider,100);const t=f.task({});runner.start(t.id);await runner.idle(t.id);const result=f.domain.task(f.p.id,t.id);assert.equal(result.status,'FAILED');assert.equal(result.usage.calls,3);assert.equal(result.error?.code,'INVALID_JSON');assert.equal(result.steps[0].attempts,3);f.store.close();});
test('H: timeout bounded, partial data retained, cancel-late never commits',async()=>{const f=fixture();const provider={info:()=>({available:true,name:'test-timeout',detail:'test'}),async generate(r:ModelRequest){r.onDelta('这是尚未结束的模型输出');return new Promise<any>(()=>{});}};const runner=new Runner(f.domain,provider,provider,25);const t=f.task({});runner.start(t.id);await runner.idle(t.id);const result=f.domain.task(f.p.id,t.id);assert.equal(result.status,'FAILED');assert.equal(result.error?.code,'MODEL_TIMEOUT');assert.ok(result.steps[0].partial);assert.equal(result.usage.calls,3);f.store.close();});
test('G: actual pause during chapter two, disk restart reuses checkpoint without repeating chapter one',async()=>{
  const dir=mkdtempSync(join(tmpdir(),'novel-restart-'));const path=join(dir,'studio.sqlite');const f=fixture(path);const demo=new DemoProvider();let release!:()=>void;let ready=false;
  const provider={info:()=>demo.info(),async generate(r:ModelRequest){const result=await demo.generate(r);if(r.prompt==='plan'&&r.task.completedChapters===1){ready=true;await new Promise<void>(resolve=>{release=resolve;});}return result;}};
  const runner=new Runner(f.domain,provider,provider);const t=f.task({count:2});runner.start(t.id);await until(()=>ready,5000);const first=f.store.list('versions',f.p.id)[0];const before=f.domain.task(f.p.id,t.id);assert.equal(before.completedChapters,1);
  f.domain.controlTask(f.p.id,t.id,'pause');release();await runner.idle(t.id);assert.equal(f.domain.task(f.p.id,t.id).status,'PAUSED');await runner.close();f.store.close();
  const store=new Store(path);const domain=new Domain(store);domain.recover();const resumed=new Runner(domain,demo,demo);domain.controlTask(f.p.id,t.id,'resume');resumed.start(t.id);await resumed.idle(t.id);const result=domain.task(f.p.id,t.id);
  assert.equal(result.status,'COMPLETED',JSON.stringify(result.error));assert.deepEqual(result.budget,t.budget);assert.equal(result.completedChapters,2);assert.ok(store.events(f.p.id,t.id).some(e=>e.type==='step.reused'));assert.equal(store.list('versions',f.p.id).filter(v=>v.chapterId===first.chapterId).length,1);assert.equal(store.list('versions',f.p.id).length,2);
  const facts=store.objects(f.p.id,'fact');assert.equal(new Set(facts.map(f=>f.source?.versionId+':'+f.fields.entityId+':'+f.fields.property)).size,facts.length);await resumed.close();store.close();rmSync(dir,{recursive:true});
});

test('review-only repair gets blocking issues and no implicit writing-length target',async()=>{
 const f=fixture();const body='他核对水尺，把三尺伍改为三尺五。';let calls=0;const seen:ModelRequest[]=[];
 const provider={info:()=>({available:true,name:'bounded-review-fixture',detail:'deterministic'}),async generate(r:ModelRequest){seen.push(r);if(r.prompt==='review')return {text:JSON.stringify({summary:'度量已核对',claims:[],events:[],issues:calls++?[]:[{category:'typo',severity:'critical',quote:'三尺伍',message:'错字',sourceQuote:'',rationale:'本次局部修复',suggestion:'改成五',blocks:true},{category:'voice',severity:'advice',quote:'他核对水尺',message:'可以更细腻',sourceQuote:'',rationale:'文学建议',suggestion:'无需改动',blocks:false}]}),outputTokens:100,estimated:true};if(r.prompt==='repair')return {text:JSON.stringify({edits:[{quote:'三尺伍',replacement:'三尺五'}],summary:'一处错字'}),outputTokens:50,estimated:true};return new DemoProvider().generate(r);}};
 const runner=new Runner(f.domain,provider,provider);try{
  f.domain.saveChapter(f.p.id,f.chapter.id,f.chapter.revision,body);const t=f.task({kind:'review',chapterId:f.chapter.id,goal:'只核对本章错字',targetWords:4000});runner.start(t.id);await runner.idle(t.id);
  assert.equal(f.domain.task(f.p.id,t.id).status,'COMPLETED');const repair=seen.find(r=>r.prompt==='repair')!;
  assert.equal(repair.input.issues.length,1);assert.equal(repair.input.issues[0].category,'typo');assert.equal(repair.input.targetWords,undefined);
  assert.ok(seen.filter(r=>r.prompt==='review').every(r=>r.input.targetWords===undefined));assert.equal(f.domain.object(f.p.id,f.chapter.id).body,body.replace('三尺伍','三尺五'));
 }finally{await runner.close();f.store.close();}
});
