import { useRef,useState } from 'react';import { diffLines } from 'diff';import { Check,ArrowUpRight,AlertTriangle,BookOpen,FileDiff,Layers,Search } from 'lucide-react';
import { Modal,Field } from './Modal.js';import { api,statusText } from './api.js';import { countWords,type Artifact,type CreativeTask,type StoryObject } from '../contracts.js';
export function ContextTrace({context}:{context:any}){if(!context)return <p className="muted">此成果没有生成上下文记录。</p>;return <div className="context-trace"><div className="trace-summary"><strong>{context.used.toLocaleString()} / {context.budget.toLocaleString()} 字符</strong><span>作品修订 {context.revision}</span></div>{context.missing?.map((x:string)=><p className="notice" key={x}>{x}</p>)}{context.items?.map((i:any)=><details key={i.id}><summary><span className="badge">{i.kind}</span> {i.mandatory?'锁定约束 · ':''}{i.reason}<small>版本 {i.version}</small></summary><pre>{i.text}</pre></details>)}<details><summary>因预算或版本省略的资料（{context.omitted?.length??0}）</summary>{context.omitted?.map((i:any)=><p key={i.id}>{i.id} · {i.reason}</p>)}</details></div>;}
export function ArtifactModal({artifact:initial,task,objects,onClose,onChanged,onNavigate,onEdit}:{artifact:Artifact;task?:CreativeTask;objects:StoryObject[];onClose:()=>void;onChanged:()=>void;onNavigate:(id:string)=>void;onEdit:(o:StoryObject)=>void}){
  const [a,setA]=useState(initial);const [tab,setTab]=useState('result');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [replacement,setReplacement]=useState(initial.data.content??'');const [partial,setPartial]=useState(false);const [reasons,setReasons]=useState<Record<string,string>>({});const draft=useRef<HTMLTextAreaElement>(null);
  const source=objects.find(o=>o.id===a.chapterId);const original=a.data.original??source?.body??'';const issues=a.data.review?.issues??[];
  const mutate=async(action:string,body:any={})=>{setBusy(true);setError('');try{const result=await api(`/projects/${a.projectId}/artifacts/${a.id}/${action}`,body);setA(result);onChanged();if(action!=='issues')onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const locate=(quote:string)=>{setTab('result');setTimeout(()=>{const el=draft.current;if(el){const start=el.value.indexOf(quote);el.focus();el.setSelectionRange(Math.max(0,start),Math.max(0,start)+quote.length);el.scrollTop=(el.value.slice(0,start).split('\n').length-1)*30;}},0);};
  return <Modal title={a.type==='chapter'?`${source?.title??'章节成果'} · ${statusText[a.status]}`:a.type==='edit'?'选区修改提案':'创作成果'} onClose={onClose} wide><div className="artifact-review">
    {error&&<div className="notice error" role="alert">{error}</div>}{a.status==='stale'&&<div className="notice">此成果基于旧版本，已隔离保存。请按新版本重新委派。</div>}
    <div className="tabs">{[['result','成果',BookOpen],['diff','修改 Diff',FileDiff],['review',`审校 ${issues.length}`,AlertTriangle],['context','资料依据',Layers]].map(([key,label,Icon]:any)=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={15}/>{label}</button>)}</div>
    {tab==='result'&&(a.data.content!==undefined?<><div className="result-meta"><span>{countWords(a.data.content)} 字</span><span>基于作品修订 {a.baseRevision}</span>{a.chapterId&&<button onClick={()=>onNavigate(a.chapterId!)}>在写作模式查看 <ArrowUpRight size={13}/></button>}</div><textarea ref={draft} aria-label="成果正文" className="result-prose" readOnly value={a.data.content}/>{a.type==='edit'&&a.status==='pending'&&<><label className="check-field"><input type="checkbox" checked={partial} onChange={e=>setPartial(e.target.checked)}/>部分采用：先调整替换内容</label>{partial&&<textarea aria-label="部分采用的替换内容" rows={6} value={replacement} onChange={e=>setReplacement(e.target.value)}/>}</>}{a.data.review?.summary&&<div className="note-card"><h4>本章摘要</h4><p>{a.data.review.summary}</p></div>}</>:<>
      {a.data.rationale&&<div className="note-card"><h3>选择依据</h3><p>{a.data.rationale}</p></div>}
      {a.data.directions?.map((d:any,n:number)=><article className="direction" key={n}><span className="eyebrow">方向 0{n+1} {n===a.data.chosen?'· 当前选择':''}</span><h3>{d.title}</h3><p>{d.premise}</p><dl>{[['hook','核心卖点'],['protagonist','主角'],['desire','核心欲望'],['conflict','主要冲突'],['engine','长篇驱动'],['world','初始世界'],['firstStage','第一阶段'],['risk','主要风险']].map(([key,label])=><div key={key}><dt>{label}</dt><dd>{d[key]}</dd></div>)}</dl></article>)}
      {a.data.objects?.map((o:any,n:number)=><div className="note-card" key={n}><span className="badge">{o.kind}</span><h3>{o.title}</h3><p>{o.body||o.fields?.goal}</p>{o.source?.quote&&<blockquote>{o.source.quote}</blockquote>}</div>)}
      {a.data.ideas?.map((i:any,n:number)=><div className="note-card" key={n}><h3>{i.title}</h3><p>{i.body}</p><small>{i.tradeoff}</small></div>)}
      {a.data.changes?.map((c:any)=><div className="note-card" key={c.id}><h3>{c.title??objects.find(o=>o.id===c.id)?.title}</h3><p>{c.body}</p></div>)}
      {a.data.impacts?.map((i:any)=><div className="source-line" key={i.id}><span className="badge">{i.certainty==='known'?'明确依赖':'可能受影响'}</span><p>{objects.find(o=>o.id===i.id)?.title??'相关创作任务'}：{i.reason}</p></div>)}
      {a.data.diagnostic&&<pre>{JSON.stringify(a.data.diagnostic,null,2)}</pre>}
    </>)}
    {tab==='diff'&&<div className="diff-view">{a.data.content!==undefined?diffLines(a.type==='edit'?(task?.range?.expectedText??''):original,a.data.content).map((part,n)=><pre key={n} className={part.added?'added':part.removed?'removed':'unchanged'}><span>{part.added?'+':part.removed?'−':' '}</span>{part.value}</pre>):a.data.changes?.map((c:any)=><div key={c.id}><h4>{objects.find(o=>o.id===c.id)?.title}</h4>{diffLines(String(objects.find(o=>o.id===c.id)?.fields.goal??''),c.body).map((p,n)=><pre key={n} className={p.added?'added':p.removed?'removed':'unchanged'}>{p.value}</pre>)}</div>)??<p>此成果新增资料，未替换现有正文。</p>}</div>}
    {tab==='review'&&<><p className="muted">结构化硬约束使用确定性校验；人物动机、对白与节奏是 AI 建议，不代表文学质量证明。</p>{!a.data.review?<p>此产物尚未完成审校，正文不会被自动接受。</p>:!issues.length?<div className="empty-inline"><Check size={26}/><h3>本次检查未发现问题</h3><p>保留人工审读，继续关注后续章节的状态变化。</p></div>:issues.map((i:any)=><article className={`review-issue ${i.blocks?'blocking':''}`} key={i.id}><div className="object-top"><span className="badge">{i.engine==='deterministic'?'结构校验':'AI 审读'}</span><span className="badge">{i.blocks?'阻塞接受':i.severity==='advice'?'建议':'风险'}</span><span>{i.status==='open'?'待处理':i.status==='intentional'?'有意安排':i.status==='ignored'?'已忽略':'已解决'}</span></div><h3>{i.message}</h3><blockquote>{i.quote||'整章范围'}</blockquote>{i.sourceQuote&&<div className="source-quote"><small>冲突资料</small><blockquote>{i.sourceQuote}</blockquote></div>}<p>{i.rationale}</p><p><strong>建议：</strong>{i.suggestion}</p><div className="inline-actions"><button onClick={()=>locate(i.quote)}>定位原文 <Search size={13}/></button>{i.sourceId&&<button onClick={()=>{const o=objects.find(o=>o.id===i.sourceId);if(o)onEdit(o);}}>提出设定变更</button>}</div>{i.status==='open'&&a.status==='pending'&&!(i.blocks&&i.engine==='deterministic')&&<div className="issue-decision"><input aria-label="处理理由" placeholder="说明忽略或有意安排的理由" value={reasons[i.id]??''} onChange={e=>setReasons({...reasons,[i.id]:e.target.value})}/><button disabled={busy} onClick={()=>void mutate('issues',{issueId:i.id,status:'ignored',reason:reasons[i.id]??''})}>忽略</button><button disabled={busy} onClick={()=>void mutate('issues',{issueId:i.id,status:'intentional',reason:reasons[i.id]??''})}>有意安排</button></div>}{i.reason&&<p className="muted">作者决定：{i.reason}</p>}</article>)}
      {a.data.review?.claims?.length>0&&<details><summary>候选事实（{a.data.review.claims.length}）</summary>{a.data.review.claims.map((c:any,n:number)=><div className="note-card" key={n}><strong>{objects.find(o=>o.id===c.entityId)?.title} · {c.property} = {c.value}</strong><blockquote>{c.quote}</blockquote><small>{c.modality} · {c.inference?'推断':'直接依据'}</small></div>)}</details>}</>}
    {tab==='context'&&<ContextTrace context={a.data.context}/>}
    <div className="form-footer"><span className="muted">{a.status==='pending'?'接受会验证版本，并提交正文及关联状态。':statusText[a.status]}</span>{a.status==='pending'&&<><button disabled={busy} onClick={()=>void mutate('reject')}>拒绝</button><button className="solid" disabled={busy||issues.some((i:any)=>i.blocks&&i.status==='open')||a.type==='chapter'&&!a.data.review} onClick={()=>void mutate('accept',partial?{partialText:replacement}:{})}><Check size={15}/>{busy?'正在提交…':'接受成果'}</button></>}</div>
  </div></Modal>;
}
