import { useRef,useState } from 'react';import { diffLines } from 'diff';import { Check,ArrowUpRight,AlertTriangle,BookOpen,FileDiff,Layers,Search } from 'lucide-react';
import { Modal,Field } from './Modal.js';import {kindLabels,fieldLabels} from './Objects.js';import { api,statusText } from './api.js';import { countWords,type Artifact,type CreativeTask,type StoryObject } from '../contracts.js';
export function ContextTrace({context}:{context:any}){if(!context)return <p className="muted">此成果没有生成上下文记录。</p>;return <div className="context-trace"><div className="trace-summary"><strong>{context.used.toLocaleString()} / {context.budget.toLocaleString()} 字符</strong><span>作品修订 {context.revision}</span></div>{context.missing?.map((x:string)=><p className="notice" key={x}>{x}</p>)}{context.items?.map((i:any)=><details key={i.id}><summary><span className="badge">{i.kind}</span> {i.mandatory?'锁定约束 · ':''}{i.reason}<small>版本 {i.version}</small></summary><pre>{i.text}</pre></details>)}<details><summary>因预算或版本省略的资料（{context.omitted?.length??0}）</summary>{context.omitted?.map((i:any)=><p key={i.id}>{i.id} · {i.reason}</p>)}</details></div>;}
export function ArtifactModal({onInspect,artifact:initial,task,objects,onClose,onChanged,onNavigate,onEdit,onCreate}:{onInspect?:(id?:string)=>void;artifact:Artifact;task?:CreativeTask;objects:StoryObject[];onClose:()=>void;onChanged:()=>void;onNavigate:(id:string)=>void;onEdit:(o:StoryObject)=>void;onCreate:(input:any)=>Promise<void>}){
  const [a,setA]=useState(initial);const [tab,setTab]=useState('result');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [replacement,setReplacement]=useState(initial.data.content??'');const [partial,setPartial]=useState(false);const [repairMode,setRepairMode]=useState(false);const [reasons,setReasons]=useState<Record<string,string>>({});const draft=useRef<HTMLTextAreaElement>(null);
  const source=objects.find(o=>o.id===a.chapterId);const original=a.data.original??source?.body??'';const issues=a.data.review?.issues??[];
  const mutate=async(action:string,body:any={})=>{setBusy(true);setError('');try{const result=await api(`/projects/${a.projectId}/artifacts/${a.id}/${action}`,body);setA(result);onChanged();if(action!=='issues')onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const locate=(quote:string)=>{setTab('result');setTimeout(()=>{const el=draft.current;if(el){const start=el.value.indexOf(quote);el.focus();el.setSelectionRange(Math.max(0,start),Math.max(0,start)+quote.length);el.scrollTop=(el.value.slice(0,start).split('\n').length-1)*30;}},0);};
  return <Modal title={a.type==='chapter'?`${source?.title??'章节成果'} · ${statusText[a.status]}`:a.type==='edit'?'选区修改提案':'创作成果'} onClose={onClose} wide><div className="artifact-review">
    {error&&<div className="notice error" role="alert">{error}</div>}{a.status==='stale'&&<div className="notice">此成果基于旧版本，已隔离保存。请按新版本重新委派。</div>}
    <button className="context-link" onClick={()=>onInspect?.(a.data.generation?.requestId)}>查看本次生成检查器</button>{a.data.generation&&<details><summary>原始响应与处理版本</summary><pre>{a.data.generation.rawResponse}</pre><p>配置 {a.data.generation.config.hash.slice(0,12)} · {a.data.generation.transformations.length} 条变换。最终正文与原始模型响应分别保留。</p></details>}{a.data.review?.relationships?.length>0&&<details><summary>本章关系变化提案（随正文一并接受）</summary>{a.data.review.relationships.map((r:any,n:number)=><div className="note-card" key={n}><p>{objects.find(o=>o.id===r.fromId)?.title} → {r.type} / {r.state} → {objects.find(o=>o.id===r.toId)?.title}</p><blockquote>{r.quote}</blockquote><p>{r.cause} · {r.visibility}</p></div>)}</details>}<div className="tabs">{[['result','成果',BookOpen],['diff','修改 Diff',FileDiff],['review',`审校 ${issues.length}`,AlertTriangle],['context','资料依据',Layers]].map(([key,label,Icon]:any)=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={15}/>{label}</button>)}</div>
    {tab==='result'&&(a.data.content!==undefined?<><div className="result-meta"><span>{countWords(a.data.content)} 字</span><span>基于作品修订 {a.baseRevision}</span>{a.chapterId&&<button onClick={()=>{onNavigate(a.chapterId!);onClose();}}>在写作模式查看 <ArrowUpRight size={13}/></button>}</div><textarea ref={draft} aria-label="成果正文" className="result-prose" readOnly={!repairMode} value={repairMode?replacement:a.data.content} onChange={e=>setReplacement(e.target.value)}/>{a.type==='edit'&&a.status==='pending'&&<><label className="check-field"><input type="checkbox" checked={partial} onChange={e=>setPartial(e.target.checked)}/>部分采用：先调整替换内容</label>{partial&&<textarea aria-label="部分采用的替换内容" rows={6} value={replacement} onChange={e=>setReplacement(e.target.value)}/>}</>}{a.type==="chapter"&&a.status==="pending"&&<div className="inline-actions"><button onClick={()=>{setRepairMode(!repairMode);setReplacement(a.data.content);}}>{repairMode?"取消工作稿修改":"局部修改后重新审校"}</button>{repairMode&&<button className="solid" disabled={busy} onClick={()=>{setBusy(true);void onCreate({kind:"review",goal:"审查作者手工修复后的工作稿，只修复明确问题，保留其余正文。",chapterId:a.chapterId,draftArtifactId:a.id,draft:replacement,provider:task?.provider??"dsh",targetWords:task?.targetWords??2000,autoAccept:false}).then(onClose).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>保存工作稿并重新审校</button>}</div>}{a.data.review?.summary&&<div className="note-card"><h4>本章摘要</h4><p>{a.data.review.summary}</p></div>}</>:<>
      {a.data.memory&&<div className="note-card"><h3>章节记忆提案</h3><p>{a.data.memory.summary}</p>{a.data.memory.scenes.map((s:any,n:number)=><details key={n} open><summary>{s.summary}</summary><p>{s.cause} → {s.effect}</p><blockquote>{s.quote}</blockquote></details>)}</div>}
      {a.data.rationale&&<div className="note-card"><h3>选择依据</h3><p>{a.data.rationale}</p></div>}
      {a.data.directions?.map((d:any,n:number)=><article className="direction" key={n}><span className="eyebrow">方向 0{n+1} {n===a.data.chosen?'· 当前选择':''}</span><h3>{d.title}</h3><p>{d.premise}</p><dl>{[['hook','核心卖点'],['protagonist','主角'],['desire','核心欲望'],['conflict','主要冲突'],['engine','长篇驱动'],['world','初始世界'],['firstStage','第一阶段'],['risk','主要风险']].map(([key,label])=><div key={key}><dt>{label}</dt><dd>{d[key]}</dd></div>)}</dl>{a.type==="setup"&&a.status==="pending"&&n!==a.data.chosen&&<button disabled={busy} onClick={()=>{setBusy(true);void api(`/projects/${a.projectId}/artifacts/${a.id}/reject`,{}).then(()=>onCreate({kind:"bootstrap",goal:`作者选择以下故事方向，请严格按它生成最小开书资料，不再改选其他题材或主角：《${d.title}》。故事前提：${d.premise}。主角：${d.protagonist}。核心欲望：${d.desire}。冲突：${d.conflict}。长篇驱动：${d.engine}。初始世界：${d.world}。第一阶段：${d.firstStage}。风险：${d.risk}。生成至多三章章纲，正文留空。`,provider:task?.provider??"dsh",autoAccept:false})).then(onClose).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>选择此方向并生成资料</button>}</article>)}
      {a.data.objects?.map((o:any,n:number)=><div className="note-card" key={n}><span className="badge">{kindLabels[o.kind as keyof typeof kindLabels]??o.kind}</span><h3>{o.title}</h3><p>{o.body||o.fields?.goal}</p>{Object.keys(o.fields??{}).length>0&&<details><summary>属性与关联</summary><dl className="contract-list">{Object.entries(o.fields).map(([key,value])=><div key={key}><dt>{fieldLabels[key]??key}</dt><dd>{(Array.isArray(value)?value:[value]).map(v=>objects.find(x=>x.id===v)?.title??String(v??"未填写")).join("、")}</dd></div>)}</dl></details>}{o.source?.quote&&<blockquote>{o.source.quote}</blockquote>}</div>)}
      {a.data.ideas?.map((i:any,n:number)=><div className="note-card" key={n}><h3>{i.title}</h3><p>{i.body}</p><small>{i.tradeoff}</small></div>)}
      {a.data.changes?.map((c:any)=><div className="note-card" key={c.id}><h3>{c.title??objects.find(o=>o.id===c.id)?.title}</h3><p>{c.body}</p></div>)}
      {a.data.impacts?.map((i:any)=><div className="source-line" key={i.id}><span className="badge">{i.certainty==='known'?'明确依赖':'可能受影响'}</span><p>{objects.find(o=>o.id===i.id)?.title??'相关创作任务'}：{i.reason}</p></div>)}
      {a.data.diagnostic&&<pre>{JSON.stringify(a.data.diagnostic,null,2)}</pre>}
    </>)}
    {tab==='diff'&&<div className="diff-view">{a.data.content!==undefined?diffLines(a.type==='edit'?(task?.range?.expectedText??''):original,a.data.content).map((part,n)=><pre key={n} className={part.added?'added':part.removed?'removed':'unchanged'}><span>{part.added?'+':part.removed?'−':' '}</span>{part.value}</pre>):a.data.changes?.map((c:any)=><div key={c.id}><h4>{objects.find(o=>o.id===c.id)?.title}</h4>{diffLines(JSON.stringify(a.data.beforePlans?.find((o:any)=>o.id===c.id)??objects.find(o=>o.id===c.id),null,2),JSON.stringify({...(a.data.beforePlans?.find((o:any)=>o.id===c.id)??objects.find(o=>o.id===c.id)),title:c.title??objects.find(o=>o.id===c.id)?.title,fields:{...(a.data.beforePlans?.find((o:any)=>o.id===c.id)?.fields??objects.find(o=>o.id===c.id)?.fields),...c.fields,goal:c.body}},null,2)).map((p,n)=><pre key={n} className={p.added?'added':p.removed?'removed':'unchanged'}>{p.value}</pre>)}</div>)??<p>此成果新增资料，未替换现有正文。</p>}</div>}
    {tab==='review'&&<><p className="muted">结构化硬约束使用确定性校验；人物动机、对白与节奏是 AI 建议，不代表文学质量证明。</p>{!a.data.review?<p>此产物尚未完成审校，正文不会被自动接受。</p>:!issues.length?<div className="empty-inline"><Check size={26}/><h3>本次检查未发现问题</h3><p>保留人工审读，继续关注后续章节的状态变化。</p></div>:issues.map((i:any)=><article className={`review-issue ${i.blocks?'blocking':''}`} key={i.id}><div className="object-top"><span className="badge">{i.engine==='deterministic'?'结构校验':'AI 审读'}</span><span className="badge">{i.blocks?'阻塞接受':i.severity==='advice'?'建议':'风险'}</span><span>{i.status==='open'?'待处理':i.status==='intentional'?'有意安排':i.status==='ignored'?'已忽略':'已解决'}</span></div><h3>{i.message}</h3><blockquote>{i.quote||'整章范围'}</blockquote>{i.sourceQuote&&<div className="source-quote"><small>冲突资料</small><blockquote>{i.sourceQuote}</blockquote></div>}<p>{i.rationale}</p><p><strong>建议：</strong>{i.suggestion}</p><div className="inline-actions"><button onClick={()=>locate(i.quote)}>定位原文 <Search size={13}/></button>{i.sourceId&&objects.some(o=>o.id===i.sourceId)&&<button onClick={()=>{const o=objects.find(o=>o.id===i.sourceId);if(o)onEdit(o);}}>提出设定变更</button>}</div>{i.status==='open'&&a.status==='pending'&&!(i.blocks&&i.engine==='deterministic')&&<div className="issue-decision"><input aria-label="处理理由" placeholder="说明忽略或有意安排的理由" value={reasons[i.id]??''} onChange={e=>setReasons({...reasons,[i.id]:e.target.value})}/><button disabled={busy} onClick={()=>void mutate('issues',{issueId:i.id,status:'ignored',reason:reasons[i.id]??''})}>忽略</button><button disabled={busy} onClick={()=>void mutate('issues',{issueId:i.id,status:'intentional',reason:reasons[i.id]??''})}>有意安排</button></div>}{i.reason&&<p className="muted">作者决定：{i.reason}</p>}</article>)}
      {a.data.review?.claims?.length>0&&<details><summary>候选事实（{a.data.review.claims.length}）</summary>{a.data.review.claims.map((c:any,n:number)=><div className="note-card" key={n}><strong>{objects.find(o=>o.id===c.entityId)?.title} · {c.property} = {c.value}</strong><blockquote>{c.quote}</blockquote><small>{c.modality} · {c.inference?'推断':'直接依据'}</small></div>)}</details>}</>}
    {tab==='context'&&<ContextTrace context={a.data.context}/>}
    {a.type==='replan'&&a.status==='accepted'&&<div className="note-card">{a.data.revertedAt?<p>此规划变更已撤销于 {new Date(a.data.revertedAt).toLocaleString('zh-CN')}</p>:<button disabled={busy||!a.data.beforePlans} onClick={()=>{setBusy(true);void api(`/projects/${a.projectId}`).then(s=>mutate('revert',{revision:s.project.revision})).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>撤销此规划变更</button>}</div>}
    <div className="form-footer"><span className="muted">{a.status==='pending'?'接受会验证版本，并提交正文及关联状态。':statusText[a.status]}</span>{a.status==='pending'&&<><button disabled={busy} onClick={()=>void mutate('reject')}>拒绝</button><button className="solid" disabled={busy||issues.some((i:any)=>i.blocks&&i.status==='open')||a.type==='chapter'&&!a.data.review} onClick={()=>void mutate('accept',partial?{partialText:replacement}:{})}><Check size={15}/>{busy?'正在提交…':'接受成果'}</button></>}</div>
  </div></Modal>;
}
