import { useEffect,useState } from 'react';
import { diffLines } from 'diff';
import { Modal,Field } from './Modal.js';
import { api } from './api.js';
import type { ConfigPatch,ConfigVersion } from '../config-contracts.js';
import type { StoryObject } from '../contracts.js';

export function TextDiff({before,after}:{before:string;after:string}){return <pre className="config-diff">{diffLines(before,after).map((part,n)=><span key={n} className={part.added?'added':part.removed?'removed':''}>{part.value}</span>)}</pre>;}
export function CreativeConfig({pid,objects,onClose,onDone}:{pid:string;objects:StoryObject[];onClose:()=>void;onDone:()=>void}){
  const [data,setData]=useState<any>(),[tab,setTab]=useState('style'),[draft,setDraft]=useState<ConfigPatch>({enabled:true,strategy:'novel'}),[name,setName]=useState('我的文风'),[selected,setSelected]=useState<string>(),[report,setReport]=useState<ConfigVersion>(),[adapt,setAdapt]=useState<any>(),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[rules,setRules]=useState('[]'),[input,setInput]=useState('她把信放在桌上。\n命运的齿轮开始转动。'),[stage,setStage]=useState('after'),[scope,setScope]=useState('prose'),[edited,setEdited]=useState(false),[result,setResult]=useState<any>();
  const base=`/projects/${pid}`;
  let parsedRules:any[]=[];try{const value=JSON.parse(rules);if(Array.isArray(value))parsedRules=value;}catch{}
  const toggleRule=(index:number,enabled:boolean)=>setRules(JSON.stringify(parsedRules.map((r,n)=>n===index?{...r,enabled}:r),null,2));
  const load=async()=>{const value=await api(base+'/configurations');setData(value);return value;};
  const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
  useEffect(()=>{void act(async()=>{const value=await load();setDraft(value.effective.config);setRules(JSON.stringify(value.effective.config.regex??[],null,2));});},[pid]);
  const native=(key:string,value:string|string[])=>setDraft({...draft,native:{...draft.native,[key]:value}});
  const saved=async(v:ConfigVersion)=>{setSelected(v.id);setDraft(v.config);setRules(JSON.stringify(v.config.regex??[],null,2));setReport(v);setName(v.name);await load();setNotice('版本已保存。选择应用范围后，后续任务才会使用它。');};
  const bind=async(scope:string,versionId:string|null)=>{await api(base+'/configurations/bind',{scope,versionId,expected:data.bindings[scope]??null});await load();onDone();setNotice('应用范围已更新。运行中的任务仍使用原配置快照。');};
  return <Modal title="创作配置" wide onClose={onClose}><div className="config-workbench"><p className="muted">正文文风、模型采样和文本规则分别管理。任务开始时固定版本；这里的修改不会改写历史正文。</p><div className="tabs">{[['style','文风组合'],['import','导入与兼容'],['regex','文本规则测试']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>{error&&<div role="alert" className="notice error">{error}</div>}{notice&&<p role="status" className="notice">{notice}</p>}{!data?<p>{busy?'正在读取本地配置…':<button onClick={()=>void act(load)}>重新读取配置</button>}</p>:<>
    <div className="config-current"><strong>当前有效配置</strong><span>{data.effective.config.enabled?data.effective.versions.map((v:any)=>v.name).join(' → ')||'原生组合':'原有作品文风'}</span><details><summary>来源与覆盖顺序</summary><pre>{JSON.stringify(data.effective.origins,null,2)}</pre><p>全局 → 项目 → 本次任务。相同字段以后者为准，列表整体替换。</p></details></div>
    <div className="form-grid"><Field label="已保存版本"><select value={selected??''} onChange={e=>{const v=data.versions.find((v:any)=>v.id===e.target.value);if(v){setSelected(v.id);setName(v.name);setDraft(v.config);setReport(v);setRules(JSON.stringify(v.config.regex??[],null,2));}}}><option value="">选择或新建配置</option>{data.versions.map((v:any)=><option key={v.id} value={v.id}>{v.name} · {v.id.slice(-6)}</option>)}</select></Field><div className="inline-actions config-bind"><button disabled={busy||!selected||report?.applicable===false} onClick={()=>void act(()=>bind('project',selected!))}>应用到本作品</button><button disabled={busy||!selected||report?.applicable===false} onClick={()=>void act(()=>bind('global',selected!))}>设为全局默认</button><button disabled={busy||!data.bindings.project} onClick={()=>void act(()=>bind('project',null))}>取消作品覆盖</button><button disabled={busy||!data.bindings.global} onClick={()=>void act(()=>bind('global',null))}>清除全局默认</button></div></div>
    {tab==='style'&&<><div className="style-samples">{data.samples.map((p:any)=><button key={p.id} onClick={()=>{setName(p.name);setDraft({...draft,...p.config,native:p.config.native,entries:[]});setNotice('已用原生组合替换文学条目，保留文本规则；保存新版本后再应用。');}}>{p.name}</button>)}</div><Field label="版本名称"><input value={name} onChange={e=>setName(e.target.value)}/></Field><label className="check-field"><input type="checkbox" checked={draft.enabled===true} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>启用创作配置</label><div className="form-grid">{[['base','基础文风'],['viewpoint','视角'],['tense','时态'],['dialogue','对白规则'],['project','作品特殊要求'],['scene','场景临时要求']].map(([key,label])=><Field key={key} label={label}><textarea rows={key==='base'?4:2} value={(draft.native as any)?.[key]??''} onChange={e=>native(key,e.target.value)}/></Field>)}</div><Field label="禁用表达（每行一条）"><textarea rows={2} value={draft.native?.forbidden?.join('\n')??''} onChange={e=>native('forbidden',e.target.value.split('\n').filter(Boolean))}/></Field>
    <details><summary>宏绑定与采样参数</summary><div className="form-grid"><Field label="{{char}} 绑定角色"><select value={draft.bindings?.characterId??''} onChange={e=>setDraft({...draft,bindings:{...draft.bindings,characterId:e.target.value||undefined}})}><option value="">未绑定（宏会报警）</option>{objects.filter(o=>o.kind==='character').map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></Field><Field label="{{user}} 作者称呼"><input value={draft.bindings?.authorName??''} onChange={e=>setDraft({...draft,bindings:{...draft.bindings,authorName:e.target.value}})}/></Field><Field label="默认视角人物"><select value={draft.bindings?.viewpointId??''} onChange={e=>setDraft({...draft,bindings:{...draft.bindings,viewpointId:e.target.value||undefined,audience:e.target.value?'character':'author'}})}><option value="">由任务指定</option>{objects.filter(o=>o.kind==='character').map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></Field><Field label="Temperature（仅正文）"><input type="number" min="0" max="2" step="0.1" value={draft.sampling?.temperature??''} onChange={e=>setDraft({...draft,sampling:{...draft.sampling,temperature:e.target.value===''?undefined:Number(e.target.value)}})}/></Field></div><p className="muted">DSH 当前未暴露 top_p 等参数。角色、作者与视角人物分别绑定；不执行脚本或变量写操作。</p></details>
    <label className="check-field"><input type="checkbox" checked={draft.memory?.enabled??false} onChange={e=>setDraft({...draft,memory:{enabled:e.target.checked,checkpointEvery:5,recallLimit:6}})}/>接受章节后维护长篇记忆</label><button className="solid" disabled={busy} onClick={()=>void act(async()=>saved(await api(base+'/configurations',{name,config:{...draft,regex:JSON.parse(rules)},parentId:selected})))}>保存为独立版本</button></>}
    {tab==='import'&&<><Field label="导入 JSON 配置" hint="先预览兼容报告，再保存版本，最后选择应用范围。"><input type="file" accept=".json" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void act(async()=>{const v=await api(base+'/configurations/preview',{raw:await f.text(),name:f.name});setReport(v);setAdapt(undefined);});}}/></Field>{report&&<><h3>{report.name} <span className="badge">{report.format}</span></h3><div className="compat-list">{report.report.map((r,n)=><p key={n}><span className={`badge ${r.status}`}>{r.status}</span><strong>{r.field}</strong> {r.message}</p>)}</div><details><summary>规范化内容、未识别字段和原始文件</summary><pre>{JSON.stringify({config:report.config,unknown:report.unknown,converter:report.converter,source:report.source},null,2)}</pre><pre>{report.raw}</pre></details><div className="inline-actions"><button disabled={busy||data.versions.some((v:any)=>v.id===report.id)} onClick={()=>void act(async()=>saved(await api(base+'/configurations',{raw:report.raw,name:report.name})))}>保存导入版本</button><button disabled={busy||!selected||report.format!=='chat-completion'||selected!==report.id} onClick={()=>void act(async()=>setAdapt(await api(base+`/configurations/${selected}/adapt`,{})))}>预览小说适配变更</button></div>{adapt&&<><p>{adapt.warning}</p><TextDiff before={adapt.before} after={adapt.after}/><button disabled={busy} onClick={()=>void act(async()=>{await saved(await api(base+'/configurations',{name:name+' · 小说适配',config:adapt.config,parentId:selected}));setAdapt(undefined);})}>接受变更并保存独立版本</button></>}</>}</>}
    {tab==='regex'&&<><p>顺序执行 JavaScript 正则，每条最多 1000 次匹配、500 ms。不会运行替换文本内的 HTML 或脚本。命中位置以 UTF-16 索引计。</p><div className="inline-actions">{parsedRules.map((rule,n)=><label className="check-field" key={n}><input type="checkbox" checked={rule.enabled!==false} onChange={e=>toggleRule(n,e.target.checked)}/>{rule.name??`规则 ${n+1}`}</label>)}</div><Field label="规则 JSON"><textarea className="code-input" rows={9} value={rules} onChange={e=>setRules(e.target.value)}/></Field><button onClick={()=>void act(async()=>setRules(JSON.stringify([...(JSON.parse(rules||'[]')),{id:'rule-'+Date.now(),name:'删除套话',pattern:'命运的齿轮开始转动。',flags:'gu',replacement:'',enabled:true,order:0,stage:'after',scope:'prose',onEdit:false,macros:'none',supported:true}],null,2)))}>添加示例规则</button><div className="form-grid"><Field label="处理阶段"><select value={stage} onChange={e=>{setStage(e.target.value);setScope(e.target.value==='before'?'goal':'prose');}}><option value="before">发送前</option><option value="after">完整生成后</option><option value="display">仅展示</option></select></Field><Field label="文本范围"><select value={scope} onChange={e=>setScope(e.target.value)}>{(stage==='before'?['goal','selection','world']:['prose']).map(s=><option key={s}>{s}</option>)}</select></Field></div><label className="check-field"><input type="checkbox" checked={edited} onChange={e=>setEdited(e.target.checked)}/>测试编辑触发（只执行 onEdit 规则）</label><Field label="测试输入"><textarea rows={6} value={input} onChange={e=>setInput(e.target.value)}/></Field><div className="inline-actions"><button disabled={busy} onClick={()=>void act(async()=>setResult(await api(base+'/regex-test',{input,rules:JSON.parse(rules),stage,scope,edited,config:draft})))}>运行规则测试</button><button disabled={busy} onClick={()=>void act(async()=>saved(await api(base+'/configurations',{name:name+' · 文本规则',config:{...draft,enabled:true,regex:JSON.parse(rules)},parentId:selected})))}>保存规则为配置新版本</button></div>{result&&<>{result.warnings?.map((w:string,n:number)=><p className="notice" key={n}>{w}</p>)}<TextDiff before={result.original} after={result.text}/>{result.trace.map((r:any,n:number)=><details key={n} open={!!r.error}><summary>{n+1}. {r.name} · {r.matches.length} 次 · {r.elapsedMs} ms</summary>{r.error&&<p role="alert" className="notice error">{r.error}</p>}<pre>{JSON.stringify(r.matches,null,2)}</pre></details>)}</>}</>}
    </>}</div></Modal>;
}
