import { useEffect, useState } from 'react';
import { BookMarked, Feather, Upload } from 'lucide-react';
import { api } from './api.js';
import { Field } from './Modal.js';
import type { ConfigPatch, ConfigVersion } from '../config-contracts.js';

export function CreativeAssets(){
  const [data,setData]=useState<any>(),[selected,setSelected]=useState<ConfigVersion>(),[name,setName]=useState('我的全局文风');
  const [draft,setDraft]=useState<ConfigPatch>({enabled:true,strategy:'novel',native:{base:'克制、具体，以行动和对白推动故事。'}});
  const [report,setReport]=useState<ConfigVersion>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const load=async()=>setData(await api('/creative-assets'));
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(caught){setError((caught as Error).message);}finally{setBusy(false);}};
  useEffect(()=>{void run(load);},[]);
  const choose=(version:ConfigVersion)=>{setSelected(version);setName(version.name);setDraft(version.config);setReport(undefined);};
  const current=selected??report;
  const unsafe=!!current?.config.bindings?.characterId||!!current?.config.bindings?.viewpointId;
  return <section className="creative-assets"><div className="global-intro"><span className="eyebrow">CREATIVE ASSETS</span><h1>创作资产</h1><p>全局文风和预设保存在同一套配置版本中。项目仍可覆盖；已经运行的任务使用固定快照。</p></div>
    {error&&<p className="notice error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
    <div className="assets-layout"><aside className="assets-list"><h2>配置版本</h2>{!data?<p>正在读取…</p>:<><button onClick={()=>{setSelected(undefined);setReport(undefined);setName('我的全局文风');}}>＋ 新建文风</button>{data.versions.map((v:ConfigVersion)=><button className={selected?.id===v.id?'active':''} key={v.id} onClick={()=>choose(v)}><Feather size={15}/><span>{v.name}<small>{v.id===data.global?'全局已应用':v.applicable?'可应用':'仅留存，不兼容'}</small></span></button>)}{!data.versions.length&&<p className="muted">还没有配置版本。可以选择原创文风，或导入 JSON 预设。</p>}</>}</aside>
    <div className="assets-editor"><div className="note-card"><h2><BookMarked size={18}/>实际生效的全局规则</h2><p>{data?.effective.versions.map((v:any)=>v.name).join(' → ')||'原有作品文风'}</p><details><summary>覆盖来源与完整配置</summary><pre>{JSON.stringify({origins:data?.effective.origins,config:data?.effective.config},null,2)}</pre></details><p className="muted">全局 → 项目 → 任务；角色实例属于具体作品，不能直接绑定为全局角色。</p></div>
      <div className="note-card"><h2>原生文风与版本</h2><div className="style-samples">{data?.samples.map((sample:any)=><button key={sample.id} onClick={()=>{setDraft({...sample.config,enabled:true});setSelected(undefined);setName(sample.name+' · 我的版本');}}>{sample.name}</button>)}</div><Field label="版本名称"><input value={name} onChange={event=>setName(event.target.value)}/></Field><div className="form-grid"><Field label="基础文风"><textarea rows={4} value={draft.native?.base??''} onChange={event=>setDraft({...draft,native:{...draft.native,base:event.target.value}})}/></Field><Field label="视角与时态"><textarea rows={4} value={[draft.native?.viewpoint,draft.native?.tense].filter(Boolean).join('\n')} onChange={event=>setDraft({...draft,native:{...draft.native,viewpoint:event.target.value,tense:''}})}/></Field><Field label="对白规则"><textarea rows={3} value={draft.native?.dialogue??''} onChange={event=>setDraft({...draft,native:{...draft.native,dialogue:event.target.value}})}/></Field><Field label="禁用表达（每行一项）"><textarea rows={3} value={draft.native?.forbidden?.join('\n')??''} onChange={event=>setDraft({...draft,native:{...draft.native,forbidden:event.target.value.split('\n').filter(Boolean)}})}/></Field></div><button className="solid" disabled={busy||!name.trim()} onClick={()=>void run(async()=>{const v=await api<ConfigVersion>('/creative-assets/save',{name,config:{...draft,enabled:true},parentId:selected?.id});choose(v);await load();setNotice('已保存独立版本；尚未自动应用。');})}>保存独立版本</button></div>
      <div className="note-card"><h2><Upload size={18}/>导入 Chat Completion 预设</h2><Field label="选择 JSON 文件" hint="先预览兼容报告，再保存版本，最后选择全局应用。"><input type="file" accept=".json" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void run(async()=>{setReport(await api('/creative-assets/preview',{raw:await file.text(),name:file.name}));setSelected(undefined);});}}/></Field>{report&&<><h3>{report.name} · {report.format}</h3>{report.report.map((entry,index)=><p key={index}><span className={`badge ${entry.status}`}>{entry.status}</span> {entry.field} · {entry.message}</p>)}<details><summary>未识别字段与规范化内容</summary><pre>{JSON.stringify({unknown:report.unknown,config:report.config},null,2)}</pre></details>{!selected&&<button disabled={busy||!report.applicable} onClick={()=>void run(async()=>{const version=await api<ConfigVersion>('/creative-assets/save',{name:report.name,raw:report.raw});choose(version);await load();setNotice('已保存导入版本；还没有应用。');})}>保存导入版本</button>}</>}</div>
      {selected&&<div className="note-card"><h2>应用与版本依据</h2><p>{selected.name} · {selected.converter} · {selected.source} · {new Date(selected.createdAt).toLocaleString('zh-CN')}</p>{unsafe&&<p className="notice">此版本绑定了作品角色 ID，只能在那本作品内应用。创建不带角色绑定的独立版本后才能设为全局。</p>}{selected.report.map((entry,index)=><p key={index}><span className={`badge ${entry.status}`}>{entry.status}</span> {entry.message}</p>)}<div className="inline-actions"><button className="solid" disabled={busy||!selected.applicable||unsafe||selected.id===data?.global} onClick={()=>void run(async()=>{await api('/creative-assets/bind',{versionId:selected.id,expected:data.global??null});await load();setNotice('全局规则已应用；当前运行任务不改变。');})}>设为全局默认</button><button disabled={busy||!data?.global} onClick={()=>void run(async()=>{await api('/creative-assets/bind',{versionId:null,expected:data.global});await load();setNotice('已取消全局默认，项目覆盖仍保留。');})}>清除全局默认</button></div></div>}
    </div></div>
  </section>;
}
