import { useEffect,useState } from 'react';
import { diffLines } from 'diff';
import { Modal,Field } from './Modal.js';
import { api } from './api.js';
import type { ConfigPatch,ConfigVersion } from '../config-contracts.js';
import type { StoryObject } from '../contracts.js';

export function TextDiff({before,after}:{before:string;after:string}){return <pre className="config-diff">{diffLines(before,after).map((part,n)=><span key={n} className={part.added?'added':part.removed?'removed':''}>{part.value}</span>)}</pre>;}
export function CreativeConfig({pid,objects,onClose,onDone}:{pid:string;objects:StoryObject[];onClose:()=>void;onDone:()=>void}){
  const [data,setData]=useState<any>(),[tab,setTab]=useState('style'),[draft,setDraft]=useState<ConfigPatch>({enabled:true,strategy:'novel'}),[name,setName]=useState('我的文风'),[selected,setSelected]=useState<string>(),[report,setReport]=useState<ConfigVersion>(),[adapt,setAdapt]=useState<any>(),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[rules,setRules]=useState('[]'),[input,setInput]=useState('她把信放在桌上。\n命运的齿轮开始转动。'),[stage,setStage]=useState('after'),[scope,setScope]=useState('prose'),[edited,setEdited]=useState(false),[result,setResult]=useState<any>();
  const base=`/projects/${pid}`;
  let parsedRules:any[]=[];try{const value=JSON.parse(rules);if(Array.isArray(value))parsedRules=value;}catch{}
  const toggleRule=(index:number,enabled:boolean)=>setRules(JSON.stringify(parsedRules.map((r,n)=>n===index?{...r,enabled}:r),null,2));
  const load=async()=>{const value=await api(base+'/configurations');setData(value);return value;};
  const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
  useEffect(()=>{void act(async()=>{const value=await load();setDraft(value.effective.config);setRules(JSON.stringify(value.effective.config.regex??[],null,2));});},[pid]);
  const native=(key:string,value:string|string[])=>setDraft({...draft,native:{...draft.native,[key]:value}});
  const saved=async(v:ConfigVersion)=>{setSelected(v.id);setDraft(v.config);setRules(JSON.stringify(v.config.regex??[],null,2));setReport(v);setName(v.name);await load();setNotice('版本已保存。选择应用范围后，后续任务才会使用它。');};
  const bind=async(scope:string,versionId:string|null)=>{await api(base+'/configurations/bind',{scope,versionId,expected:data.bindings[scope]??null});await load();onDone();setNotice('应用范围已更新。运行中的任务仍使用原配置快照。');};
  return <Modal title="创作配置" wide onClose={onClose}><div className="config-workbench"><p className="muted">正文文风、模型采样和文本规则分别管理。任务开始时固定版本；这里的修改不会改写历史正文。</p><div className="tabs">{[['style','文风组合'],['import','导入与兼容'],['regex','文本规则测试']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>{error&&<div role="alert" className="notice error">{error}</div>}{notice&&<p role="status" className="notice">{notice}</p>}{!data?<p>{busy?'正在读取本地配置…':<button onClick={()=>void act(load)}>重新读取配置</button>}</p>:<>
    <div className="config-current"><strong>当前有效配置</strong><span>{data.effective.config.enabled?data.effective.versions.map((v:any)=>v.name).join(' → ')||'原生组合':'原有作品文风'}</span><details><summary>来源与覆盖顺序</summary><pre>{JSON.stringify(data.effective.origins,null,2)}</pre><p>全局 → 项目 → 本次任务。相同字段以后者为准，列表整体替换。</p></details></div>
    <div className="form-grid"><Field label="已保存版本"><select value={selected??''} onChange={e=>{const v=data.versions.find((v:any)=>v.id===e.target.value);if(v){setSelected(v.id);setName(v.name);setDraft(v.config);setReport(v);setRules(JSON.stringify(v.config.regex??[],null,2));}}}><option value="">选择或新建配置</option>{data.versions.map((v:any)=><option key={v.id} value={v.id}>{v.name} · {v.id.slice(-6)}</option>)}</select></Field><div className="inline-actions config-bind"><button disabled={busy||!selected||report?.applicable===false} onClick={()=>void act(()=>bind('project',selected!))}>应用到本作品</button><button disabled={busy||!selected||report?.applicable===false} onClick={()=>void act(()=>bind('global',selected!))}>设为全局默认</button><button disabled={busy||!data.bindings.project} onClick={()=>void act(()=>bind('project',null))}>取消作品覆盖</button><button disabled={busy||!data.bindings.global} onClick={()=>void act(()=>bind('global',null))}>清除全局默认</button></div></div>
    {tab==='style'&&<><div className="style-samples">{data.samples.map((p:any)=><button key={p.id} onClick={()=>{setName(p.name);setDraft({...draft,...p.config,native:p.config.native,entries:[]});setNotice('已用原生组合替换文学条目，保留文本规则；保存新版本后再应用。');}}>{p.name}</button>)}</div><Field label="版本名称"><input value={name} onChange={e=>setName(e.target.value)}/></Field><label className="check-field"><input type="checkbox" checked={draft.enabled===true} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>启用创作配置</label><div className="form-grid">{[['base','基础文风'],['viewpoint','视角'],['tense','时态'],['dialogue','对白规则'],['project','作品特殊要求'],['scene','场景临时要求']].map(([key,label])=><Field key={key} label={label}><textarea rows={key==='base'?4:2} value={(draft.native as any)?.[key]??''} onChange={e=>native(key,e.target.value)}/></Field>)}</div><Field label="禁用表达（每行一条）"><textarea rows={2} value={draft.native?.forbidden?.join('\n')??''} onChange={e=>native('forbidden',e.target.value.split('\n').filter(Boolean))}/></Field>
    <details><summary>宏绑定与采样参数</summary><div className="form-grid"><Field label="{{char}} 绑定角色"><select value={draft.bindings?.characterId??''} onChange={e=>setDraft({...draft,bindings:{...draft.bindings,characterId:e.target.value||undefined}})}><option value="">未绑定（宏会报警）</option>{objects.filter(o=>o.kind==='character').map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></Field><Field label="{{user}} 作者称呼"><input value={draft.bindings?.authorName??''} onChange={e=>setDraft({...draft,bindings:{...draft.bindings,authorName:e.target.value}})}/></Field><Field label="默认视角人物"><select value={draft.bindings?.viewpointId??''} onChange={e=>setDraft({...draft,bindings:{...draft.bindings,viewpointId:e.target.value||undefined,audience:e.target.value?'character':'author'}})}><option value="">由任务指定</option>{objects.filter(o=>o.kind==='character').map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></Field><Field label="Temperature（仅正文）"><input type="number" min="0" max="2" step="0.1" value={draft.sampling?.temperature??''} onChange={e=>setDraft({...draft,sampling:{...draft.sampling,temperature:e.target.value===''?undefined:Number(e.target.value)}})}/></Field></div><p className="muted">DSH 当前未暴露 top_p 等参数。角色、作者与视角人物分别绑定；不执行脚本或变量写操作。</p></details>
    <label className="check-field"><input type="checkbox" checked={draft.memory?.enabled??false} onChange={e=>setDraft({...draft,memory:{enabled:e.target.checked,checkpointEvery:5,recallLimit:6}})}/>接受章节后维护长篇记忆</label><button className="solid" disabled={busy} onClick={()=>void act(async()=>saved(await api(base+'/configurations',{name,config:{...draft,regex:JSON.parse(rules)},parentId:selected})))}>保存为独立版本</button></>}
    {tab==='import'&&<><Field label="导入 JSON 配置" hint="先预览兼容报告，再保存版本，最后选择应用范围。"><input type="file" accept=".json" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void act(async()=>{const v=await api(base+'/configurations/preview',{raw:await f.text(),name:f.name});setReport(v);setAdapt(undefined);});}}/></Field>{report&&<><h3>{report.name} <span className="badge">{report.format}</span></h3><div className="compat-list">{report.report.map((r,n)=><p key={n}><span className={`badge ${r.status}`}>{r.status}</span><strong>{r.field}</strong> {r.message}</p>)}</div><details><summary>规范化内容、未识别字段和原始文件</summary><pre>{JSON.stringify({config:report.config,unknown:report.unknown,converter:report.converter,source:report.source},null,2)}</pre><pre>{report.raw}</pre></details><div className="inline-actions"><button disabled={busy||data.versions.some((v:any)=>v.id===report.id)} onClick={()=>void act(async()=>saved(await api(base+'/configurations',{raw:report.raw,name:report.name})))}>保存导入版本</button><button disabled={busy||!selected||report.format!=='chat-completion'||selected!==report.id} onClick={()=>void act(async()=>setAdapt(await api(base+`/configurations/${selected}/adapt`,{})))}>预览小说适配变更</button></div>{adapt&&<><p>{adapt.warning}</p><TextDiff before={adapt.before} after={adapt.after}/><button disabled={busy} onClick={()=>void act(async()=>{await saved(await api(base+'/configurations',{name:name+' · 小说适配',config:adapt.config,parentId:selected}));setAdapt(undefined);})}>接受变更并保存独立版本</button></>}</>}</>}
    {tab==='regex'&&<><p>顺序执行 JavaScript 正则，每条最多 1000 次匹配、500 ms。不会运行替换文本内的 HTML 或脚本。命中位置以 UTF-16 索引计。</p><div className="inline-actions">{parsedRules.map((rule,n)=><label className="check-field" key={n}><input type="checkbox" checked={rule.enabled!==false} onChange={e=>toggleRule(n,e.target.checked)}/>{rule.name??`规则 ${n+1}`}</label>)}</div><Field label="规则 JSON"><textarea className="code-input" rows={9} value={rules} onChange={e=>setRules(e.target.value)}/></Field><button onClick={()=>void act(async()=>setRules(JSON.stringify([...(JSON.parse(rules||'[]')),{id:'rule-'+Date.now(),name:'删除套话',pattern:'命运的齿轮开始转动。',flags:'gu',replacement:'',enabled:true,order:0,stage:'after',scope:'prose',onEdit:false,macros:'none',supported:true}],null,2)))}>添加示例规则</button><div className="form-grid"><Field label="处理阶段"><select value={stage} onChange={e=>{setStage(e.target.value);setScope(e.target.value==='before'?'goal':'prose');}}><option value="before">发送前</option><option value="after">完整生成后</option><option value="display">仅展示</option></select></Field><Field label="文本范围"><select value={scope} onChange={e=>setScope(e.target.value)}>{(stage==='before'?['goal','selection','world']:['prose']).map(s=><option key={s}>{s}</option>)}</select></Field></div><label className="check-field"><input type="checkbox" checked={edited} onChange={e=>setEdited(e.target.checked)}/>测试编辑触发（只执行 onEdit 规则）</label><Field label="测试输入"><textarea rows={6} value={input} onChange={e=>setInput(e.target.value)}/></Field><div className="inline-actions"><button disabled={busy} onClick={()=>void act(async()=>setResult(await api(base+'/regex-test',{input,rules:JSON.parse(rules),stage,scope,edited,config:draft})))}>运行规则测试</button><button disabled={busy} onClick={()=>void act(async()=>saved(await api(base+'/configurations',{name:name+' · 文本规则',config:{...draft,enabled:true,regex:JSON.parse(rules)},parentId:selected})))}>保存规则为配置新版本</button></div>{result&&<>{result.warnings?.map((w:string,n:number)=><p className="notice" key={n}>{w}</p>)}<TextDiff before={result.original} after={result.text}/>{result.trace.map((r:any,n:number)=><details key={n} open={!!r.error}><summary>{n+1}. {r.name} · {r.matches.length} 次 · {r.elapsedMs} ms</summary>{r.error&&<p role="alert" className="notice error">{r.error}</p>}<pre>{JSON.stringify(r.matches,null,2)}</pre></details>)}</>}</>}
    </>}</div></Modal>;
}

export function GenerationInspector({pid,taskId,requestId,chapterId,onClose}:{pid:string;taskId?:string;requestId?:string;chapterId?:string;onClose:()=>void}){
  const [list,setList]=useState<any[]>([]),[record,setRecord]=useState<any>(),[preview,setPreview]=useState<any>(),[goal,setGoal]=useState('继续当前故事'),[prompt,setPrompt]=useState('write'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
  const load=async()=>{const rows=await api(`/projects/${pid}/requests`);setList(taskId?rows.filter((r:any)=>r.taskId===taskId):rows);};
  useEffect(()=>{void act(async()=>{await load();if(requestId)setRecord(await api(`/projects/${pid}/requests/${requestId}`));});},[pid,taskId,requestId]);
  const compiled=record?.compiled??preview;return <Modal title="生成检查器" wide onClose={onClose}><p className="muted">实际请求保留最近 100 次，随本地作品访问权限保护；原始正文候选与变换另存于成果中。预览不调用模型、不改变变量或作品。</p>{error&&<div role="alert" className="notice error">{error}</div>}<div className="inspector-picker"><select aria-label="选择生成记录" value={record?.id??''} onChange={e=>void act(async()=>{setPreview(undefined);setRecord(e.target.value?await api(`/projects/${pid}/requests/${e.target.value}`):undefined);})}><option value="">选择实际生成记录</option>{list.map(r=><option key={r.id} value={r.id}>{r.role} · {r.stepKey.split(':').at(-1)} · {r.status} · {new Date(r.createdAt).toLocaleTimeString()}</option>)}</select><button disabled={busy} onClick={()=>void act(load)}>刷新记录</button></div><details><summary>编译预览（不产生模型调用）</summary><Field label="任务类型"><select value={prompt} onChange={e=>setPrompt(e.target.value)}>{[['write','Writer 正文'],['plan','Planner 章纲'],['review','Reviewer 审校'],['extract','Extractor 抽取'],['summarize','Summarizer 总结']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field><Field label="预览目标"><textarea value={goal} onChange={e=>setGoal(e.target.value)}/></Field><button disabled={busy||!goal.trim()} onClick={()=>void act(async()=>{setRecord(undefined);setPreview(await api(`/projects/${pid}/compile-preview`,{prompt,task:{kind:'write',goal,chapterId}}));})}>编译当前配置</button></details>
    {compiled&&<><div className="config-current"><strong>{record?'实际调用记录':'编译预览，尚未发送'}</strong><span>{compiled.role} · 约 {record?.observedEstimatedTokens??compiled.estimatedTokens} tokens（{record?.observedEstimatedTokens?'含工具 Schema 的请求估算':'编译文本估算'}）</span><small>配置 {compiled.config.hash.slice(0,12)} · 来源 {compiled.config.versions.map((v:any)=>v.name).join(' → ')||'原有文风'}</small></div>{record&&<><div className="usage-panel"><p><span>本地编译缓存</span><strong>{compiled.localCompilationCache}</strong></p><p><span>本地稳定块相同</span><strong>{record.localPrefixReuse===undefined?'UNKNOWN':String(record.localPrefixReuse)}</strong></p><p><span>服务端缓存读 / 写 tokens</span><strong>{record.usage?.cacheReadTokens??'UNKNOWN'} / {record.usage?.cacheWriteTokens??'UNKNOWN'}</strong></p><p><span>总输入 / 未缓存输入 / 输出</span><strong>{record.usage?.inputTokens??'UNKNOWN'} / {record.usage?.uncachedInputTokens??'UNKNOWN'} / {record.usage?.outputTokens??'UNKNOWN'}</strong></p><p><span>首 token / 总耗时</span><strong>{record.usage?.firstTokenMs??'UNKNOWN'} / {record.usage?.elapsedMs??'UNKNOWN'} ms</strong></p><small>三类缓存分别计量。DSH 输入字段表示未缓存输入；仅在有 cache 字段时计算总输入。不估算费用。</small></div>{record.error&&<p role="alert" className="notice error">{record.error.code}：{record.error.message}</p>}</>}
    {compiled.warnings.length>0&&<details open><summary>兼容与宏警告（{compiled.warnings.length}）</summary>{compiled.warnings.map((w:string,n:number)=><p key={n}>{w}</p>)}</details>}
    <div className="prompt-blocks">{compiled.blocks.map((b:any,n:number)=><details key={n}><summary><span className="badge">{b.layer}</span> {b.source} · {b.role} · {b.chars} 字符</summary><p>{b.purpose} · {b.trust} · {b.stability} · {b.position}</p><small>版本 {b.version} / 依赖 {b.dependencies.join('、')}</small><pre>{b.text}</pre></details>)}</div>
    <details><summary>宏、资料命中与省略、有效来源</summary><pre>{JSON.stringify({macros:compiled.macros,context:compiled.context,origins:compiled.config.origins},null,2)}</pre></details>{record&&<>{record.syntaxRepair&&<p className="notice">结构语法修复：移除末尾 {record.syntaxRepair.removedTrailingClosers} 个多余闭括号。原始响应保留，字段与证据仍须校验。</p>}<details><summary>最终可观察 DSH 请求与相邻 Diff</summary><p>观察点为 DSH llm.stream 参数；下游连接凭据与不可观察的 HTTP 头不记录。</p><pre>{JSON.stringify(record.observed??'测试提供方未提供最终请求',null,2)}</pre><pre>{JSON.stringify(record.diff??'没有可比较的相邻请求',null,2)}</pre></details><details><summary>原始响应 → 文本处理 → 正文候选</summary><TextDiff before={record.rawResponse??''} after={record.candidate??record.rawResponse??''}/></details></>}{[...compiled.transformations,...record?.transformations??[]].map((r:any,n:number)=><details key={n}><summary>变换 {r.stage}/{r.scope} · {r.name} · {r.elapsedMs} ms</summary><TextDiff before={r.before} after={r.after}/></details>)}</>}{!compiled&&!busy&&<p className="muted empty-line">从生成记录查看真实请求，或展开编译预览。</p>}</Modal>;
}
