import { useEffect,useState } from 'react';import { ArrowUpRight,ArrowRight,Check,ChevronDown,Clapperboard,FileText,Pause,Play,Square,RotateCcw,Sparkles,AlertCircle,Clock,Layers } from 'lucide-react';
import type { CreativeTask,StoryObject } from '../contracts.js';import { api,statusText } from './api.js';import { Field } from './Modal.js';
export function Director({onInspect,composerRequest=0,task,objects,chapter,health,initialGoal,onCreate,onControl,onArtifact,onView,onTakeover}:{onInspect?:(id?:string)=>void;composerRequest?:number;task:any;objects:StoryObject[];chapter?:StoryObject;health:any;initialGoal?:string;onCreate:(input:any)=>Promise<void>;onControl:(action:string)=>void;onArtifact:(id:string)=>void;onView:(id:string)=>void;onTakeover:(id:string)=>void}){
  const [scene,setScene]=useState(''),[viewpoint,setViewpoint]=useState('');
  const [composerOpen,setComposerOpen]=useState(!task);
  useEffect(()=>{setComposerOpen(!task);},[task?.id]);
  useEffect(()=>{if(composerRequest)setComposerOpen(true);},[composerRequest]);
  const [replanScope,setReplanScope]=useState('future');const [answer,setAnswer]=useState('');const [goal,setGoal]=useState(initialGoal??'');const [kind,setKind]=useState(objects.some(o=>o.kind==='character')?'write':objects.some(o=>o.kind==='chapter'&&o.body)?'extract':'bootstrap');const [provider,setProvider]=useState('dsh');const [reasoning,setReasoning]=useState('balanced');const [count,setCount]=useState(1);const [words,setWords]=useState(2000);const [auto,setAuto]=useState(true);const [constraints,setConstraints]=useState('');const [calls,setCalls]=useState(18);const [tokens,setTokens]=useState(48000);const [chars,setChars]=useState(18000);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{if(kind==='bootstrap'&&objects.some(o=>o.kind==='chapter'&&o.body))setKind(objects.some(o=>o.kind==='character')?'write':'extract');},[objects]);
  const submit=async()=>{setBusy(true);setError('');try{await onCreate({configuration:scene?{patch:{enabled:true,native:{scene}}}:undefined,perspective:viewpoint?{viewpointId:viewpoint,audience:'character'}:undefined,kind,goal:goal||chapter?.fields.goal||'沿着当前故事继续，保持人物状态和世界规则一致',provider,reasoning,count,targetWords:words,autoAccept:auto,constraints:constraints.split('\n').filter(Boolean),budget:{calls,outputTokens:tokens,contextChars:chars},...((['review','extract','summarize'].includes(kind)||kind==='replan'&&replanScope==='chapter')&&chapter?{chapterId:chapter.id}:kind==='write'&&chapter&&chapter.status!=='accepted'&&!chapter.locked?{chapterId:chapter.id}:{})});setGoal('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const active=task&&['QUEUED','RUNNING','PAUSE_REQUESTED'].includes(task.status);const selected=objects.find(o=>o.id===task?.checkpoint?.chapterId);const artifacts=task?.artifacts??[];const steps=task?.steps??[];
  return <div className="director-layout"><main className="director-main"><header className="director-heading"><div className="eyebrow"><Clapperboard size={14}/> DIRECTOR</div><h1>{task&&active?'故事正在向前。':'让故事，继续向前。'}</h1><p>说清想抵达的地方，导演会在约定范围内规划、创作与检查。</p></header>
    <details className="composer-fold" open={composerOpen} onToggle={e=>setComposerOpen(e.currentTarget.open)}><summary>委派新的创作目标</summary><div className="task-composer"><div className="composer-head"><Sparkles size={16}/><span>委派一个创作目标</span><select aria-label="导演任务类型" value={kind} onChange={e=>setKind(e.target.value)}>{[['write','创作章节'],['bootstrap','从灵感开书'],['review','审查并局部修复'],['replan','重规划未来章纲'],['extract','从正文提取资料'],['summarize','总结作品记忆'],['ideas','剧情推演']].map(([key,title])=><option key={key} value={key}>{title}</option>)}</select></div><textarea aria-label="创作目标" placeholder={kind==='bootstrap'?'例如：在一个以记忆支付灯火的港口，邮差收到一封寄给失踪母亲的信…':'例如：继续两章，让沈砚开始怀疑导师，但不要揭露身份。不修改前文，不新增核心角色。'} rows={4} value={goal} onChange={e=>setGoal(e.target.value)}/>
      <div className="composer-options"><label>章节数 <select aria-label="章节数" value={count} onChange={e=>setCount(Number(e.target.value))}>{[1,2,3].map(n=><option value={n} key={n}>{n} 章</option>)}</select></label><label>目标 <input aria-label="目标字数" type="number" min="300" max="8000" step="100" value={words} onChange={e=>setWords(Number(e.target.value))}/> 字 / 章</label><select aria-label="模型提供方" value={provider} onChange={e=>{setProvider(e.target.value);if(e.target.value==='demo')setWords(600);else if(words===600)setWords(2000);}}><option value="dsh">DSH 当前模型</option><option value="demo">演示提供方 · 非真实 AI</option></select></div>
      {kind==='replan'&&<Field label="规划作用范围"><select value={replanScope} onChange={e=>setReplanScope(e.target.value)}><option value="future">全部未锁定未来大纲</option>{chapter&&chapter.status==='planned'&&!chapter.locked&&!chapter.body&&<option value="chapter">仅当前章：{chapter.title}</option>}</select></Field>}<details className="task-boundaries"><summary>创作边界与预算 <ChevronDown size={14}/></summary><Field label="模型推理配置" hint="均衡优先使用模型支持的非推理模式，否则使用低推理档；保留预算用于正文与审校，不修改 DSH 配置。"><select value={reasoning} onChange={e=>setReasoning(e.target.value)}><option value="balanced">均衡创作（默认）</option><option value="configured">沿用 DSH 当前配置</option></select></Field><Field label="本次场景文风（临时覆盖）"><textarea rows={2} value={scene} onChange={e=>setScene(e.target.value)} placeholder="留空沿用作品配置；本次任务固定版本"/></Field><Field label="本次视角人物"><select value={viewpoint} onChange={e=>setViewpoint(e.target.value)}><option value="">沿用作品配置 / 作者视角</option>{objects.filter(o=>o.kind==='character').map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></Field><Field label="必须遵守（每行一条）"><textarea rows={3} value={constraints} onChange={e=>setConstraints(e.target.value)} placeholder="不揭露导师身份&#10;不新增核心角色"/></Field><div className="form-grid three"><Field label="最多模型调用"><input type="number" min="1" max="40" value={calls} onChange={e=>setCalls(Number(e.target.value))}/></Field><Field label="输出 token 上限"><input type="number" min="500" max="150000" value={tokens} onChange={e=>setTokens(Number(e.target.value))}/></Field><Field label="上下文字符上限"><input type="number" min="1000" max="48000" value={chars} onChange={e=>setChars(Number(e.target.value))}/></Field></div></details>
      <div className="composer-bottom"><label className="check-field"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>自动接受通过检查的成果</label><button className="solid" disabled={busy||active} onClick={()=>void submit()}>{busy?'正在建立任务…':'开始执行'}<ArrowRight size={15}/></button></div>
      {provider==='demo'&&<p className="composer-note">演示使用原创固定样本，验证工作流与状态；不代表真实模型创作。</p>}{provider==='dsh'&&!health?.dsh?.available&&<p className="composer-note warning">尚未连接 DSH 模型。仍可写作、导入或选择演示；真实调用会明确报错。</p>}{error&&<div className="notice error" role="alert">{error}</div>}
    </div></details>
    {task?<section className="task-work"><div className="task-heading"><div><span className={`status-dot ${task.status}`}/><span className="badge">{statusText[task.status]}</span><small>{new Date(task.createdAt).toLocaleString('zh-CN')}</small></div><div className="inline-actions">{active?<><button onClick={()=>onControl('pause')} disabled={task.status==='PAUSE_REQUESTED'}><Pause size={14}/>暂停</button><button onClick={()=>onControl('cancel')}><Square size={12}/>取消</button></>:['PAUSED','FAILED','NEEDS_INPUT'].includes(task.status)?<><button onClick={()=>onControl('resume')}><Play size={14}/>恢复</button><button onClick={()=>onControl('redelegate')} title="保留已完成章节与用量，根据作品新版本重建上下文"><RotateCcw size={14}/>重新委派</button><button onClick={()=>onControl('cancel')}>取消</button></>:null}</div></div>
      <h2 className="task-objective">{task.contract.brief?.objective??task.goal}</h2>{(task.goal.length>180||task.contract.brief)&&<details><summary>查看完整委派</summary><p className="original-goal">{task.goal}</p></details>}{task.error&&<div className={`notice ${task.status==='FAILED'?'error':''}`}><AlertCircle size={17}/><div><strong>{task.error.message}</strong><small>{task.error.code}</small></div></div>}
      {selected&&<div className="current-object"><div><FileText size={17}/><span>当前对象 <strong>{selected.title}</strong></span></div><div><button onClick={()=>onView(selected.id)}>查看 <ArrowUpRight size={13}/></button><button onClick={()=>onTakeover(selected.id)}>接管编辑</button></div></div>}
      <div className="run-steps">{steps.map((s:any,n:number)=><div className={`run-step ${s.status}`} key={`${s.key}:${s.inputHash}`}><span className="step-marker">{s.status==='COMPLETED'?<Check size={13}/>:s.status==='RUNNING'?<span className="tiny-spinner"/>:n+1}</span><div><strong>{s.name}</strong>{s.requestIds?.length>0&&<button className="step-inspect" onClick={()=>onInspect?.(s.requestIds.at(-1))}>检查生成请求</button>}<p>{s.status==='COMPLETED'?`已保存 · 来源修订 ${s.inputRevision}`:s.error??'正在执行实际模型调用'}</p>{s.partial&&s.status!=='COMPLETED'&&<details><summary>已保留的生成片段</summary><pre>{s.partial}</pre></details>}</div><small>{s.usage?`${s.usage.outputTokens.toLocaleString()} tokens`:s.attempts>1?`尝试 ${s.attempts}/3`:''}</small></div>)}</div>
      <div className="artifacts-heading"><h3>交付成果</h3><span>{artifacts.length} 项已落盘</span></div>{artifacts.length?<div className="artifact-list">{artifacts.map((a:any)=><button className="artifact-card" key={a.id} onClick={()=>onArtifact(a.id)}><div className="artifact-icon"><FileText size={20}/></div><div><strong>{objects.find(o=>o.id===a.chapterId)?.title??({setup:'故事方向与基础资料',ideas:'剧情候选',replan:'未来章纲变更',extraction:'待确认作品资料',memory:'有证据的章节记忆',edit:'选区修改提案'} as any)[a.type]??'创作成果'}</strong><p>{statusText[a.status]}{a.type==='chapter'?(a.data.review?' · 已审校':' · 工作稿，尚未审校'):''} {a.data?.content?`· ${a.data.content.length.toLocaleString()} 字符`:''}{a.data?.late?' · 旧调用晚到':''}</p></div><ArrowUpRight size={16}/></button>)}</div>:<p className="muted empty-line">成果落盘后会出现在这里。</p>}
      <details className="event-log"><summary>实际执行事件 <span>{task.events?.length??0}</span></summary>{task.events?.map((e:any)=><div key={e.id}><time>{new Date(e.at).toLocaleTimeString('zh-CN',{hour12:false})}</time><span>{e.message}</span></div>)}</details>
    </section>:<div className="director-empty"><div className="quiet-line"/><span>从一个有边界的目标开始</span><div className="workflow-preview"><span>规划</span><ChevronDown size={13}/><span>起草</span><ChevronDown size={13}/><span>审校</span><ChevronDown size={13}/><span>交付与状态更新</span></div><p>你随时可以查看成果；只有「接管」会暂停相关 AI 写入。</p></div>}
  </main><aside className="director-inspector"><div className="panel-label"><Layers size={16}/>任务约定</div>{task?<><h3>共同守住的边界</h3><p className="muted">固定配置：{task.configSnapshot?.versions.map((v:any)=>v.name).join(' → ')||'原有作品文风'} · {task.configSnapshot?.hash.slice(0,8)}</p>{task.error?.code==='TASK_CLARIFICATION'&&<div className="note-card"><p>{task.error.message}</p><textarea aria-label="补充任务约定" value={answer} onChange={e=>setAnswer(e.target.value)}/><button disabled={busy||!answer.trim()} onClick={()=>{setBusy(true);void api(`/projects/${task.projectId}/tasks/${task.id}/clarify`,{answer}).then(()=>setAnswer('')).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>补充后重新委派</button></div>}{task.contract.brief&&<div className="note-card"><h4>执行安排</h4><details><summary>展开步骤与默认假设</summary><p>{task.contract.brief.approach}</p>{task.contract.brief.assumptions.map((x:string)=><p className="muted" key={x}>默认：{x}</p>)}</details>{task.contract.brief.constraints.map((x:string)=><p key={x}>约束：{x}</p>)}</div>}<p className="contract-scope">{task.contract.scope}</p><dl className="contract-list"><div><dt>推理配置</dt><dd>{task.reasoning==="configured"?"DSH 当前配置":"均衡创作"}</dd></div><div><dt>输入版本</dt><dd>修订 {task.inputRevision} → 当前绑定 {task.expectedRevision}</dd></div><div><dt>允许自主决定</dt><dd>{task.contract.permitted.join('；')}</dd></div><div><dt>受保护的对象</dt><dd>{task.contract.lockedIds.length?task.contract.lockedIds.map((id:string)=>objects.find(o=>o.id===id)?.title??id).join('、'):'遵守作品约束，不改范围外已接受正文'}</dd></div><div><dt>交付物</dt><dd>{task.contract.deliverables.join('、')}</dd></div><div><dt>停止条件</dt><dd>{task.contract.stop.join('、')}</dd></div></dl>{task.constraints.length>0&&<div className="note-card"><h4>本次特别约束</h4>{task.constraints.map((c:string)=><p key={c}>{c}</p>)}</div>}<div className="usage-panel"><h4>用量与预算</h4><p><span>模型调用</span><strong>{task.usage.calls} / {task.budget.calls}</strong></p><p><span>输出 tokens</span><strong>{task.usage.outputTokens.toLocaleString()} / {task.budget.outputTokens.toLocaleString()}</strong></p><p><span>已接受章节</span><strong>{task.completedChapters} / {task.count}</strong></p><small>{task.usage.estimated?'含演示估算或未结算调用的保守预留':'提供方实际用量'} · 不估算金额</small></div><p className="model-caption">{task.provider==='demo'?'演示提供方 · 非真实 AI':health?.dsh?.name}</p></>:<><div className="contract-illustration"><span>01</span><div/><span>02</span><div/><span>03</span></div><h3>一份清楚的委派</h3><p>给出目标、作用范围与禁区。普通细节交给导演决定，关键边界由运行器保护。</p><div className="note-card"><h4>试着这样说</h4><p>“继续两章，让两个人的信任出现裂缝，但不要揭露信件的真正来源。”</p></div><small>默认最多 3 章，每步最多重试 2 次，每章最多局部修复 2 轮。</small></>}</aside></div>;
}
