import { useEffect,useRef,useState } from 'react';import { createRoot } from 'react-dom/client';
import { BookOpen,BookMarked,Clapperboard,PenLine,Users,Globe,Network,GitBranch,Clock,Lightbulb,Bookmark,CheckCheck,Plus,ChevronDown,ChevronRight,ArrowUpRight,ArrowRight,Settings,Sun,Moon,FolderOpen,PanelLeft,Upload,Download,Archive,Search,Sparkles,FileText,Lock,ArrowLeft,Feather } from 'lucide-react';
import { Editor,type EditorHandle } from './Editor.js';import { ObjectForm,Collection,kindLabels } from './Objects.js';import { Director } from './Director.js';import { Modal,Field } from './Modal.js';import { ArtifactModal,ContextTrace } from './Artifacts.js';import { api,downloadProject,inputOf,statusText } from './api.js';import { countWords,orderedChapters,type Project,type StoryObject,type Kind } from '../contracts.js';import './style.css';
import { WorkbenchRail } from './WorkbenchRail.js';
import { DirectorTaskSidebar } from './DirectorTaskSidebar.js';
import { CreativeConfig,GenerationInspector } from './CreativeConfig.js';
import { SourceLibrary,InheritanceView } from './SourceLibrary.js';
import { MemoryStudio,LorebookImport } from './MemoryStudio.js';
import { ProjectSessionCoordinator,isAbortError } from './project-session.js';

function App(){
  const [evidenceRange,setEvidenceRange]=useState<{chapterId:string;start:number;end:number}>();const [effectiveStyle,setEffectiveStyle]=useState('原有作品文风');const [composerRequest,setComposerRequest]=useState(0);const [projects,setProjects]=useState<Project[]>([]);const [health,setHealth]=useState<any>();const [snap,setSnap]=useState<any>();const [chapter,setChapter]=useState<StoryObject>();const [mode,setMode]=useState<'writer'|'director'>('writer');const [surface,setSurface]=useState<Kind|'workspace'>('workspace');const [selectedTask,setSelectedTask]=useState<any>();const [modal,setModal]=useState<any>();const [error,setError]=useState('');const [toast,setToast]=useState('');const [focus,setFocus]=useState(false);const [sidebar,setSidebar]=useState(false);const [inspector,setInspector]=useState(()=>window.matchMedia('(min-width: 1121px)').matches);const [theme,setTheme]=useState(localStorage.getItem('novel-theme')??'light');const [showArchived,setShowArchived]=useState(false);const [loading,setLoading]=useState(true);const [selection,setSelection]=useState(false);const [assist,setAssist]=useState('');const [assistBusy,setAssistBusy]=useState(false);const [assistProvider,setAssistProvider]=useState('dsh');
  const editor=useRef<EditorHandle>(null);const sessions=useRef(new ProjectSessionCoordinator());const current=useRef({snap,chapter,selectedTask});current.current={snap,chapter,selectedTask};const pid=snap?.project.id as string|undefined;const objects:StoryObject[]=snap?.objects??[];const chapters=orderedChapters(objects);const tasks:any[]=snap?.tasks??[];const active=tasks.find(t=>['QUEUED','RUNNING','PAUSE_REQUESTED'].includes(t.status));
  useEffect(()=>{if(evidenceRange&&chapter?.id===evidenceRange.chapterId&&mode==='writer'){const frame=requestAnimationFrame(()=>{editor.current?.locate(evidenceRange.start,evidenceRange.end);setEvidenceRange(undefined);});return()=>cancelAnimationFrame(frame);}},[evidenceRange,chapter?.id,mode]);
  const clearProjectView=()=>{setSnap(undefined);setChapter(undefined);setSelectedTask(undefined);setModal(undefined);setEvidenceRange(undefined);setEffectiveStyle('原有作品文风');setSurface('workspace');setSidebar(false);setFocus(false);};
  const loadStyle=async()=>{const p=current.current.snap?.project.id;if(!p)return;const ticket=sessions.current.begin(p,'configuration');try{const c=await api(`/projects/${p}/configurations`,undefined,'GET',ticket.signal);sessions.current.commit(ticket,()=>setEffectiveStyle(c.effective.config.enabled?c.effective.versions.at(-1)?.name??'原生组合':'原有作品文风'));}catch(e){if(!isAbortError(e))throw e;}};
  useEffect(()=>{void loadStyle().catch(e=>setError(e.message));},[pid]);
  async function refresh(){const p=current.current.snap?.project.id;if(!p)return false;const ticket=sessions.current.begin(p,'refresh');try{const data=await api(`/projects/${p}`,undefined,'GET',ticket.signal);return sessions.current.commit(ticket,()=>{setSnap(data);const cid=current.current.chapter?.id;if(cid){const found=data.objects.find((o:StoryObject)=>o.id===cid);if(found)setChapter(found);}else setChapter(data.objects.find((o:StoryObject)=>o.kind==='chapter'&&o.status==='accepted')??data.objects.find((o:StoryObject)=>o.kind==='chapter'));});}catch(e){if(isAbortError(e))return false;throw e;}}
  async function act(fn:()=>Promise<any>){try{setError('');return await fn();}catch(e){if(isAbortError(e))return;setError((e as Error).message);}}
  async function flush(){return await editor.current?.flush()??true;}
  async function leaveProject(){if(!(await flush()))return false;const ticket=sessions.current.leave();clearProjectView();try{const list=await api<Project[]>('/projects',undefined,'GET',ticket.signal);sessions.current.commit(ticket,()=>setProjects(list));return true;}catch(e){if(isAbortError(e))return false;throw e;}}
  async function openProject(p:Project){if(!(await flush()))return false;const ticket=sessions.current.enter(p.id,'open');clearProjectView();try{const data=await api(`/projects/${p.id}`,undefined,'GET',ticket.signal);return sessions.current.commit(ticket,()=>{setSnap(data);const ch=orderedChapters(data.objects).find(c=>!c.fields.referenceOnly)??orderedChapters(data.objects)[0];setChapter(ch);setSurface('workspace');localStorage.setItem('novel-last-project',p.id);});}catch(e){if(isAbortError(e))return false;throw e;}}
  async function navigate(id:string,changeMode=true){const p=current.current.snap?.project.id;if(!p||!(await flush()))return false;const ticket=sessions.current.begin(p,'navigate');try{const o=await api<StoryObject>(`/projects/${p}/objects/${id}`,undefined,'GET',ticket.signal);return sessions.current.commit(ticket,()=>{if(o.kind==='chapter'){setChapter(o);setSurface('workspace');if(changeMode)setMode('writer');setSidebar(false);}else setModal({type:'object',object:o,kind:o.kind});});}catch(e){if(isAbortError(e))return false;throw e;}}
  async function selectTask(id:string){const p=current.current.snap?.project.id;if(!p)return false;const ticket=sessions.current.begin(p,'task-detail');try{const task=await api(`/projects/${p}/tasks/${id}`,undefined,'GET',ticket.signal);return sessions.current.commit(ticket,()=>{setSelectedTask(task);setSurface('workspace');setSidebar(false);});}catch(e){if(isAbortError(e))return false;throw e;}}
  async function controlTask(action:string){const p=current.current.snap?.project.id,taskId=current.current.selectedTask?.id;if(!p||!taskId)return;const ticket=sessions.current.begin(p,'task-control'),task=await api(`/projects/${p}/tasks/${taskId}/${action}`,{},'POST',ticket.signal);if(!sessions.current.commit(ticket,()=>setSelectedTask(task)))return;await refresh();}
  async function switchMode(next:'writer'|'director'){const p=current.current.snap?.project.id;if(!p||!(await flush()))return false;const ticket=sessions.current.begin(p,'mode');let task=selectedTask;if(next==='director'&&!task&&tasks.length){const latest=tasks.at(-1);try{task=await api(`/projects/${p}/tasks/${latest.id}`,undefined,'GET',ticket.signal);}catch(e){if(isAbortError(e))return false;throw e;}}return sessions.current.commit(ticket,()=>{if(task)setSelectedTask(task);setMode(next);setSurface('workspace');setFocus(false);setSidebar(false);});}
  async function beginDelegation(){if(await switchMode('director'))setComposerRequest(n=>n+1);}
  async function createTask(input:any){const p=current.current.snap?.project.id;if(!p||!(await flush()))throw new Error('请先保存正文或处理保存冲突');const ticket=sessions.current.begin(p,'create-task'),task=await api(`/projects/${p}/tasks`,input,'POST',ticket.signal);if(!sessions.current.commit(ticket,()=>{setSelectedTask(task);setMode('director');setSurface('workspace');}))return;await refresh();}
  async function showArtifact(id:string){const p=current.current.snap?.project.id;if(!p)return;const ticket=sessions.current.begin(p,'artifact');try{const a=await api(`/projects/${p}/artifacts/${id}`,undefined,'GET',ticket.signal),t=await api(`/projects/${p}/tasks/${a.taskId}`,undefined,'GET',ticket.signal);sessions.current.commit(ticket,()=>setModal({type:'artifact',artifact:a,task:t}));}catch(e){if(!isAbortError(e))throw e;}}
  async function showHistory(target:StoryObject){const p=current.current.snap?.project.id;if(!p)return;const ticket=sessions.current.begin(p,'history');try{const versions=await api(`/projects/${p}/objects/${target.id}/versions`,undefined,'GET',ticket.signal);sessions.current.commit(ticket,()=>setModal({type:'history',versions,chapter:target}));}catch(e){if(!isAbortError(e))throw e;}}
  async function showContext(){const p=current.current.snap?.project.id;if(!p)return;const target=current.current.chapter;const ticket=sessions.current.begin(p,'context');try{const context=await api(`/projects/${p}/context${target?'?chapterId='+target.id:''}`,undefined,'GET',ticket.signal);sessions.current.commit(ticket,()=>setModal({type:'context',context}));}catch(e){if(!isAbortError(e))throw e;}}
  async function showDisplay(){const p=current.current.snap?.project.id,target=current.current.chapter;if(!p||!target||!(await flush()))return;const ticket=sessions.current.begin(p,'display');try{const result=await api(`/projects/${p}/display`,{chapterId:target.id},'POST',ticket.signal);sessions.current.commit(ticket,()=>setModal({type:'display',result}));}catch(e){if(!isAbortError(e))throw e;}}
  async function takeover(id:string){const p=current.current.snap?.project.id;if(!p)return;const ticket=sessions.current.begin(p,'takeover'),c=await api<StoryObject>(`/projects/${p}/objects/${id}`,undefined,'GET',ticket.signal),result=await api<StoryObject>(`/projects/${p}/objects/${id}/takeover`,{revision:c.revision},'POST',ticket.signal);if(!sessions.current.commit(ticket,()=>{setChapter(result);setMode('writer');setSurface('workspace');setToast('已接管。旧 AI 结果不能覆盖您的编辑。');}))return;await refresh();}
  async function bodySaved(c:StoryObject){const ticket=sessions.current.begin(c.projectId,'body-save');if(!sessions.current.commit(ticket,()=>setChapter(c)))return;await act(refresh);}
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('novel-theme',theme);},[theme]);
  useEffect(()=>{const media=window.matchMedia('(min-width: 1121px)');const sync=(event:MediaQueryListEvent)=>setInspector(event.matches);media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync);},[]);
  useEffect(()=>{void (async()=>{try{const [ps,h]=await Promise.all([api<Project[]>('/projects'),api('/health')]);setProjects(ps);setHealth(h);const last=localStorage.getItem('novel-last-project');const p=ps.find(p=>p.id===last&&!p.archived);if(p)await openProject(p);}catch(e){setError((e as Error).message);}finally{setLoading(false);}})();},[]);
  useEffect(()=>{if(!pid)return;let stopped=false,busy=false;const poll=async()=>{if(stopped||busy)return;busy=true;const ticket=sessions.current.begin(pid,'poll');try{const status=await api(`/projects/${pid}/status`,undefined,'GET',ticket.signal);if(!sessions.current.current(ticket))return;const old=current.current.snap;if(status.project.revision!==old?.project.revision)await refresh();else sessions.current.commit(ticket,()=>setSnap((value:any)=>value?{...value,tasks:status.tasks}:value));const tid=current.current.selectedTask?.id??status.tasks.find((task:any)=>['QUEUED','RUNNING','NEEDS_INPUT'].includes(task.status))?.id;if(tid&&sessions.current.current(ticket)){const detail=sessions.current.begin(pid,'task-detail'),task=await api(`/projects/${pid}/tasks/${tid}`,undefined,'GET',detail.signal);sessions.current.commit(detail,()=>setSelectedTask(task));}}catch(e){if(!isAbortError(e)&&sessions.current.current(ticket))setError((e as Error).message);}finally{busy=false;}};const timer=setInterval(()=>void poll(),1200);return()=>{stopped=true;sessions.current.abort('poll');clearInterval(timer);};},[pid]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);},[toast]);
  const projectFields=(p:Project)=>({title:p.title,premise:p.premise,genre:p.genre,style:p.style,constraints:p.constraints,archived:p.archived});
  async function demo(){const p=await api<Project>('/projects',{title:'雾港来信 · 原创演示',premise:'一个港口邮差收到一封寄给失踪母亲的信。'});setProjects(await api('/projects'));if(!(await openProject(p)))return;const ticket=sessions.current.begin(p.id,'create-task'),task=await api(`/projects/${p.id}/tasks`,{kind:'bootstrap',goal:'根据原创演示建立雾港来信的基础资料',provider:'demo',targetWords:600,autoAccept:true});sessions.current.commit(ticket,()=>{setSelectedTask(task);setMode('director');});}
  async function selectionTask(action:string){const p=current.current.snap?.project.id,target=current.current.chapter;if(!p||!target||!(await flush()))return;setAssistBusy(true);const ticket=sessions.current.begin(p,'create-task');try{const range=editor.current!.selection(),task=await api(`/projects/${p}/tasks`,{kind:action==='剧情建议'?'ideas':'assist',goal:assist?action+'：'+assist:action,chapterId:target.id,...(action==='剧情建议'?{}:{range}),provider:assistProvider,targetWords:600,autoAccept:false},'POST',ticket.signal);if(!sessions.current.commit(ticket,()=>{setSelectedTask(task);setToast('伴写任务已提交，成果落盘后可预览。');}))return;await refresh();}catch(e){if(!isAbortError(e))setError((e as Error).message);}finally{setAssistBusy(false);}}
  const taskArtifacts=selectedTask?.artifacts??[];const assistantArtifacts=taskArtifacts.filter((a:any)=>['edit','ideas'].includes(a.type));
  return <div className={`app ${mode==='director'?'mode-director':'mode-writer'} ${focus?'focus-mode':''} ${sidebar?'sidebar-open':''} ${inspector?'inspector-open':'inspector-closed'}`}>
    <header className="app-header"><button className="mobile-nav icon-button" aria-label="展开导航" onClick={()=>setSidebar(!sidebar)}><PanelLeft size={19}/></button><button className="brand" aria-label="返回作品书架" onClick={()=>void act(leaveProject)}><span className="brand-symbol"><Feather size={20}/></span><span>Novel <strong>Studio</strong><small>DSH</small></span></button>{pid&&<div className="mode-switch" aria-label="创作模式"><button className={mode==='writer'?'active':''} onClick={()=>void switchMode('writer')}><PenLine size={15}/>写作模式</button><button className={mode==='director'?'active':''} onClick={()=>void switchMode('director')}><Clapperboard size={15}/>导演模式{active&&<span className="live-dot"/>}</button></div>}{pid&&<button className="header-project" title="编辑作品信息" onClick={()=>setModal({type:'project',project:snap.project})}><BookOpen size={15}/><span>{snap.project.title}</span><ChevronDown size={13}/></button>}<div className="header-actions">{pid&&<button className="icon-button inspector-toggle" aria-label={inspector?'收起辅助侧栏':'展开辅助侧栏'} aria-pressed={inspector} onClick={()=>setInspector(!inspector)}><Sparkles size={17}/></button>}<span className="local-mark"><span/>本地工作空间</span><button className="icon-button" aria-label={theme==='light'?'切换深色':'切换浅色'} onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={17}/>:<Sun size={17}/>}</button><button className="icon-button" aria-label="设置" onClick={()=>setModal({type:'settings'})}><Settings size={17}/></button></div></header>
    {error&&<div className="global-error" role="alert"><span>{error}</span><button onClick={()=>setError('')}>收起</button></div>}{toast&&<div className="toast" role="status">{toast}</div>}
    {loading?<div className="loading-page"><span className="tiny-spinner"/>正在打开工作空间…</div>:!pid?<main className="library"><div className="library-heading"><div className="eyebrow">YOUR STORIES, IN THE MAKING</div><h1>从一个念头，<br/>写到最后一页。</h1><p>构思世界，写下人物。亲自执笔，或把下一段旅程交给 AI。<br/>你的故事，始终在同一个创作空间里。</p><div className="onboarding-paths"><button onClick={()=>setModal({type:'sources'})}><GitBranch size={21}/><div><strong>从已有作品创作</strong><span>选择原作时间点，带走人物与世界</span></div><ArrowUpRight size={17}/></button><button onClick={()=>setModal({type:'project',path:'idea'})}><Lightbulb size={21}/><div><strong>我有一个灵感</strong><span>从一句话，找到故事的方向</span></div><ArrowUpRight size={17}/></button><button onClick={()=>setModal({type:'project',path:'import'})}><FolderOpen size={21}/><div><strong>我已经有小说</strong><span>导入正文，继续尚未完成的故事</span></div><ArrowUpRight size={17}/></button></div><button className="demo-link" onClick={()=>void act(demo)}>打开原创演示作品 <ArrowRight size={15}/><small>显式演示模式，可重新创建</small></button></div><div className="library-art" aria-hidden="true"><div className="book-spine"/><div className="paper-art"><span>创作札记 / 001</span><i>每一个世界<br/>都始于一行字。</i><div className="ink-lines"><b/><b/><b/><b/></div><div className="paper-seal">N</div></div><span className="art-caption">A PLACE FOR YOUR NEXT CHAPTER</span></div>
      <section className="book-library"><div className="section-inline"><h2>我的作品 <small>{projects.filter(p=>p.archived===showArchived).length}</small></h2><div><button onClick={()=>setModal({type:'sources'})}><BookOpen size={14}/>原作资料库</button><button onClick={()=>setShowArchived(!showArchived)}><Archive size={14}/>{showArchived?'返回书架':'已归档'}</button><button onClick={()=>setModal({type:'project',path:'idea'})}><Plus size={15}/>新建作品</button></div></div><div className="book-grid">{projects.filter(p=>p.archived===showArchived).map((p,n)=><button className="book-card" key={p.id} onClick={()=>void act(async()=>{if(p.archived){await api(`/projects/${p.id}`,{revision:p.revision,project:{...projectFields(p),archived:false}},'PATCH');setProjects(await api('/projects'));}await openProject({...p,archived:false});})}><div className={`book-cover tone-${n%3}`}><span>小说 / {p.genre||'未分类'}</span><h3>{p.title}</h3><BookOpen size={24} strokeWidth={1}/></div><div className="book-meta"><strong>{p.title}</strong><small>{p.archived?'点击恢复归档':`上次编辑 ${new Date(p.updatedAt).toLocaleDateString('zh-CN')}`}</small></div></button>)}</div>{!projects.length&&<p className="muted">这里会保存你正在创作的作品。关闭或重启应用后，它们仍然在。</p>}</section>
    </main>:<div className="workspace"><WorkbenchRail mode={mode} surface={surface} hasLineage={!!snap.project.lineage} inspectorOpen={inspector} onNavigate={next=>void act(async()=>{if(await flush()){setSurface(next);setSidebar(false);}})} onOpenTool={tool=>void act(async()=>{if(tool==='transfer'&&!(await flush()))return;setModal({type:tool});})} onToggleInspector={()=>setInspector(!inspector)} onBack={()=>void act(leaveProject)}/><aside className="sidebar">{mode==='director'&&<DirectorTaskSidebar projectTitle={snap.project.title} tasks={tasks} selectedTaskId={selectedTask?.id} onCreate={()=>void beginDelegation()} onSelect={task=>void act(()=>selectTask(task.id))}/>}<button className="project-select" onClick={()=>setModal({type:'project',project:snap.project})}><div className="small-cover"><BookMarked size={19}/></div><span><strong>{snap.project.title}</strong><small>{snap.project.genre||'长篇小说'} · 修订 {snap.project.revision}</small></span><ChevronDown size={15}/></button>
      <div className="nav-section"><div className="nav-label">{mode==='writer'?'文稿':'创作任务'}<button className="icon-button" aria-label={mode==='writer'?'添加章节':'新建任务'} onClick={()=>mode==='writer'?setModal({type:'object',kind:'chapter'}):void beginDelegation()}><Plus size={14}/></button></div>{mode==='writer'?<><button className={surface==='book'?'nav-item active':'nav-item'} onClick={()=>void act(async()=>{if(await flush())setSurface('book');})}><GitBranch size={16}/>故事大纲</button><div className="chapter-tree">{objects.filter(o=>o.kind==='volume').sort((a,b)=>a.order-b.order).map(v=><details key={v.id} open><summary><ChevronRight size={13}/><span>{v.title}</span><button aria-label={`编辑${v.title}`} onClick={e=>{e.preventDefault();setModal({type:'object',kind:'volume',object:v});}}>···</button></summary>{chapters.filter(c=>c.parentId===v.id).map(c=><button key={c.id} className={`chapter-nav ${chapter?.id===c.id&&surface==='workspace'?'active':''}`} onClick={()=>void act(()=>navigate(c.id))}><FileText size={14}/><span>{c.title}</span>{c.locked?<Lock size={11}/>:c.status==='accepted'?<span className="chapter-dot"/>:null}</button>)}</details>)}{chapters.filter(c=>!c.parentId).map(c=><button className={`chapter-nav ${chapter?.id===c.id?'active':''}`} key={c.id} onClick={()=>void act(()=>navigate(c.id))}><FileText size={14}/>{c.title}</button>)}</div></>:<div className="task-nav">{[...tasks].reverse().map(t=><button key={t.id} className={selectedTask?.id===t.id?'active':''} onClick={()=>void act(()=>selectTask(t.id))}><span className={`status-dot ${t.status}`}/><span><strong>{t.goal}</strong><small>{statusText[t.status]}</small></span></button>)}{!tasks.length&&<p>还没有任务。<br/>说出第一个创作目标。</p>}</div>}</div>
      <div className="nav-section materials"><div className="nav-label">故事资料</div>{[['character','人物档案',Users],['world','世界设定',Globe],['relationship','人物关系',Network],['event','时间线',Clock],['foreshadow','伏笔',Bookmark],['fact','事实账本',CheckCheck],['idea','灵感收件箱',Lightbulb]].map(([kind,label,Icon]:any)=><button className={`nav-item ${surface===kind?'active':''}`} key={kind} onClick={()=>void act(async()=>{if(await flush()){setSurface(kind);setSidebar(false);}})}><Icon size={16}/>{label}<small>{objects.filter(o=>o.kind===kind&&o.status!=='revoked'&&o.status!=='stale').length||''}</small></button>)}</div><div className="sidebar-footer">{snap.project.lineage&&<button onClick={()=>setModal({type:'inheritance'})}><GitBranch size={15}/>继承与改编</button>}<button onClick={()=>setModal({type:'sources'})}><BookOpen size={15}/>原作资料库</button><button onClick={()=>setModal({type:'memory'})}><BookMarked size={15}/>作品记忆</button><button onClick={()=>setModal({type:'creative-config'})}><Feather size={15}/>创作配置</button><button onClick={()=>setModal({type:'generation-inspector'})}><Search size={15}/>生成检查器</button><button onClick={()=>void act(async()=>{if(await flush())setModal({type:'transfer'});})}><Upload size={15}/>导入、导出与备份</button><button onClick={()=>void act(leaveProject)}><ArrowLeft size={15}/>返回书架</button></div>
    </aside><div className="workspace-main">
      {surface==='workspace'?<><div className={`writer-layout ${mode==='director'?'hidden':''}`}>{chapter?<Editor key={chapter.id} ref={editor} chapter={chapter} readOnly={chapter.locked||chapter.fields.control==='director'||!!active&&(active.chapterId===chapter.id||active.checkpoint?.chapterId===chapter.id)} focus={focus} onFocus={()=>setFocus(!focus)} onSaved={c=>void bodySaved(c)} onHistory={()=>void act(()=>showHistory(chapter))} onPlan={()=>setModal({type:'object',kind:'chapter',object:chapter})} onTakeover={()=>void act(()=>takeover(chapter.id))} onDelegate={()=>void beginDelegation()} onSelection={setSelection}/>:<div className="empty-workspace"><div className="eyebrow">FIRST CHAPTER</div><h1>每个故事，都有第一行。</h1><p>创建一个章节亲自写，或让导演从灵感开始准备作品。</p><div><button className="solid" onClick={()=>setModal({type:'object',kind:'chapter'})}><Plus size={16}/>新建章节</button><button onClick={()=>void switchMode('director')}>委派给导演 <ArrowRight size={15}/></button></div></div>}
      <aside className="assistant-panel"><div className="panel-label"><Sparkles size={16}/>伴写助手<span className="badge">作者主导</span></div><button className="style-caption" onClick={()=>setModal({type:'creative-config'})}>当前文风 · {effectiveStyle}</button><div className="assistant-intro"><h3>{selection?'让这一段更靠近你的想法。':'落笔的方向，由你决定。'}</h3><p>{selection?'AI 只处理当前选区，结果先预览再接受。':'选中一段文字来改写，或把光标放在需要续写的位置。'}</p></div><div className="assist-actions">{['续写','改写','扩写','压缩','对白优化','剧情建议'].map(action=><button disabled={!chapter||assistBusy||!!active} key={action} onClick={()=>void selectionTask(action)}>{action}</button>)}</div><textarea aria-label="伴写要求" rows={4} placeholder="补充要求，例如：保留犹豫的语气，让对白更简洁。" value={assist} onChange={e=>setAssist(e.target.value)}/><select aria-label="伴写模型" value={assistProvider} onChange={e=>setAssistProvider(e.target.value)}><option value="dsh">DSH 当前模型</option><option value="demo">演示提供方 · 非真实 AI</option></select><p className="model-caption">{assistProvider==='demo'?'固定样本，仅验证工作流':health?.dsh?.name??'模型状态读取中'}</p>
      {['assist','ideas'].includes(selectedTask?.kind)&&<div className="assistant-result"><strong>{statusText[selectedTask.status]}</strong>{selectedTask.error&&<p className="warning">{selectedTask.error.message}</p>}{assistantArtifacts.map((a:any)=><button className="artifact-card" key={a.id} onClick={()=>void act(()=>showArtifact(a.id))}><FileText size={16}/><span>预览修改 · {statusText[a.status]}</span><ArrowUpRight size={15}/></button>)}</div>}
      <div className="related-material"><h4>与你的故事有关</h4>{objects.filter(o=>o.kind==='character'&&o.status==='accepted').slice(0,5).map(c=><button key={c.id} onClick={()=>setModal({type:'object',kind:'character',object:c})}><span className="avatar">{c.title.slice(0,1)}</span><span><strong>{c.title}</strong><small>{String(c.fields.identity??'角色档案')}</small></span><ArrowUpRight size={13}/></button>)}</div><button className="context-link" disabled={!chapter} onClick={()=>void act(showDisplay)}>查看展示规则效果</button><button className="context-link" onClick={()=>void act(showContext)}>查看当前资料依据 <ArrowUpRight size={14}/></button><div className="assistant-bottom"><Clapperboard size={18}/><p>想让 AI 规划并连续完成任务？</p><button onClick={()=>void switchMode('director')}>切换到导演模式 <ArrowRight size={14}/></button></div></aside></div>
      <div className={mode==='writer'?'hidden':''}><Director onInspect={(id)=>setModal({type:'generation-inspector',requestId:id,taskId:selectedTask?.id})} key={pid} composerRequest={composerRequest} task={selectedTask} objects={objects} chapter={chapter} health={health} onCreate={createTask} onControl={action=>void act(()=>controlTask(action))} onArtifact={id=>void act(()=>showArtifact(id))} onView={id=>void act(()=>navigate(id))} onTakeover={id=>void act(()=>takeover(id))}/></div></>:<Collection onWorldImport={()=>setModal({type:'lorebook'})} key={surface} kind={surface} objects={objects} foreshadows={snap.foreshadows} onEdit={o=>setModal({type:'object',object:o,kind:o.kind})} onAdd={kind=>setModal({type:'object',kind})} onNavigate={id=>void act(()=>navigate(id))} onAdopt={o=>void act(async()=>{if(!(await flush()))return;const c=await api<StoryObject>(`/projects/${pid}/objects/${o.id}/adopt`,{revision:o.revision});await refresh();await navigate(c.id);setToast('已采用为未来章纲；尚未进入事实账本。');})} onInspire={()=>void act(()=>createTask({kind:'ideas',goal:'分析当前剧情的停滞原因，提出几种有差异的后续事件与冲突',provider:assistProvider,autoAccept:false}))}/>}
    </div></div>}
    {modal?.type==='sources'&&<SourceLibrary health={health} onClose={()=>setModal(undefined)} onOpen={async(p,mode)=>{if(!(await openProject(p)))return;setMode(mode);setProjects(await api('/projects'));setModal(undefined);}}/>}
    {modal?.type==='inheritance'&&pid&&<InheritanceView project={snap.project} objects={objects} onClose={()=>setModal(undefined)} onNavigate={id=>void act(()=>navigate(id))}/>}
    {modal?.type==='memory'&&pid&&<MemoryStudio pid={pid} objects={objects} onClose={()=>setModal(undefined)} onCreate={createTask} onNavigate={(id,start,end)=>void act(async()=>{if(await navigate(id)){if(start!==undefined)setEvidenceRange({chapterId:id,start,end:end??start});}})}/>}
    {modal?.type==='lorebook'&&pid&&<LorebookImport pid={pid} onClose={()=>setModal(undefined)} onDone={()=>void act(refresh)}/>}
    {modal?.type==='creative-config'&&pid&&<CreativeConfig pid={pid} objects={objects} onClose={()=>setModal(undefined)} onDone={()=>void loadStyle()}/>}
    {modal?.type==='generation-inspector'&&pid&&<GenerationInspector pid={pid} taskId={modal.taskId} requestId={modal.requestId} chapterId={chapter?.id} onClose={()=>setModal(undefined)}/>}
    {modal?.type==='display'&&<Modal title="仅展示文本 · 原文保持不变" wide onClose={()=>setModal(undefined)}><p className="muted">以下规则仅用于这次显示，不写入正文或事实。</p>{modal.result.warnings?.map((w:string,n:number)=><p className="notice" key={n}>{w}</p>)}{modal.result.trace.map((r:any,n:number)=><p key={n} className={r.error?"notice error":"muted"} role={r.error?"alert":undefined}>{r.name} · {r.error??`${r.matches.length} 次匹配 · ${r.elapsedMs} ms`}</p>)}<pre>{modal.result.text}</pre></Modal>}
    {modal?.type==='project'&&<ProjectForm project={modal.project} importPath={modal.path==='import'} onClose={()=>setModal(undefined)} onSave={async data=>{if(modal.project){if(!(await flush()))throw new Error('请先处理正文保存状态');const latest=await api(`/projects/${pid}`);if(JSON.stringify(projectFields(latest.project))!==JSON.stringify(projectFields(modal.project)))throw new Error('作品设置已变化，请关闭后重新打开设置');await api(`/projects/${pid}`,{revision:latest.project.revision,project:data},'PATCH');await refresh();}else{const p=await api<Project>('/projects',data);if(!(await openProject(p)))return;setProjects(await api('/projects'));if(modal.path==='import'){setModal({type:'transfer',projectId:p.id,revision:p.revision});return;}setMode('director');}setModal(undefined);}} onArchive={modal.project?()=>void act(async()=>{if(!(await flush()))return;const latest=await api(`/projects/${pid}`);await api(`/projects/${pid}`,{revision:latest.project.revision,project:{...projectFields(latest.project),archived:true}},'PATCH');await leaveProject();}):undefined}/>}
    {modal?.type==='object'&&<ObjectForm object={modal.object} kind={modal.kind} objects={objects} onClose={()=>setModal(undefined)} onSave={async input=>{if(!(await flush()))throw new Error('请先处理正文保存状态');const latest=await api(`/projects/${pid}`);if(modal.object)await api(`/projects/${pid}/objects/${modal.object.id}`,{revision:modal.object.revision,object:input},'PATCH');else{const o=await api<StoryObject>(`/projects/${pid}/objects`,{revision:latest.project.revision,object:input});if(o.kind==='chapter'){setChapter(o);setSurface('workspace');}}await refresh();setModal(undefined);}}/>}
    {modal?.type==='artifact'&&<ArtifactModal onInspect={(requestId)=>setModal({type:'generation-inspector',requestId,taskId:modal.task?.id})} artifact={modal.artifact} task={modal.task} onCreate={createTask} objects={objects} onClose={()=>setModal(undefined)} onChanged={()=>void act(refresh)} onNavigate={id=>void act(()=>navigate(id))} onEdit={o=>setModal({type:'object',object:o,kind:o.kind})}/>}
    {modal?.type==='context'&&<Modal title="Context Trace · 当前资料依据" wide onClose={()=>setModal(undefined)}><ContextTrace context={modal.context}/></Modal>}
    {modal?.type==='history'&&<Modal title="正文版本与恢复" wide onClose={()=>setModal(undefined)}><p className="notice">恢复会同时处理关联事实、状态与下游任务。不会只换回编辑器文字。</p>{!modal.versions.length?<p>本章保存或接受正文后，会出现可恢复版本。</p>:modal.versions.map((v:any)=><details className="version-row" key={v.id}><summary>修订 {v.chapterRevision} · {new Date(v.createdAt).toLocaleString('zh-CN')}<span>{v.actor.startsWith('auto:')?'任务自动接受':'作者保存'} · {countWords(v.content)} 字</span></summary><pre>{v.content}</pre><button className="solid" onClick={()=>void act(async()=>{if(!(await flush()))return;const current=await api<StoryObject>(`/projects/${pid}/objects/${modal.chapter.id}`);const c=await api(`/projects/${pid}/objects/${current.id}/rollback`,{revision:current.revision,versionId:v.id});setChapter(c);await refresh();setModal(undefined);setToast('已恢复正文版本，并撤销失效的派生状态。');})}>恢复此版本</button></details>)}</Modal>}
    {modal?.type==='transfer'&&<Transfer project={snap?.project} onClose={()=>setModal(undefined)} onDone={()=>void act(refresh)}/>}
    {modal?.type==='settings'&&<Modal title="工作空间设置" onClose={()=>setModal(undefined)}><div className="note-card"><h3>模型连接</h3><p>{health?.dsh?.name}</p><p>{health?.dsh?.detail}</p><a className="button-link" href="/" target="_blank" rel="noreferrer">打开 DSH 配置 <ArrowUpRight size={14}/></a><p className="muted">独立模式通过 npm start 启动，支持离线写作与显式演示。真实 AI 请使用 DSH 插件启动路径，复用 DSH 已配置模型。凭据不会进入本项目、浏览器或备份。</p></div><div className="note-card"><h3>显示与保存</h3><p>当前主题：{theme==='dark'?'深色':'浅色'}。正文停顿 650 ms 后自动保存；网络错误或版本冲突会明确提示，并保留本地编辑。</p><button onClick={()=>setTheme(theme==='dark'?'light':'dark')}>切换主题</button></div><p className="muted">Novel Studio 0.3.0 · 本机数据 · SQLite 格式 v3</p></Modal>}
  </div>;
}

function ProjectForm({project,importPath,onClose,onSave,onArchive}:{project?:Project;importPath:boolean;onClose:()=>void;onSave:(data:any)=>Promise<void>;onArchive?:()=>void}){
  const [title,setTitle]=useState(project?.title??'');const [premise,setPremise]=useState(project?.premise??'');const [genre,setGenre]=useState(project?.genre??'');const [style,setStyle]=useState(project?.style??'克制、具体，以行动与对白推动故事。');const [constraints,setConstraints]=useState(project?.constraints.join('\n')??'');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  return <Modal title={project?'作品设置':importPath?'把故事带进来':'一个新故事'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();setBusy(true);void onSave({title,premise,genre,style,constraints:constraints.split('\n').filter(Boolean),archived:project?.archived??false}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>{error&&<p className="notice error">{error}</p>}<Field label="作品名称"><input autoFocus required placeholder="给这个故事一个暂定的名字" value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label={importPath?'已有故事简介（可留空）':'一句灵感 / 故事前提'}><textarea rows={4} placeholder="一座以记忆支付灯火的城，一个收到无地址来信的邮差…" value={premise} onChange={e=>setPremise(e.target.value)}/></Field><Field label="题材"><input value={genre} placeholder="悬疑、幻想、现实…" onChange={e=>setGenre(e.target.value)}/></Field><details open={!!project}><summary>风格与故事承诺</summary><Field label="写作风格"><textarea rows={3} value={style} onChange={e=>setStyle(e.target.value)}/></Field><Field label="不可破坏的约束（每行一条）"><textarea rows={4} value={constraints} onChange={e=>setConstraints(e.target.value)}/></Field></details><div className="form-footer">{onArchive&&<button type="button" onClick={onArchive}><Archive size={14}/>归档作品</button>}<button type="submit" className="solid" disabled={busy}>{busy?'保存中…':project?'保存设置':importPath?'创建并导入':'开始这个故事'}<ArrowRight size={15}/></button></div></form></Modal>;
}
function Transfer({project,onClose,onDone}:{project:Project;onClose:()=>void;onDone:()=>void}){
  const [message,setMessage]=useState('');const [raw,setRaw]=useState('');const [name,setName]=useState('');const [parts,setParts]=useState<any[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [format,setFormat]=useState('utf-8');
  const perform=async(fn:()=>Promise<any>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <Modal title="导入、导出与备份" onClose={onClose} wide>{error&&<p className="notice error">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}<div className="transfer-grid"><section><h3><Upload size={18}/>导入已有小说</h3><p>原文会单独保存。先预览拆分，再导入章节；资料提取由有预算的任务分章执行。</p><div className="inline-actions"><select aria-label="文件编码" value={format} onChange={e=>setFormat(e.target.value)}><option value="utf-8">UTF-8</option><option value="gb18030">GB18030</option></select><input type="file" accept=".txt,.md,.markdown" aria-label="选择小说文件" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void perform(async()=>{const text=new TextDecoder(format,{ignoreBOM:true}).decode(await file.arrayBuffer());setRaw(text);setName(file.name);setParts(await api(`/projects/${project.id}/import-preview`,{raw:text}));});}}/></div>{parts.length>0&&<><p>{name} · {raw.length.toLocaleString()} 字符 · 拆分为 {parts.length} 章</p><div className="import-preview">{parts.map((p,n)=><details key={n}><summary>{p.title} · {countWords(p.body)} 字</summary><Field label="章节名称"><input value={p.title} onChange={e=>setParts(parts.map((x,i)=>i===n?{...x,title:e.target.value}:x))}/></Field><textarea aria-label={`调整第${n+1}章拆分内容`} rows={6} value={p.body} onChange={e=>setParts(parts.map((x,i)=>i===n?{...x,body:e.target.value}:x))}/>{n>0&&<button onClick={()=>{const list=[...parts];list[n-1]={...list[n-1],body:list[n-1].body+'\n'+list[n].title+'\n'+list[n].body};list.splice(n,1);setParts(list);}}>合并到上一章</button>}</details>)}</div><button className="solid" disabled={busy} onClick={()=>void perform(async()=>{const current=await api(`/projects/${project.id}`);await api(`/projects/${project.id}/imports`,{revision:current.project.revision,raw,name,parts:parts.map(({title,body})=>({title,body}))});onDone();onClose();})}>确认拆分并导入</button></>}</section><section><h3><Download size={18}/>带走你的作品</h3><p>TXT / Markdown 默认只导出本书新增或改编正文，并保留来源说明。私人完整备份含锁定的继承前文、证据、设定和版本；不会附带资料库中未继承的后文。</p><div className="export-buttons">{['txt','md'].map(format=><button key={format} disabled={busy} onClick={()=>void perform(async()=>{downloadProject(project.id,format);})}><FileText size={17}/>导出 {format.toUpperCase()}</button>)}<button disabled={busy} onClick={()=>void perform(async()=>downloadProject(project.id,'backup'))}><Archive size={17}/>私人备份（含已继承原文）</button></div><Field label="恢复项目备份" hint="校验完整性后创建独立副本，不覆盖当前作品。"><input type="file" aria-label="恢复备份文件" accept=".json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void perform(async()=>{await api('/backups/restore',JSON.parse(await file.text()));onDone();setMessage('备份已恢复为独立副本，请返回书架打开。');});}}/></Field></section></div></Modal>;
}
createRoot(document.getElementById('root')!).render(<App/>);
