import { useEffect,useState,type FormEvent } from 'react';import { ArrowUpRight,BookOpen,GitBranch,Plus,Search,Lock,Network,ChevronRight,MapPin } from 'lucide-react';
import { Modal,Field } from './Modal.js';import { api,inputOf,statusText } from './api.js';import type { Kind,StoryObject } from '../contracts.js';
export const kindLabels:Record<Kind,string>={book:'全书',volume:'分卷',chapter:'章节',character:'角色',world:'世界',relationship:'关系',fact:'事实',event:'时间线',foreshadow:'伏笔',idea:'灵感'};
const definitions:Record<string,[string,string][]>={
  book:[['goal','全书目标'],['conflict','核心冲突'],['promise','故事承诺']],volume:[['goal','本卷目标'],['conflict','核心冲突'],['progression','推进内容']],
  chapter:[['goal','本章目标'],['conflict','核心冲突'],['participants','参与角色（姓名或 ID，以逗号分隔）'],['events','主要事件'],['change','人物变化'],['reveal','信息揭示'],['foreshadow','伏笔推进'],['ending','结尾落点'],['targetWords','目标字数'],['constraints','不可破坏的约束']],
  character:[['aliases','别名（逗号分隔）'],['group','角色分组'],['identity','身份'],['desire','核心欲望'],['fear','恐惧'],['boundaries','性格边界'],['weakness','弱点'],['voice','说话方式'],['address','称呼习惯'],['emotion','情绪表达'],['background','背景'],['arc','成长弧'],['location','当前位置（基础设定）'],['health','身体状态'],['goal','当前目标'],['abilities','能力'],['inventory','持有物'],['known','已知信息']],
  world:[['type','实体类型'],['rule','规则与限制'],['properties','自定义属性'],['relations','关联实体说明']],
  relationship:[['type','关系类型'],['state','关系状态'],['perspectiveFrom','起点角色的认知'],['perspectiveTo','终点角色的认知']],
  fact:[['property','属性（例如 holder、location）'],['value','事实或状态值'],['effectiveTime','生效时间 / 章节范围']],
  event:[['storyTime','故事内时间（可相对或未知）'],['chapterOrder','呈现章节序号'],['participants','关联角色与事件']],
  foreshadow:[['plantChapter','埋设章节'],['recoveryRange','计划回收范围'],['state','规划状态'],['participants','关联人物与事件']],
  idea:[['type','灵感类型'],['tradeoff','取舍 / 风险']]
};
export function ObjectForm({object,kind,objects,onClose,onSave}:{object?:StoryObject;kind:Kind;objects:StoryObject[];onClose:()=>void;onSave:(input:any)=>Promise<void>}){
  const [value,setValue]=useState<any>(object?inputOf(object):{kind,title:'',body:'',parentId:null,order:objects.filter(o=>o.kind===kind).length+1,status:['character','world','relationship','fact'].includes(kind)?'accepted':kind==='idea'?'candidate':'planned',locked:false,tags:[],fields:{}});
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [tag,setTag]=useState<string>(value.tags.join('，'));const [quote,setQuote]=useState(object?.source?.quote??'');
  const [history,setHistory]=useState<any>();
  useEffect(()=>{if(object)void api(`/projects/${object.projectId}/objects/${object.id}/history`).then(setHistory).catch(e=>setError(e.message));},[object?.id]);
  const parents=objects.filter(o=>o.id!==object?.id&&(kind==='chapter'?o.kind==='volume':kind==='volume'?o.kind==='book':o.kind===kind));
  const update=(field:string,data:any)=>setValue((v:any)=>({...v,[field]:data}));const field=(key:string,data:any)=>setValue((v:any)=>({...v,fields:{...v.fields,[key]:data}}));
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const data={...value,tags:tag.split(/[,，]/).map(x=>x.trim()).filter(Boolean)};if(!object?.source||quote!==object.source.quote)data.source={...object?.source,type:'user',quote,inference:false,modality:'objective'};if(object?.status==='candidate'&&data.status==='accepted')data.source={...data.source,type:'user',inference:false,modality:'objective',policy:'author-confirmed'};await onSave(data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal title={`${object?'编辑':'添加'}${kindLabels[kind]}`} onClose={onClose} wide><form onSubmit={submit}>
    {error&&<div className="notice error">{error}</div>}{value.locked&&<div className="notice">此对象已锁定。先取消锁定并保存，再修改内容。</div>}
    <div className="form-grid"><Field label="名称"><input required value={value.title} onChange={e=>update('title',e.target.value)}/></Field><Field label="内容状态" hint={kind==='chapter'?'正文状态随版本提交更新':''}><select disabled={kind==='chapter'} value={value.status} onChange={e=>update('status',e.target.value)}>{['candidate','planned','draft','accepted','revoked','stale'].map(s=><option value={s} key={s}>{statusText[s]}</option>)}</select></Field>
      {!['relationship','fact','event','idea','foreshadow','book'].includes(kind)&&<Field label="上级节点"><select value={value.parentId??''} onChange={e=>update('parentId',e.target.value||null)}><option value="">根节点</option>{parents.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></Field>}
      <Field label="排序"><input type="number" value={value.order} onChange={e=>update('order',Number(e.target.value))}/></Field>
    </div>
    {kind!=='chapter'&&<Field label={kind==='idea'?'记下这个想法':'描述 / 设定'}><textarea rows={4} value={value.body} onChange={e=>update('body',e.target.value)}/></Field>}
    {kind==='relationship'&&<div className="form-grid">{[['fromId','关系起点'],['toId','关系终点']].map(([key,label])=><Field key={key} label={label}><select required value={value.fields[key]??''} onChange={e=>field(key,e.target.value)}><option value="">选择角色</option>{objects.filter(o=>o.kind==='character').map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></Field>)}</div>}
    {kind==='fact'&&<Field label="关联实体"><select required value={value.fields.entityId??''} onChange={e=>field('entityId',e.target.value)}><option value="">选择角色、世界节点或伏笔</option>{objects.filter(o=>['character','world','foreshadow'].includes(o.kind)).map(o=><option value={o.id} key={o.id}>{o.title}</option>)}</select></Field>}
    <div className="form-grid">{(definitions[kind]??[]).map(([key,label])=><Field key={key} label={label}>{['targetWords','chapterOrder'].includes(key)?<input type="number" min="0" value={value.fields[key]??''} onChange={e=>field(key,Number(e.target.value))}/>:<textarea rows={['goal','rule','arc','background','constraints'].includes(key)?3:2} value={Array.isArray(value.fields[key])?value.fields[key].join('，'):value.fields[key]??''} onChange={e=>field(key,['aliases','participants'].includes(key)?e.target.value.split(/[,，]/).filter(Boolean):e.target.value)}/>}</Field>)}</div>
    <Field label="标签"><input value={tag} placeholder="以逗号分隔" onChange={e=>setTag(e.target.value)}/></Field>
    <details><summary>来源与依据</summary><Field label="用户明确设定 / 原文依据" hint="手工确认会记录为用户设定；原来的来源仍保留在修改历史中。"><textarea rows={3} value={quote} onChange={e=>setQuote(e.target.value)}/></Field>{object?.source&&<p className="muted">原来源：{object.source.type} · {object.source.versionId??'用户设定'} · {object.source.time}</p>}</details>
    {history&&<details><summary>状态与修改历史（{history.records.length} 条资料 / {history.changes.length} 次修改）</summary>{history.records.filter((r:any)=>r.id!==object?.id||r.source?.supersedes).map((r:any)=><div className="note-card" key={r.id}><span className="badge">{statusText[r.status]}</span><strong> {r.title}</strong><p>{String(r.fields.property??'')} {String(r.fields.value??'')}</p><blockquote>{r.source?.quote}</blockquote><small>{r.source?.type==='user'?'作者设定':r.source?.time} · {r.source?.versionId??r.updatedAt}</small></div>)}{history.changes.map((c:any)=><details key={c.id}><summary>{new Date(c.at).toLocaleString('zh-CN')} · {c.kind==='fact.supersede'?'作者确认替代事实':'资料修订'}</summary><p>修改前：{c.data.before?.body??c.data.before?.title??'新增'}</p><p>修改后：{c.data.after?.body??c.data.after?.title??'正文版本变化'}</p><pre>{JSON.stringify({before:c.data.before?.fields,after:c.data.after?.fields},null,2)}</pre></details>)}</details>}
    <label className="check-field"><input type="checkbox" checked={value.locked} onChange={e=>update('locked',e.target.checked)}/>锁定此对象，阻止导演与编辑器覆盖</label>
    <div className="form-footer"><button type="button" onClick={onClose}>取消</button><button className="solid" disabled={busy}>{busy?'保存中…':'保存'}</button></div>
  </form></Modal>;
}
export function Collection({kind,objects,onEdit,onAdd,onNavigate,onInspire}:{kind:Kind;objects:StoryObject[];onEdit:(o:StoryObject)=>void;onAdd:(kind:Kind)=>void;onNavigate:(id:string)=>void;onInspire:()=>void}){
  const [search,setSearch]=useState('');const [entity,setEntity]=useState('');const [chapter,setChapter]=useState('');const [graph,setGraph]=useState(kind==='relationship');
  const items=objects.filter(o=>(kind==='book'?['book','volume','chapter'].includes(o.kind):o.kind===kind)&&(!search||`${o.title} ${o.body} ${JSON.stringify(o.fields)}`.includes(search))&&(!entity||o.fields.entityId===entity)&&(!chapter||o.source?.chapterId===chapter)).sort((a,b)=>a.order-b.order);
  const byId=new Map(objects.map(o=>[o.id,o]));
  return <section className="collection"><header className="section-heading"><div><div className="eyebrow">STORY ATLAS</div><h1>{({book:'故事大纲',character:'人物档案',world:'世界设定',relationship:'人物关系',fact:'事实账本',event:'故事时间线',foreshadow:'伏笔与回声',idea:'灵感收件箱'} as any)[kind]??kindLabels[kind]}</h1><p>{({book:'区分准备发生的故事，与已经发生的事实。',character:'让每一个选择，都来自一个具体的人。',world:'那些让故事成立的地方、物品与规则。',relationship:'一段关系，可以有两种理解。',fact:'每一条事实，都能回到它的来源。',event:'故事内的时间，与读者看见它的顺序。',foreshadow:'记得那些尚未兑现的承诺。',idea:'让还没想好的念头，先有一个落脚点。'} as any)[kind]}</p></div><button className="solid" onClick={()=>onAdd(kind==='book'?'volume':kind)}><Plus size={16}/>添加{kind==='book'?'分卷':kindLabels[kind]}</button></header>
    <div className="collection-tools"><label className="search"><Search size={16}/><input aria-label="搜索资料" placeholder="搜索名称、属性或原文…" value={search} onChange={e=>setSearch(e.target.value)}/></label>{kind==='fact'&&<><select aria-label="按实体筛选" value={entity} onChange={e=>setEntity(e.target.value)}><option value="">全部实体</option>{objects.filter(o=>['world','character'].includes(o.kind)).map(o=><option value={o.id} key={o.id}>{o.title}</option>)}</select><select aria-label="按章节筛选" value={chapter} onChange={e=>setChapter(e.target.value)}><option value="">全部章节</option>{objects.filter(o=>o.kind==='chapter').map(o=><option value={o.id} key={o.id}>{o.title}</option>)}</select></>}{kind==='relationship'&&<button onClick={()=>setGraph(!graph)}><Network size={16}/>{graph?'切换列表':'查看关系图'}</button>}{kind==='idea'&&<button onClick={onInspire}>AI 帮我推演 <ArrowUpRight size={15}/></button>}</div>
    {graph&&kind==='relationship'&&<RelationshipGraph characters={objects.filter(o=>o.kind==='character')} relations={items} onSelect={onEdit}/>}
    {['book','character','world'].includes(kind)&&items.length>0&&<ObjectTree objects={items} onSelect={o=>['book','volume','chapter'].includes(o.kind)?onNavigate(o.id):onEdit(o)}/>}
    {!items.length?<div className="empty-inline"><BookOpen size={32} strokeWidth={1}/><h3>还没有{kindLabels[kind]}</h3><p>从一条具体的{kindLabels[kind]}开始，让它在创作中慢慢生长。</p><button onClick={()=>onAdd(kind==='book'?'volume':kind)}>添加第一条 <Plus size={14}/></button></div>:<div className={`object-list ${kind==='event'?'timeline-list':''}`}>{items.map(o=><article key={o.id} className={`object-card ${o.status==='revoked'||o.status==='stale'?'faded':''}`}>
      <div className="object-top"><span className={`badge ${o.status}`}>{statusText[o.status]}</span>{o.locked&&<Lock size={12}/>}<span className="muted small">{o.kind==='character'?String(o.fields.group??'未分组'):o.kind==='world'?String(o.fields.type??'实体'):o.kind==='event'?String(o.fields.storyTime??o.source?.time??'时间未知'):kindLabels[o.kind]}</span><button className="edit-link" onClick={()=>onEdit(o)}>编辑 <ArrowUpRight size={13}/></button></div>
      <button className="object-title" onClick={()=>['book','volume','chapter'].includes(o.kind)?onNavigate(o.id):onEdit(o)}>{o.parentId&&<small>{byId.get(o.parentId)?.title} / </small>}{o.title}</button>
      {o.kind==='relationship'&&<p className="relation-text">{byId.get(String(o.fields.fromId))?.title??'未关联'} <span>→ {String(o.fields.type??'关系')} →</span> {byId.get(String(o.fields.toId))?.title??'未关联'}</p>}
      <p className="object-excerpt">{o.kind==='chapter'?String(o.fields.goal??'尚未规划本章目标'):o.body||String(o.fields.goal??o.fields.value??'')}</p>
      {o.kind==='character'&&<div className="entity-details"><span><MapPin size={12}/>{String(o.fields.location??'位置待定')}</span><span>{String(o.fields.desire??'核心欲望待补充')}</span></div>}
      {o.kind==='character'&&objects.filter(f=>f.kind==='fact'&&f.status==='accepted'&&f.fields.entityId===o.id).slice(-3).map(f=><div key={f.id} className="projection"><span>{String(f.fields.property)}</span><strong>{String(f.fields.value)}</strong><button onClick={()=>f.source?.chapterId&&onNavigate(f.source.chapterId)}>来源 ↗</button></div>)}
      {o.kind==='foreshadow'&&<p className="muted">{String(o.fields.plantChapter??'尚未埋设')} → {String(o.fields.recoveryRange??'回收范围待定')} · {String(objects.filter(f=>f.kind==='fact'&&f.status==='accepted'&&f.fields.entityId===o.id&&f.fields.property==='foreshadowState').at(-1)?.fields.value??o.fields.state??'规划')}</p>}
      {o.source&&<div className="source-line"><span>{o.source.type==='user'?'作者设定':o.source.type==='ai'?'AI 提案设定':o.source.inference?'待确认推断':'原文依据'} · {o.source.modality==='knowledge'?'角色知情':o.source.modality==='memory'?'回忆':o.source.time}</span>{o.source.chapterId&&<button onClick={()=>onNavigate(o.source!.chapterId!)}>{byId.get(o.source.chapterId)?.title??'来源章节'} <ArrowUpRight size={12}/></button>}<details><summary>查看证据与版本</summary><blockquote>{o.source.quote||'未提供文字引用'}</blockquote><small>{o.source.versionId??`资料修订 ${o.revision}`} {o.source.policy??''}</small></details></div>}
      {!!o.tags.length&&<div className="tags">{o.tags.map(t=><span key={t}>#{t}</span>)}</div>}
    </article>)}</div>}
  </section>;
}
function ObjectTree({objects,onSelect}:{objects:StoryObject[];onSelect:(o:StoryObject)=>void}){
  const ids=new Set(objects.map(o=>o.id));const roots=objects.filter(o=>!o.parentId||!ids.has(o.parentId));
  const groups=[...new Set(roots.map(o=>String(o.kind==='character'?o.fields.group??'未分组':o.kind==='world'?o.fields.type??'世界节点':'全书结构')))];
  const node=(o:StoryObject,depth:number):any=>{const children=objects.filter(c=>c.parentId===o.id);return <li key={o.id}>{children.length&&depth<8?<details open={depth<1}><summary><button onClick={()=>onSelect(o)}>{o.locked&&<Lock size={12}/>} {o.title}</button><small>{children.length} 个下级</small></summary><ul>{children.map(c=>node(c,depth+1))}</ul></details>:<button onClick={()=>onSelect(o)}>{o.locked&&<Lock size={12}/>} {o.title} <ArrowUpRight size={12}/></button>}</li>;};
  return <details className="atlas-tree" open><summary>资料树 · 分组与层级导航</summary><div className="tree-groups">{groups.map(group=><section key={group}><h4>{group}</h4><ul>{roots.filter(o=>String(o.kind==='character'?o.fields.group??'未分组':o.kind==='world'?o.fields.type??'世界节点':'全书结构')===group).map(o=>node(o,0))}</ul></section>)}</div></details>;
}
function RelationshipGraph({characters,relations,onSelect}:{characters:StoryObject[];relations:StoryObject[];onSelect:(o:StoryObject)=>void}){
  const visible=characters.slice(0,30);const coords=new Map(visible.map((c,n)=>{const angle=n/visible.length*Math.PI*2-Math.PI/2;return [c.id,{x:360+240*Math.cos(angle),y:210+135*Math.sin(angle)}];}));
  return <div className="relationship-graph"><svg viewBox="0 0 720 420" role="img" aria-label="可点击角色与关系图"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="var(--accent)"/></marker></defs>{relations.map(r=>{const a=coords.get(String(r.fields.fromId));const b=coords.get(String(r.fields.toId));if(!a||!b)return null;return <g key={r.id} onClick={()=>onSelect(r)} role="button" tabIndex={0} aria-label={`编辑关系 ${r.title}`} onKeyDown={e=>e.key==='Enter'&&onSelect(r)}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} markerEnd="url(#arrow)"/><rect x={(a.x+b.x)/2-35} y={(a.y+b.y)/2-12} width="70" height="24" rx="8"/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2+4}>{String(r.fields.type??r.title)}</text><title>{r.title}：{r.body}</title></g>;})}{visible.map(c=>{const p=coords.get(c.id)!;return <g key={c.id} role="button" tabIndex={0} aria-label={`打开角色 ${c.title}`} onClick={()=>onSelect(c)} onKeyDown={e=>e.key==='Enter'&&onSelect(c)}><circle cx={p.x} cy={p.y} r="29"/><text className="node-initial" x={p.x} y={p.y+5}>{c.title.slice(0,1)}</text><text x={p.x} y={p.y+48}>{c.title}</text></g>;})}</svg>{!relations.length&&<p className="muted">角色可以直接打开。添加关系后，这里会显示方向、类型与双方认知。</p>}{characters.length>30&&<p className="muted">图中显示前 30 位角色，其余角色可在人物档案中查找。</p>}</div>;
}
