import { useEffect, useState } from 'react';
import { Archive, ArrowRight, BookOpen, BookMarked, Clapperboard, Feather, FileText, GitBranch, Lightbulb, Plus, Upload } from 'lucide-react';
import { api } from './api.js';
import { SourceLibrary } from './SourceLibrary.js';
import { CreativeAssets } from './CreativeAssets.js';
import type { ShelfProject } from '../shelf.js';

type Tab='books'|'sources'|'assets';
export function ProjectShelf({projects,health,onOpen,onNew,onDemo,onRefresh}:{projects:ShelfProject[];health:any;onOpen:(project:ShelfProject,mode?:'writer'|'director')=>Promise<void>;onNew:(path:'idea'|'import')=>void;onDemo:()=>Promise<void>;onRefresh:()=>Promise<void>}){
  const [tab,setTab]=useState<Tab>(()=>{const old=localStorage.getItem('novel-global-tab');return old==='sources'||old==='assets'?old:'books';});
  const [archived,setArchived]=useState(false),[layout,setLayout]=useState<'grid'|'list'>('grid'),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState('');
  useEffect(()=>{localStorage.setItem('novel-global-tab',tab);window.scrollTo(0,0);},[tab]);
  const changeCover=async(p:ShelfProject,file:File)=>{setBusy(p.id);setError('');try{
    if(file.size>2_000_000)throw new Error('封面限 2 MB');
    const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));
    await api(`/projects/${p.id}/cover`,{mime:file.type,base64:btoa(binary),expectedRevision:p.coverRevision??null});await onRefresh();
  }catch(caught){setError((caught as Error).message);}finally{setBusy('');}};
  const removeCover=async(p:ShelfProject)=>{setBusy(p.id);setError('');try{await api(`/projects/${p.id}/cover`,{expectedRevision:p.coverRevision},'DELETE');await onRefresh();}catch(caught){setError((caught as Error).message);}finally{setBusy('');}};
  const listed=projects.filter(p=>p.archived===archived&&`${p.title} ${p.genre} ${p.lineage?.sourceTitle??''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return <main className="global-shell"><nav className="global-nav" aria-label="全局工作空间"><button className={tab==='books'?'active':''} onClick={()=>setTab('books')}><BookOpen size={17}/>作品书架</button><button className={tab==='sources'?'active':''} onClick={()=>setTab('sources')}><GitBranch size={17}/>原作资料</button><button className={tab==='assets'?'active':''} onClick={()=>setTab('assets')}><Feather size={17}/>创作资产</button></nav>
    {error&&<p role="alert" className="global-error">{error}</p>}
    {tab==='sources'&&<div className="global-content"><SourceLibrary embedded health={health} onClose={()=>setTab('books')} onOpen={async(p,mode)=>{await onOpen(p as ShelfProject,mode);setTab('books');}}/></div>}
    {tab==='assets'&&<div className="global-content"><CreativeAssets/></div>}
    {tab==='books'&&<div className="global-content">
      {projects.length===0?<div className="shelf-first"><div className="eyebrow">YOUR STORIES, IN THE MAKING</div><h1>从一个念头，写到最后一页。</h1><p>亲自执笔，或把下一段旅程交给导演。故事和创作资料始终在同一个工作空间。</p><div className="shelf-paths"><button onClick={()=>setTab('sources')}><GitBranch size={22}/><span><strong>从已有作品创作</strong><small>按截止点继承人物与世界</small></span><ArrowRight size={16}/></button><button onClick={()=>onNew('idea')}><Lightbulb size={22}/><span><strong>我有一个灵感</strong><small>从前提出发建立小说</small></span><ArrowRight size={16}/></button><button onClick={()=>onNew('import')}><FileText size={22}/><span><strong>我已经有小说</strong><small>导入正文继续写作</small></span><ArrowRight size={16}/></button></div><button className="demo-link" onClick={()=>void onDemo().catch(caught=>setError((caught as Error).message))}>创建可重置的原创演示项目 <ArrowRight size={15}/></button></div>:<div className="shelf-heading"><span className="eyebrow">YOUR WORKSPACE</span><h1>作品书架</h1><p>继续写作、查看待审成果，或从原作与创作资产开始新的故事。</p><div className="shelf-quick"><button onClick={()=>onNew('idea')} className="solid"><Plus size={16}/>新建作品</button><button onClick={()=>setTab('sources')}><GitBranch size={15}/>从已有作品创作</button><button onClick={()=>setTab('assets')}><Feather size={15}/>创作资产</button></div></div>}
      <section className="shelf-collection"><div className="shelf-controls"><div><h2>{archived?'已归档作品':'继续创作'} <small>{listed.length}</small></h2><p className="muted">封面和最近章节来自本地作品；待审数来自实际成果状态。</p></div><div className="inline-actions"><input aria-label="搜索作品" placeholder="搜索作品或来源" value={query} onChange={event=>setQuery(event.target.value)}/><button aria-pressed={layout==='grid'} onClick={()=>setLayout('grid')}>网格</button><button aria-pressed={layout==='list'} onClick={()=>setLayout('list')}>列表</button><button onClick={()=>setArchived(!archived)}><Archive size={14}/>{archived?'返回作品':'已归档'}</button></div></div>
        {listed.length?<div className={`shelf-cards ${layout}`}>{listed.map((p,n)=><article className="shelf-card" key={p.id}><button className={`shelf-open tone-${n%3}`} onClick={()=>void onOpen(p)} aria-label={`打开${p.title}`}><div className="shelf-cover">{p.coverRevision?<img src={`/api/novel-studio/projects/${p.id}/cover?v=${p.coverRevision}`} alt={`${p.title}的封面`}/>:<><span>{p.genre||'小说'} · NOVEL STUDIO</span><strong>{p.title}</strong><BookMarked size={30} strokeWidth={1}/></>}</div><div className="shelf-info"><h3>{p.title}</h3><p>{p.lineage?`源自 ${p.lineage.sourceTitle}`:p.genre||'原创故事'}</p><small>{p.recentChapter?`最近章节 · ${p.recentChapter.title}`:'尚无章节，打开后可以开始创作'}</small><span>{p.pendingReview?`${p.pendingReview} 项待审 · `:''}{p.archived?'已归档 · 打开后恢复':new Date(p.updatedAt).toLocaleDateString('zh-CN')+' 更新'}</span></div></button><div className="shelf-card-actions"><label className={busy===p.id?'disabled':''}><Upload size={13}/>{p.coverRevision?'更换封面':'上传封面'}<input type="file" accept="image/png,image/jpeg,image/webp" aria-label={`${p.title}上传封面`} disabled={busy===p.id} onChange={event=>{const file=event.target.files?.[0];if(file)void changeCover(p,file);event.target.value='';}}/></label>{p.coverRevision&&<button disabled={busy===p.id} onClick={()=>void removeCover(p)}>移除封面</button>}<button onClick={()=>void onOpen(p,'director')}><Clapperboard size={13}/>导演</button></div></article>)}</div>:<div className="shelf-empty"><BookOpen size={24}/><h3>{query?'没有匹配的作品':archived?'还没有归档作品':'还没有作品'}</h3><p>{query?'换个关键词，或清除搜索。':archived?'归档作品会保留正文和版本。':'从灵感或原作开始，作品会持久保存。'}</p>{!query&&!archived&&<button onClick={()=>onNew('idea')}><Plus size={15}/>创建第一本书</button>}</div>}
      </section>
    </div>}
  </main>;
}
