import { useEffect,useRef,useState } from 'react';
import { BookOpen,ArrowRight,Upload,Search,Pause,Play,FileText } from 'lucide-react';
import { Modal,Field } from './Modal.js';
import { api,download,statusText } from './api.js';
import { GenerationInspector } from './RequestInspector.js';
import { fieldLabels,RelationshipGraph } from './Objects.js';
import { inheritedFields } from '../source-contracts.js';
import type { Project } from '../contracts.js';
const kinds:Record<string,string>={character:'角色',world:'世界',relationship:'关系',fact:'事实',event:'事件',foreshadow:'未决线索'};
const selectionLabels:Record<string,string>={main:'主要管理',background:'背景引用',omit:'本次不导入',exclude:'明确改编排除'};
const emptySpec={title:'',mode:'continuation',template:'canonical',boundary:{kind:'after-chapter',id:null},inheritPrefix:true,inheritDynamics:true,inheritPlot:true,inheritStyle:false,categories:Object.keys(kinds),selection:{},dependencies:{},overrides:[],allowGaps:false,goal:'从选定位置接写，先推进当前场景和未兑现线索；不补造原作历史。'};

export function SourceLibrary({onClose,onOpen,health}:{onClose:()=>void;onOpen:(p:Project,mode:'writer'|'director')=>Promise<void>;health:any}){
 const [styles,setStyles]=useState<any[]>([]);const [works,setWorks]=useState<any[]>([]),[work,setWork]=useState<any>(),[version,setVersion]=useState<any>(),[run,setRun]=useState<any>(),[manifest,setManifest]=useState<any>();
 const [spec,setSpec]=useState<any>(emptySpec),[title,setTitle]=useState(''),[author,setAuthor]=useState(''),[origin,setOrigin]=useState('用户提供的本地资料'),[rights,setRights]=useState(''),[files,setFiles]=useState<any[]>([]),[encoding,setEncoding]=useState('utf-8');
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[calls,setCalls]=useState(24),[tokens,setTokens]=useState(100000),[auto,setAuto]=useState(false),[preview,setPreview]=useState<any>(),[entryMode,setEntryMode]=useState<'writer'|'director'>('director');
 const [showGraph,setShowGraph]=useState(false);const [q,setQ]=useState(''),[kind,setKind]=useState('character'),[offset,setOffset]=useState(0),[page,setPage]=useState<any>(),[detail,setDetail]=useState<any>(),[reading,setReading]=useState<string>(),[evidenceRange,setEvidenceRange]=useState<any>(),[inspection,setInspection]=useState<string>(),[directory,setDirectory]=useState<any[]>(),[diff,setDiff]=useState<any>(),[savedLists,setSavedLists]=useState<any[]>([]);
 const autoBusy=useRef(false),scopeVersion=useRef('');const running=run&&['QUEUED','RUNNING','PAUSE_REQUESTED'].includes(run.task.status);
 const perform=async(fn:()=>Promise<any>)=>{setBusy(true);setError('');try{return await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const load=async()=>{setStyles(await api('/sources/configurations'));setWorks(await api('/sources'));setSavedLists(await api('/manifests'));};
 useEffect(()=>{void perform(load);},[]);
 const change=(patch:any)=>{setSpec((s:any)=>({...s,...patch}));setPreview(undefined);};
 const chooseMode=(mode:string)=>change({mode,template:mode==='independent'?'parallel':mode==='divergence'?'divergent':'canonical',inheritPrefix:mode!=='independent',inheritDynamics:mode!=='independent',inheritPlot:mode!=='independent',categories:mode==='independent'?['character','world']:Object.keys(kinds),boundary:{kind:mode==='independent'?'all-materials':mode==='divergence'?'before-chapter':'after-chapter',id:version?.chapters.at(-1)?.id??null}});
 const chooseVersion=async(w:any,id:string)=>{const v=await api(`/source-versions/${id}`);setWork((await api('/sources')).find((item:any)=>item.id===w.id)??w);setVersion(v);setRun(undefined);setManifest(undefined);setPreview(undefined);setPage(undefined);setDirectory(undefined);setFiles([]);setDetail(undefined);scopeVersion.current=id;change({...emptySpec,title:w.title+' · 新的篇章',mode:spec.mode,template:spec.template,inheritPrefix:spec.inheritPrefix,inheritDynamics:spec.inheritDynamics,inheritPlot:spec.inheritPlot,categories:spec.categories,versionId:id,boundary:{kind:spec.mode==='independent'?'all-materials':spec.mode==='divergence'?'before-chapter':'after-chapter',id:v.chapters.at(-1)?.id??null}});};
 const loadRun=async(id:string)=>{const r=await api(`/source-runs/${id}`);const v=await api(`/source-versions/${r.run.versionId}`);setRun(r);change({runId:id,versionId:r.run.versionId,boundary:{kind:'after-chapter',id:v.chapters.find((c:any)=>c.ordinal===r.run.cutoff)?.id??null}});setCalls(r.task.budget.calls);setTokens(r.task.budget.outputTokens);return r;};
 useEffect(()=>{if(!run?.run.id)return;let live=true;const timer=setInterval(()=>{void api(`/source-runs/${run.run.id}`).then(r=>{if(live)setRun(r);}).catch(e=>{if(live)setError(e.message);});},1400);return()=>{live=false;clearInterval(timer);};},[run?.run.id]);
 const cutoff=()=>{if(!version)return 0;if(spec.boundary.kind==='all-materials')return version.chapters.at(-1)?.ordinal??0;const c=version.chapters.find((c:any)=>spec.boundary.kind.endsWith('volume')?c.volumeId===spec.boundary.id:c.id===spec.boundary.id);if(!c)return 0;return spec.boundary.kind==='after-volume'?Math.max(...version.chapters.filter((x:any)=>x.volumeId===c.volumeId).map((x:any)=>x.ordinal)):c.ordinal-(spec.boundary.kind.startsWith('before')?1:0);};
 const assetQuery=()=>`cutoff=${cutoff()}&kind=${kind}&q=${encodeURIComponent(q)}&offset=${offset}&limit=30`;
 useEffect(()=>{if(!run)return;let live=true;void api(`/source-runs/${run.run.id}/assets?${assetQuery()}`).then(p=>{if(live)setPage(p);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[run?.run.id,run?.run.revision,q,kind,offset,spec.boundary]);
 const currentSpec=()=>({...spec,versionId:version.id,runId:run.run.id});
 const save=async()=>{const result=manifest?.status==='staging'?await api(`/manifests/${manifest.id}`,{revision:manifest.revision,spec:currentSpec()},'PATCH'):await api('/manifests',currentSpec());setManifest(result.manifest);setPreview(result.preview);await load();return result;};
 const activate=async()=>{const result=await save();if(result.preview.conflicts.length){setError('需要先处理下方冲突；未创建半成品作品。');return;}const p=await api(`/manifests/${result.manifest.id}/activate`,{revision:result.manifest.revision});await onOpen(p,entryMode);};
 useEffect(()=>{if(auto&&run?.task.status==='COMPLETED'&&!autoBusy.current){autoBusy.current=true;setAuto(false);void perform(activate).finally(()=>{autoBusy.current=false;});}},[auto,run?.task.status]);
 const start=async(recommended=false)=>{if(!consent)throw new Error('请先确认把所选范围发给已配置模型。');const r=await api(`/sources/${work.id}/runs`,{versionId:version.id,boundary:spec.boundary,provider:'dsh',cloudAuthorized:true,budget:{calls,outputTokens:tokens,contextChars:36000}});setRun(r);change({runId:r.run.id});setAuto(recommended);setMessage(recommended?'按推荐选择准备。若有歧义或冲突将停在继承预览。':'任务已保存。可以关闭窗口，稍后从资料库恢复。');await load();};
 const control=async(action:string,budget=false)=>{setAuto(false);await api(`/source-runs/${run.run.id}/control`,{action,...(budget?{budget:{calls,outputTokens:tokens}}:{})});setRun(await api(`/source-runs/${run.run.id}`));};
 const select=(id:string,mode:string)=>change({selection:{...spec.selection,[id]:{...spec.selection[id],mode}}});
 const batch=async(mode:string)=>{const p=await api(`/source-runs/${run.run.id}/assets?${assetQuery()}&allIds=true`);change({selection:{...spec.selection,...Object.fromEntries(p.allIds.map((id:string)=>[id,{...spec.selection[id],mode}]))}});};
 return <Modal title="从已有作品，开始自己的故事" wide onClose={onClose}><div className="source-studio">
  {error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}
  <div className="source-intro"><BookOpen size={25}/><p>原作保存在只读资料库。先确定接续位置，再分析允许范围；选中的资料将成为独立作品，可直接交给导演或亲自执笔。</p></div>
  <div className="source-layout"><aside className="source-library"><h3>原作资料库</h3><button disabled={busy} onClick={()=>{setWork(undefined);setVersion(undefined);setRun(undefined);setFiles([]);setManifest(undefined);setPreview(undefined);setSpec(emptySpec);}}>＋ 导入新的资料</button>{works.map(w=><details key={w.id} open={work?.id===w.id}><summary>{w.title}{w.archived?' · 已归档':''}</summary>{w.versions.map((v:any)=><button className={version?.id===v.id?'selected':''} key={v.id} onClick={()=>void perform(()=>chooseVersion(w,v.id))}>版本 {v.version} · {v.chapters.length} 个章节/资料</button>)}{w.runs.map((r:any)=><button key={r.id} onClick={()=>void perform(async()=>{await chooseVersion(w,r.versionId);await loadRun(r.id);})}>{statusText[r.status]} · 截止位置 {r.cutoff}</button>)}</details>)}{!works.length&&<p className="muted">尚无资料。可以导入小说，也可以只提供人物档案与世界说明。</p>}{savedLists.filter(m=>m.status==='staging').map(m=><button key={m.id} onClick={()=>void perform(async()=>{const w=works.find(w=>w.id===m.workId);await chooseVersion(w,m.versionId);await loadRun(m.spec.runId);setManifest(m);setSpec(m.spec);setPreview((await api(`/manifests/${m.id}`)).preview);})}>恢复清单 · {m.spec.title}</button>)}</aside>
  <section className="source-workflow"><div className="form-grid"><Field label="创作方式"><select disabled={running} value={spec.mode} onChange={e=>chooseMode(e.target.value)}><option value="continuation">原作续写</option><option value="divergence">分歧改编</option><option value="independent">独立同人 / 资料包</option></select></Field><Field label="继承模板"><select disabled={running} value={spec.template} onChange={e=>change({template:e.target.value})}><option value="canonical">原作相容 · 不改继承事实</option><option value="divergent">指定分歧 · 保留此前历史</option><option value="parallel">平行设定 · 明确重置前提</option></select></Field></div>
   {(!version||files.length>0)&&<div className="note-card"><h3>本地材料</h3><div className="form-grid"><Field label="原作名称"><input value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="原作者 / 资料提供者"><input value={author} onChange={e=>setAuthor(e.target.value)}/></Field><Field label="来源"><input value={origin} onChange={e=>setOrigin(e.target.value)}/></Field><Field label="使用范围说明"><input value={rights} placeholder="保留来源说明；非商业不自动取得授权" onChange={e=>setRights(e.target.value)}/></Field></div><div className="inline-actions"><select aria-label="原作文件编码" value={encoding} onChange={e=>setEncoding(e.target.value)}><option value="utf-8">UTF-8</option><option value="gb18030">GB18030</option></select><input type="file" multiple accept=".txt,.md,.markdown" aria-label="选择原作或资料包文件" onChange={e=>{const list=Array.from(e.target.files??[]);void perform(async()=>{const parsed=await Promise.all(list.map(async f=>{if(f.size>20000000)throw new Error('单文件限20MB');const bytes=new Uint8Array(await f.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return {name:f.name,base64:btoa(binary),encoding,kind:spec.mode==='independent'?'character':'novel',stage:'当前资料版本',scope:'baseline'};}));setFiles(parsed);if(!title)setTitle(list[0]?.name.replace(/\.[^.]+$/,'')??'');});}}/></div>{files.map((f,n)=><div className="source-file" key={n}><span>{f.name}</span><select aria-label={`${f.name} 资料类型`} value={f.kind} onChange={e=>setFiles(files.map((x,i)=>i===n?{...x,kind:e.target.value}:x))}>{[['novel','小说正文'],['character','人物档案'],['world','世界说明'],['plot','剧情材料'],['supplement','补充材料']].map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input aria-label={`${f.name} 资料阶段`} value={f.stage} onChange={e=>setFiles(files.map((x,i)=>i===n?{...x,stage:e.target.value}:x))}/><select aria-label={`${f.name} 允许用途`} value={f.scope} onChange={e=>setFiles(files.map((x,i)=>i===n?{...x,scope:e.target.value}:x))}><option value="baseline">可作继承证据</option><option value="author-reference">隔离参考 · 不进入生成</option></select></div>)}<p className="muted">只登记和预览不会调用模型。原始字节、解码文本和证据偏移均保留。支持 TXT / Markdown，不读取 DRM 或执行文件脚本。</p><button className="solid" disabled={busy||!files.length||!title} onClick={()=>void perform(async()=>{const input={title,author:author||'未提供',origin,rights:rights||'使用范围由提供者确认',files};const result=work?{work,version:await api(`/sources/${work.id}/versions`,{source:input,revision:work.revision})}:await api('/sources',input);await load();await chooseVersion(result.work,result.version.id);})}><Upload size={16}/>{work?'登记为新来源版本':'保存原作并预览目录'}</button></div>}
   {version&&<><div className="source-heading"><div><h3>{work.title} <span className="badge">只读 · v{version.version}</span></h3><p className="muted">{work.author} · {version.chapters.length} 个目录项 · {version.raw.length.toLocaleString()} 字符</p></div><button onClick={()=>{setFiles([{name:'修订稿.md',raw:'',encoding,kind:'novel',stage:'新修订',scope:'baseline'}]);setTitle(work.title);}}>新增修订版本</button><button onClick={()=>void perform(async()=>{await api(`/sources/${work.id}/archive`,{revision:work.revision,archived:!work.archived});await load();setWork({...work,archived:!work.archived,revision:work.revision+1});})}>{work.archived?'恢复资料':'归档资料'}</button></div>
    <div className="form-grid"><Field label="接续边界"><select disabled={running} value={spec.boundary.kind} onChange={e=>{const k=e.target.value;change({boundary:{kind:k,id:k.endsWith('volume')?version.chapters[0]?.volumeId:version.chapters.at(-1)?.id}});}}><option value="after-chapter">接在这一章之后 · 保留至本章</option><option value="before-chapter">从这一章重写 · 不保留本章</option><option value="after-volume">接在这一卷之后</option><option value="before-volume">从这一卷之前分歧</option>{spec.mode==='independent'&&<option value="all-materials">全部允许的资料包</option>}</select></Field><Field label={spec.boundary.kind.endsWith('volume')?'选择卷（按实际目录）':'选择章节 / 材料（按实际目录）'}><select disabled={running||spec.boundary.kind==='all-materials'} value={spec.boundary.id??''} onChange={e=>change({boundary:{...spec.boundary,id:e.target.value}})}>{(spec.boundary.kind.endsWith('volume')?[...new Map(version.chapters.map((c:any)=>[c.volumeId,{id:c.volumeId,title:c.volumeTitle}])).values()]:version.chapters).map((c:any)=><option key={c.id} value={c.id}>{c.ordinal?`${c.ordinal} · `:''}{c.title}{c.excluded?'（隔离）':''}</option>)}</select></Field></div><p className="notice">允许证据：目录位置 1–{cutoff()}。其后 {version.chapters.length-cutoff()} 项及隔离资料不进入分析、继承事实或后续生成。{spec.inheritPrefix?`新章从目录位置 ${cutoff()+1} 开始。`:'本书独立从第一章开始。'}</p>
    <details><summary>目录与原文 · 校正 / 阅读 / 来源版本比较</summary>{version.warnings.map((w:string,n:number)=><p className="notice" key={n}>{w}</p>)}<div className="source-directory">{(directory??version.chapters).map((c:any,n:number)=><div key={c.id}><button onClick={()=>setReading(c.id)}>{c.ordinal} · {c.title}</button>{directory&&<><input aria-label={`目录${n+1}名称`} value={c.title} onChange={e=>setDirectory(directory.map((x,i)=>i===n?{...x,title:e.target.value}:x))}/>{['start','bodyStart','end'].map(field=><input type="number" aria-label={`目录${n+1}${field}`} key={field} value={c[field]} onChange={e=>setDirectory(directory.map((x,i)=>i===n?{...x,[field]:Number(e.target.value)}:x))}/>)}<label><input type="checkbox" checked={c.excluded} onChange={e=>setDirectory(directory.map((x,i)=>i===n?{...x,excluded:e.target.checked}:x))}/>排除</label></>}</div>)}</div>{!directory?<button onClick={()=>setDirectory(structuredClone(version.chapters))}>校正目录 · 保存为新版本</button>:<button onClick={()=>void perform(async()=>{const v=await api(`/source-versions/${version.id}/directory`,{chapters:directory.map(({ordinal,...c})=>c)});await load();await chooseVersion(work,v.id);})}>保存目录修订</button>}<select aria-label="比较来源版本" defaultValue="" onChange={e=>{if(e.target.value)void perform(async()=>setDiff(await api(`/source-versions/${version.id}/diff?against=${e.target.value}`)));}}><option value="">比较其他版本…</option>{works.find(w=>w.id===work.id)?.versions.filter((v:any)=>v.id!==version.id).map((v:any)=><option key={v.id} value={v.id}>版本 {v.version}</option>)}</select>{diff&&<div className="notice"><p>{diff.message}</p><p>{diff.chapters.filter((c:any)=>c.changed).length} 项新增或变化；可用所选版本新建清单，不更新旧作品。</p></div>}</details>
    <Field label="新作品名称"><input value={spec.title} onChange={e=>change({title:e.target.value})}/></Field><Field label="本书目标 / 分歧说明"><textarea rows={3} value={spec.goal} onChange={e=>change({goal:e.target.value})}/></Field>
    <div className="source-options">{[['inheritPrefix','锁定前缀正文'],['inheritDynamics','当前状态与成长阶段'],['inheritPlot','历史与未决剧情']].map(([key,label])=><label key={key}><input type="checkbox" checked={spec[key]} onChange={e=>change({[key]:e.target.checked})}/>{label}</label>)}</div><Field label="新作品文风配置"><select value={spec.configurationVersionId??''} onChange={e=>change({configurationVersionId:e.target.value||undefined,inheritStyle:!!e.target.value})}><option value="">沿用全局默认</option>{styles.filter(v=>v.applicable).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field><p className="muted">选定配置会绑定到新作品，导演任务固定其版本；不会修改已有作品配置。独立同人默认不继承地点、伤势、持有物、秘密和原作主线。</p>
    <div className="note-card"><h3>有边界的准备任务</h3><div className="form-grid"><Field label="总模型调用预算"><input type="number" min={1} max={1000} value={calls} onChange={e=>setCalls(Number(e.target.value))}/></Field><Field label="总输出 token 预算"><input type="number" min={1000} max={3000000} value={tokens} onChange={e=>setTokens(Number(e.target.value))}/></Field></div><p className="muted">{health?.dsh?.name??'模型状态读取中'}。每批最多 16 个发现候选；密集片段继续细分。作品角色总数没有业务截断。</p><label className="source-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>我允许将以上所选范围发送给 DSH 已配置模型，在此预算内分析。</label><div className="inline-actions"><button className="solid" disabled={busy||running||!consent||work.archived||!health?.dsh?.available} onClick={()=>void perform(()=>start(true))}>按推荐配置准备并创建 <ArrowRight size={15}/></button><button disabled={busy||running||!consent||work.archived||!health?.dsh?.available} onClick={()=>void perform(()=>start(false))}>分析后自定义继承</button></div></div>
   </>}
   {run&&<><section className="source-progress" aria-live="polite"><h3>{statusText[run.task.status]} · {run.covered}/{run.segments} 个片段已覆盖</h3><progress max={run.segments||1} value={run.covered}/><p>{run.assets} 项素材 · {run.gaps.length} 个未完成范围 · {run.task.usage.calls}/{run.task.budget.calls} 次调用 · {run.task.usage.outputTokens.toLocaleString()} 输出 token{run.task.usage.estimated?'（含估算）':''}</p>{run.task.error&&<p className="notice error">{run.task.error.message}</p>}<div className="inline-actions">{running?<button onClick={()=>void perform(()=>control('pause'))}><Pause size={15}/>暂停</button>:!['COMPLETED','CANCELED'].includes(run.task.status)&&<><button onClick={()=>void perform(()=>control('resume',true))}><Play size={15}/>按以上预算续跑</button><button onClick={()=>void perform(()=>control('redelegate',true))}>按人工修订重新委派</button></>}{!['COMPLETED','CANCELED'].includes(run.task.status)&&<button onClick={()=>void perform(()=>control('cancel'))}>取消任务</button>}<button onClick={()=>setInspection(run.task.id)}>检查实际请求与用量</button></div><details><summary>实际事件与未完成片段</summary>{run.gaps.map((s:any)=><p key={s.id} className="warning">{s.chapterId} {s.start}–{s.end}：{s.error??s.state}</p>)}{run.events.slice(0,16).map((e:any)=><p key={e.id}>{e.message}</p>)}</details></section>
    {run.profiles?.map((t:any)=><div className="note-card" key={t.id}><strong>所选角色档案 · {statusText[t.status]}</strong><p>{t.usage.calls}/{t.budget.calls} 次调用 · {t.usage.outputTokens} 输出 token</p>{t.error&&<p className="notice error">{t.error.message}</p>}<button onClick={()=>setInspection(t.id)}>查看档案实际请求</button>{['pause','resume','redelegate','cancel'].filter(a=>['QUEUED','RUNNING'].includes(t.status)?['pause','cancel'].includes(a):['PAUSED','FAILED','NEEDS_INPUT'].includes(t.status)?['resume','redelegate','cancel'].includes(a):false).map(a=><button key={a} onClick={()=>void perform(async()=>{await api(`/source-runs/${run.run.id}/profile-control`,{taskId:t.id,action:a});setRun(await api(`/source-runs/${run.run.id}`));})}>{{pause:'暂停',resume:'恢复',redelegate:'按新版本重试',cancel:'取消'}[a]}</button>)}</div>)}
    <h3>自定义继承</h3><button onClick={()=>setShowGraph(true)}>查看截止点关系图</button><div className="source-options">{Object.entries(kinds).map(([key,label])=><label key={key}><input type="checkbox" checked={spec.categories.includes(key)} onChange={e=>change({categories:e.target.checked?[...spec.categories,key]:spec.categories.filter((k:string)=>k!==key)})}/>{label}</label>)}</div>
    <div className="source-filter"><Search size={16}/><input aria-label="搜索原作素材" placeholder="姓名、别名、身份…" value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/><select aria-label="素材分类" value={kind} onChange={e=>{setKind(e.target.value);setOffset(0);}}>{Object.entries(kinds).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select aria-label="按筛选结果批量选择" value="" onChange={e=>{if(e.target.value)void perform(()=>batch(e.target.value));}}><option value="">跨页批量调整…</option>{Object.entries(selectionLabels).map(([key,label])=><option key={key} value={key}>全部筛选结果：{label}</option>)}</select></div>
    <div className="source-assets">{page?.items.map((a:any)=><div className="source-asset" key={a.id}><button onClick={()=>setDetail(a)}><span><strong>{a.name}</strong><small>{a.identity||a.description} · {a.evidence.length} 处证据</small></span></button><span className={`badge ${a.status==='verified'?'accepted':'candidate'}`}>{a.status==='verified'?'引文已校验':a.status==='ambiguous'?'身份待消歧':'不确定'}</span><select aria-label={`${a.name} 继承方式`} value={spec.selection[a.id]?.mode??(spec.categories.includes(a.kind)?'main':'omit')} onChange={e=>select(a.id,e.target.value)}>{Object.entries(selectionLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>)}</div><div className="inline-actions"><span>{page?.total??0} 项 · 本页 {page?.items.length??0} 项</span><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-30))}>上一页</button><button disabled={page?.next==null} onClick={()=>setOffset(page.next)}>下一页</button><button onClick={()=>void perform(async()=>download('原作素材-所选截止点.json',JSON.stringify(await api(`/source-runs/${run.run.id}/export?cutoff=${cutoff()}`),null,2),'application/json'))}>导出范围内全部素材</button></div>
    <div className="form-footer"><button disabled={busy} onClick={()=>void perform(async()=>{const saved=await save();setMessage(`继承清单 v${saved.manifest.revision} 已保存，可关闭后恢复。`);})}>保存选择清单</button><button disabled={busy} onClick={()=>void perform(async()=>setPreview(await api('/manifests/preview',currentSpec())))}>预览依赖与差异</button></div>
    {preview&&<div className="note-card"><h3>创建前的继承清单</h3><p>{preview.selected.filter((s:any)=>s.mode==='main').length} 项主要资料 · {preview.selected.filter((s:any)=>s.mode==='background').length} 个背景引用 · {preview.excluded.length} 项明确排除 · {preview.pending.length} 项待决策 · {spec.overrides.length} 项改编覆盖</p>{preview.conflicts.map((c:any,n:number)=><p className="notice error" key={n}>{c.message}</p>)}{preview.pending.map((c:any)=><p className="warning" key={c.id}>{c.message}</p>)}<details><summary>依赖补全与改编约定</summary><pre>{preview.contract}</pre>{preview.selected.filter((s:any)=>s.mode==='background').map((s:any)=><p key={s.asset.id}>{s.asset.name}：{s.reason}</p>)}</details><label className="source-consent"><input type="checkbox" checked={spec.allowGaps} onChange={e=>change({allowGaps:e.target.checked})}/>明确接受带缺口启动（歧义/未证实结论不会进入正式事实）</label></div>}
    <div className="form-footer"><select aria-label="创建后进入模式" value={entryMode} onChange={e=>setEntryMode(e.target.value as any)}><option value="director">进入导演模式</option><option value="writer">进入写作模式</option></select><button className="solid" disabled={busy||running||!spec.title} onClick={()=>void perform(activate)}>创建可写的新作品 <ArrowRight size={16}/></button>{manifest?.status==='staging'&&<button onClick={()=>void perform(async()=>{await api(`/manifests/${manifest.id}/cancel`,{revision:manifest.revision});setManifest(undefined);await load();})}>取消暂存清单</button>}</div>
   </>}
  </section></div>
  {detail&&<AssetDetail asset={detail} spec={spec} run={run} onClose={()=>setDetail(undefined)} onChange={change} onRead={(id:string,start:number,end:number)=>{setReading(id);setEvidenceRange({id,start,end});}} onDecision={async(data:any)=>{await api(`/source-runs/${run.run.id}/decisions`,{...data,revision:run.run.revision});setRun(await api(`/source-runs/${run.run.id}`));setDetail(undefined);}} onProfile={async()=>{await api(`/source-runs/${run.run.id}/profiles`,{ids:[detail.id],cloudAuthorized:consent,budget:{calls:3,outputTokens:12000,contextChars:36000}});setDetail(undefined);setRun(await api(`/source-runs/${run.run.id}`));setMessage('深入档案任务已保存；进度与错误显示在准备任务下方，生成后仍需审阅接受。');}}/>}
  {showGraph&&run&&<SourceGraphView runId={run.run.id} cutoff={cutoff()} onClose={()=>setShowGraph(false)} onSelect={(a:any)=>{setShowGraph(false);setDetail(a);}}/>}
  {reading&&version&&<Modal title="只读原文 · 证据定位" wide onClose={()=>setReading(undefined)}>{(()=>{const c=version.chapters.find((c:any)=>c.id===reading);return c?<><h3>{c.title}</h3><p className="muted">来源 v{version.version} · UTF-16 {c.bodyStart}–{c.end}{c.ordinal>cutoff()?' · 超出本次截止点，仅供作者隔离阅读':''}</p><pre className="source-prose">{evidenceRange?.id===c.id?<>{version.raw.slice(c.bodyStart,evidenceRange.start)}<mark>{version.raw.slice(evidenceRange.start,evidenceRange.end)}</mark>{version.raw.slice(evidenceRange.end,c.end)}</>:version.raw.slice(c.bodyStart,c.end)}</pre></>:<p>当前来源版本未包含此章节。</p>;})()}</Modal>}
  {inspection&&run&&<GenerationInspector pid={run.task.projectId} taskId={inspection} onClose={()=>setInspection(undefined)}/>}
 </div></Modal>;
}

function AssetDetail({asset:a,spec,run,onClose,onChange,onRead,onDecision,onProfile}:any){
 const [property,setProperty]=useState(''),[value,setValue]=useState(''),[reason,setReason]=useState(''),[retcon,setRetcon]=useState(false),[name,setName]=useState(a.name),[identity,setIdentity]=useState(a.identity),[target,setTarget]=useState(''),[splitStarts,setSplitStarts]=useState<number[]>([]),[refText,setRefText]=useState(JSON.stringify(a.refs)),[fieldsText,setFieldsText]=useState(JSON.stringify(a.fields)),[decisions,setDecisions]=useState<any[]>([]),[error,setError]=useState('');const keys=Object.keys(a.fields);const fields=Object.keys(inheritedFields(a,spec));
 useEffect(()=>{void api(`/source-runs/${run.run.id}/decisions`).then(setDecisions).catch(e=>setError(e.message));},[run.run.id,run.run.revision]);
 const perform=async(fn:()=>Promise<void>)=>{try{setError('');await fn();}catch(e){setError((e as Error).message);}};
 return <Modal title={`${a.name} · 来源、字段与依赖`} wide onClose={onClose}>{error&&<p className="notice error">{error}</p>}<p>{a.description}</p><p className="muted">勾选项就是实际入书字段。模板默认重置动态与无法分类的属性；这里明确勾选可覆盖默认，包括自定义字段。未选字段仍可在原作证据中查看。</p><div className="source-options">{keys.map(key=><label key={key}><input type="checkbox" checked={fields.includes(key)} onChange={e=>onChange({selection:{...spec.selection,[a.id]:{mode:spec.selection[a.id]?.mode??'main',fields:e.target.checked?[...fields,key]:fields.filter((f:string)=>f!==key)}}})}/>{a.kind==='relationship'&&key==='type'?'关系类型':key==='state'?'条目状态':fieldLabels[key]??key}：{String(a.fields[key])}</label>)}</div>{Object.values(a.refs).flat().map((ref:any)=><Field key={ref} label={`关联依赖 ${ref}`}><select value={spec.dependencies[`${a.id}:${ref}`]?.action??'background'} onChange={e=>onChange({dependencies:{...spec.dependencies,[`${a.id}:${ref}`]:{action:e.target.value}}})}><option value="background">补入最小背景引用</option><option value="include">一并继承完整资料</option><option value="drop">不继承此关联条目</option><option value="replace">替换为另一个允许实体</option></select>{spec.dependencies[`${a.id}:${ref}`]?.action==='replace'&&<input aria-label="替代实体素材ID" placeholder="从素材详情复制允许范围内的素材 ID" value={spec.dependencies[`${a.id}:${ref}`]?.replacement??''} onChange={e=>onChange({dependencies:{...spec.dependencies,[`${a.id}:${ref}`]:{action:'replace',replacement:e.target.value}}})}/>}</Field>)}<p className="muted">素材 ID：{a.id}</p>
 <details open><summary>{a.evidence.length} 处来源证据 · 揭露位置与故事时间分开</summary>{a.evidence.map((e:any,n:number)=><div className="note-card" key={n}><blockquote>{e.quote}</blockquote><p className="muted">第 {e.ordinal} 个目录项 · 故事时间 {e.storyTime} · {e.modality}{e.inference?' / 推断':''} · UTF-16 {e.start}–{e.end}</p><button onClick={()=>onRead(e.chapterId,e.start,e.end)}>打开原文</button></div>)}</details>
 <details><summary>消歧与归并 · 人工决定有独立版本</summary><Field label="可用名称"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="有证据的身份"><input value={identity} onChange={e=>setIdentity(e.target.value)}/></Field><p className="muted">此处按证据校正解析；原文不变。同人有意改动请使用下方改编覆盖。</p><Field label="确认结构字段（不改原文）"><textarea value={fieldsText} onChange={e=>setFieldsText(e.target.value)}/></Field><Field label="确认关联（当前范围的素材 ID）"><textarea value={refText} onChange={e=>setRefText(e.target.value)}/></Field><Field label="决定依据"><input value={reason} onChange={e=>setReason(e.target.value)}/></Field><button disabled={!reason} onClick={()=>void perform(()=>onDecision({assetId:a.id,action:'resolve',ordinal:run.run.cutoff,reason,patch:{name,identity,refs:JSON.parse(refText),fields:JSON.parse(fieldsText)}}))}>确认独立身份 / 关联</button><Field label="合并目标素材 ID"><input value={target} onChange={e=>setTarget(e.target.value)}/></Field><button disabled={!reason||!target} onClick={()=>void perform(()=>onDecision({assetId:a.id,action:'merge',targetId:target,ordinal:run.run.cutoff,reason}))}>按本截止点证据合并</button><details><summary>按证据拆分同名实体</summary><p className="muted">上方名称与身份用于新实体。选择移出的证据，至少为原实体保留一条。混合属性被清空；已有关系需重新确认。</p>{a.evidence.map((e:any,n:number)=><label className="source-consent" key={n}><input type="checkbox" checked={splitStarts.includes(e.start)} onChange={ev=>setSplitStarts(ev.target.checked?[...splitStarts,e.start]:splitStarts.filter(start=>start!==e.start))}/>{e.start} · {e.quote}</label>)}<button disabled={!reason||!identity||!splitStarts.length} onClick={()=>void perform(()=>onDecision({assetId:a.id,action:'split',ordinal:run.run.cutoff,reason,patch:{name,identity},evidenceStarts:splitStarts}))}>保存身份拆分</button></details><details><summary>人工决定历史 / 撤销</summary>{decisions.filter(d=>d.assetId===a.id||d.targetId===a.id||d.splitId===a.id).map(d=><p key={d.id}>{d.action} · 目录 {d.ordinal} · {d.reason}{d.action!=='undo'&&!decisions.some(x=>x.decisionId===d.id)&&<button disabled={!reason} onClick={()=>void perform(()=>onDecision({assetId:a.id,action:'undo',decisionId:d.id,ordinal:run.run.cutoff,reason}))}>登记撤销</button>}</p>)}</details></details>
 <details><summary>声明本书改编覆盖</summary><div className="form-grid"><Field label="改编属性"><input placeholder="health / state / identity …" value={property} onChange={e=>setProperty(e.target.value)}/></Field><Field label="本书有效值"><input value={value} onChange={e=>setValue(e.target.value)}/></Field></div><Field label="改编原因 / 影响"><textarea rows={2} value={reason} onChange={e=>setReason(e.target.value)}/></Field><label><input type="checkbox" checked={retcon} onChange={e=>setRetcon(e.target.checked)}/>明确回溯改编前缀中的已发生事件，保留原证据而不假造原文</label><button disabled={!property||!value||!reason} onClick={()=>{onChange({overrides:[...spec.overrides,{entityId:a.id,property,value,reason,retcon}]});onClose();}}>加入覆盖清单</button></details>{spec.overrides.filter((o:any)=>o.entityId===a.id).map((o:any,n:number)=><p className="notice" key={n}>{o.property} → {o.value} · {o.reason}<button onClick={()=>onChange({overrides:spec.overrides.filter((x:any)=>x!==o)})}>移除</button></p>)}{a.profile&&<details open><summary>深入档案 · {a.profile.accepted?'作者已接受':'待审阅'}</summary><pre>{JSON.stringify(a.profile,null,2)}</pre>{!a.profile.accepted&&<button onClick={()=>void perform(()=>onDecision({assetId:a.id,action:'accept-profile',ordinal:run.run.cutoff,reason:'作者审阅并接受此角色档案'}))}>接受有证据档案</button>}</details>}{a.kind==='character'&&<button onClick={()=>void perform(onProfile)}>补充所选角色档案 · 最多 3 次调用</button>}
 </Modal>;
}

export function InheritanceView({project,objects,onClose,onNavigate}:{project:Project;objects:any[];onClose:()=>void;onNavigate:(id:string)=>void}){
 const [data,setData]=useState<any>(),[error,setError]=useState(''),[q,setQ]=useState(''),[offset,setOffset]=useState(0);const filtered=objects.filter(o=>['character','world','relationship','fact','event','foreshadow'].includes(o.kind)&&`${o.title} ${JSON.stringify(o.fields)}`.includes(q));useEffect(()=>{void api(`/projects/${project.id}/source-baseline`).then(setData).catch(e=>setError(e.message));},[project.id]);
 return <Modal title="本书继承与改编" wide onClose={onClose}>{error&&<p className="notice error">{error}</p>}<p>{project.lineage?.sourceTitle} · {project.lineage?.author} · 来源版本 {project.lineage?.versionId}</p><pre>{project.lineage?.contract}</pre><input aria-label="搜索本书继承资料" placeholder="搜索名称或改编属性" value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/>{filtered.slice(offset,offset+40).map(o=><details key={o.id}><summary>{o.title} <span className="badge">{o.fields.backgroundReference?'背景引用':o.source?.provenance==='adaptation'?'作者改编':o.source?.provenance==='baseline'?'原作继承':'本书新增'}</span> <span className="badge">{statusText[o.status]??o.status}</span></summary><p className="muted">{o.source?.fromChapter?`生效自目录 ${o.source.fromChapter} · `:''}{o.source?.versionId?'正文版本 '+o.source.versionId:''}</p><p>{o.body}</p><button onClick={()=>onNavigate(o.id)}>在工作台查看</button>{data?.assets.find((a:any)=>a.id===o.source?.sourceAssetId)?.evidence.map((e:any,n:number)=><blockquote key={n}>{e.quote}<small> · 原作目录 {e.ordinal}，来源 {e.versionId}</small></blockquote>)}</details>)}<div className="inline-actions"><span>{filtered.length} 项 · {offset+1}–{Math.min(offset+40,filtered.length)}</span><button disabled={!offset} onClick={()=>setOffset(offset-40)}>上一页</button><button disabled={offset+40>=filtered.length} onClick={()=>setOffset(offset+40)}>下一页</button></div><p className="muted">同时展示历史记录和当前记录；已撤销内容不再进入当前正式状态。原作引文读取激活时的证据快照。修改本书角色不会改写原作或其他分支；资料库新版本也不会自动改变本书。</p></Modal>;
}

function SourceGraphView({runId,cutoff,onClose,onSelect}:any){
 const [q,setQ]=useState(''),[type,setType]=useState(''),[data,setData]=useState<any>(),[error,setError]=useState('');
 useEffect(()=>{let live=true;void api(`/source-runs/${runId}/graph?cutoff=${cutoff}&q=${encodeURIComponent(q)}&type=${encodeURIComponent(type)}`).then(r=>{if(live){setData(r);setError('');}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[runId,cutoff,q,type]);
 const object=(a:any)=>({id:a.id,projectId:'source-view',revision:a.revision,kind:a.kind,title:a.name,body:a.description,fields:{...a.fields,...a.refs},tags:[],order:0,parentId:null,status:'candidate' as const,locked:true,updatedAt:''});
 return <Modal title="原作关系 · 截止点视图" wide onClose={onClose}><div className="form-grid"><Field label="定位角色 / 别名"><input value={q} onChange={e=>setQ(e.target.value)}/></Field><Field label="筛选关系类型"><input value={type} onChange={e=>setType(e.target.value)}/></Field></div>{error&&<p className="notice error">{error}</p>}{data&&<><p className="muted">截至目录 {data.cutoff} · {data.characters.length}/{data.total} 个角色 · 另有 {data.omitted} 个关联节点因局部预算省略。箭头表示方向，布局距离不代表强弱。</p><RelationshipGraph center={data.center} characters={data.characters.map(object)} relations={data.relations.map(object)} onSelect={o=>onSelect([...data.characters,...data.relations].find((a:any)=>a.id===o.id))}/></>}</Modal>;
}
