import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const directory='docs/novel-studio/evidence/';
const read=name=>readFile(directory+name,'utf8').then(JSON.parse);
const sha=value=>createHash('sha256').update(value).digest('hex');
const api=async(port,path)=>{const response=await fetch(`http://127.0.0.1:${port}/api/novel-studio${path}`,{signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error(`Read ${path}: HTTP ${response.status}`);return response.json();};
const original=await read('source-backup-receipt.json'),oldProjects=[];
for(const before of original.checks){const after=await api(before.port,`/projects/${before.id}/backup`);oldProjects.push({...before,afterChecksum:after.checksum,status:after.checksum===before.checksum?'PASS':'FAIL'});}
const runtime=await read('source-final-runtime.json'),real=await read('source-real.json'),browser=await read('source-browser.json'),scale=await read('source-scale.json');
const tests=[];
for(const type of ['unit','integration','e2e']){const file=`source-test-${type}.txt`,text=await readFile(directory+file,'utf8'),pass=Number(text.match(/ℹ pass (\d+)/)?.[1]),fail=Number(text.match(/ℹ fail (\d+)/)?.[1]);tests.push({type,file,pass,fail,status:Number.isFinite(pass)&&pass>0&&fail===0&&/ℹ skipped 0/.test(text)&&/ℹ cancelled 0/.test(text)?'PASS':'FAIL'});}
const current=await api(4318,`/projects/${real.projectId}`),memory=await api(4318,`/projects/${real.projectId}/memories`);
const source=await api(4318,`/source-versions/${real.versionId}`),run=await api(4318,`/source-runs/${real.runId}`);
const finalText=real.branch.chapters.map(c=>{const live=current.objects.find(o=>o.id===c.id);return {id:c.id,version:live?.fields.currentVersion,words:c.words,hash:sha(live?.body??''),status:live?.fields.currentVersion===c.currentVersion&&sha(live.body)===c.contentHash&&live.fields.summaryVersion===live.fields.currentVersion&&!live.fields.extractionPending?'PASS':'FAIL'};});
const images=[];for(const s of browser.screenshots)images.push({file:s.file,status:sha(await readFile(directory+s.file))===s.sha256&&s.visuallyInspected?'PASS':'FAIL'});
const checks=[...tests,...oldProjects,...finalText,...images,{type:'restart',status:runtime.status},{type:'browser',status:browser.status},{type:'real-model',status:real.status},{type:'scale-metadata-only',status:scale.status},{type:'memory',status:memory.gaps.length===0&&memory.covered===2?'PASS':'FAIL'},{type:'source-read-only',status:source.raw===await readFile('test/fixtures/source-real.md','utf8')?'PASS':'FAIL'},{type:'source-complete',status:run.task.status==='COMPLETED'&&run.covered===run.segments?'PASS':'FAIL'}];
const result={at:new Date().toISOString(),status:checks.every(c=>c.status==='PASS')?'PASS':'FAIL',tests,oldProjects,finalText,images,checks:checks.filter(c=>c.type&&!tests.includes(c)),runtime:'source-final-runtime.json',cache:real.cache,sourceModel:run.task.usage,fixture:'60 chapters/64 roles through HTTP+deterministic extraction; real24 roles separately; scale1000 direct metadata only',servicePorts:{dsh:4318,local:4317,unrelatedUntouched:3080},failedDevelopmentPaths:['Structured review citations and closing delimiters preserved in request records.','Budget stops kept progress; explicit grants did not reset usage.','Verifier initially tried a forbidden generic backup of the source workspace (403); corrected to source-specific read APIs.','Virtualized editor automation partial edit recovered via visible version history; final full text verified.'],unfinished:[],externalBlockers:[]};
await writeFile(directory+'source-final.json',JSON.stringify(result,null,2));console.log(JSON.stringify({status:result.status,tests,oldProjects:oldProjects.length,sourceRecords:runtime.sourceChecks.length,finalText,images:images.length},null,2));if(result.status!=='PASS')process.exitCode=1;
