import { chromium } from 'playwright';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const port=Number(process.argv[2]??4323);
if(!Number.isInteger(port)||port<1024||port>65535)throw new Error('Use an isolated local test port');
const base=`http://127.0.0.1:${port}`;
const browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'});
const checks=[],errors=[];
const record=(name,detail)=>checks.push({name,status:'PASS',detail});
try{
  const context=await browser.newContext({viewport:{width:1280,height:800},deviceScaleFactor:1});
  const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
  const shelf=await page.request.get(base+'/api/novel-studio/shelf');if(!shelf.ok())throw new Error('Isolated server missing /shelf');
  let projects=await shelf.json();
  if(!projects.some(p=>!p.archived)){
    const created=await page.request.post(base+'/api/novel-studio/projects',{headers:{'X-Novel-Studio':'1'},data:{title:'Stage 3 browser fixture — a long harbor title to check truncation',premise:'A quiet harbor and a missing letter.'}});
    if(!created.ok())throw new Error('Could not create isolated browser fixture');projects=await (await page.request.get(base+'/api/novel-studio/shelf')).json();
  }
  const project=projects.find(p=>!p.archived);
  await page.goto(base+'/novel-studio/');await page.getByRole('heading',{name:'作品书架',exact:true}).waitFor();
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth);
  if(overflow>1)throw new Error(`Desktop shelf horizontal overflow ${overflow}px`);
  await page.screenshot({path:resolve('docs/novel-studio/evidence/stage3-shelf-desktop.png')});
  record('desktop shelf',`1280x800, project ${project.id}, overflow ${overflow}px`);
  await page.getByRole('button',{name:'列表'}).click();
  if(await page.locator('.shelf-cards.list').count()!==1)throw new Error('List view did not activate');
  await page.getByRole('button',{name:'网格'}).click();
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScL/nwAAAABJRU5ErkJggg==','base64');
  await page.getByLabel(`${project.title}上传封面`).setInputFiles({name:'cover.png',mimeType:'image/png',buffer:png});
  await page.getByRole('img',{name:`${project.title}的封面`}).waitFor();
  await page.getByRole('button',{name:'移除封面'}).click();
  await page.getByRole('img',{name:`${project.title}的封面`}).waitFor({state:'detached'});
  record('shelf controls','Grid/list switch and cover upload/remove round trip through real HTTP');
  await page.getByRole('button',{name:'原作资料',exact:true}).click();
  const heading=page.getByRole('heading',{name:'原作资料库 · 从已有作品创作'});await heading.waitFor();
  const top=(await heading.boundingBox())?.y??-1;
  if(top<100)throw new Error(`Source heading hidden by sticky navigation at ${top}px`);
  await page.screenshot({path:resolve('docs/novel-studio/evidence/stage3-source-desktop.png')});
  record('global source library',`Existing source workflow embedded, heading y=${top}px`);
  await page.getByRole('button',{name:'创作资产',exact:true}).first().click();
  await page.getByRole('heading',{name:'创作资产',exact:true}).waitFor();
  await page.getByText('实际生效的全局规则').waitFor();
  await page.screenshot({path:resolve('docs/novel-studio/evidence/stage3-assets-desktop.png')});
  record('projectless creative assets','Effective global binding and version panel available without a project');
  await page.getByRole('button',{name:'作品书架',exact:true}).click();
  await page.getByRole('button',{name:`打开${project.title}`}).click();
  await page.getByRole('button',{name:'导演模式',exact:true}).click();
  await page.reload();await page.getByRole('button',{name:'导演模式',exact:true}).waitFor();
  if(!page.url().includes(`project=${project.id}`))throw new Error('Project deep-link did not survive refresh');
  if(!(await page.getByText('新的导演会话').count())&&!(await page.getByText('创作任务').count()))throw new Error('Director session did not restore');
  record('project position',`Director and project ${project.id} restored after reload`);
  await page.getByRole('button',{name:'返回书架'}).first().click();
  if(page.url().includes('project='))throw new Error('Shelf return did not clear project deep-link');
  await page.getByRole('heading',{name:'作品书架',exact:true}).waitFor();
  record('project navigation','Director to global shelf clears project URL without new task');
  await page.setViewportSize({width:390,height:844});
  const narrowOverflow=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth);
  if(narrowOverflow>1)throw new Error(`Narrow shelf horizontal overflow ${narrowOverflow}px`);
  await page.screenshot({path:resolve('docs/novel-studio/evidence/stage3-shelf-narrow.png')});
  record('narrow shelf',`390x844, overflow ${narrowOverflow}px`);
  await page.getByRole('button',{name:'创作资产',exact:true}).first().click();
  const assetOverflow=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth);
  if(assetOverflow>1)throw new Error(`Narrow assets horizontal overflow ${assetOverflow}px`);
  await page.screenshot({path:resolve('docs/novel-studio/evidence/stage3-assets-narrow.png')});
  record('narrow assets',`390x844, overflow ${assetOverflow}px`);
  await page.getByRole('button',{name:'切换深色'}).click();
  if(await page.locator('html').getAttribute('data-theme')!=='dark')throw new Error('Dark theme failed');
  record('dark theme','Global assets remain operable in dark theme');
  if(errors.length)throw new Error(`Browser errors: ${errors.join(' | ')}`);
  await context.close();
  const receipt={at:new Date().toISOString(),status:'PASS',server:base,browser:'Chrome headless via Playwright',checks,errors};
  writeFileSync('docs/novel-studio/evidence/stage3-browser.json',JSON.stringify(receipt,null,2));
  console.log(JSON.stringify({status:receipt.status,checks,errors},null,2));
}finally{await browser.close();}
