import { readFile,writeFile,mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const base='http://127.0.0.1:4318/api/novel-studio';const path='docs/novel-studio/evidence/upgrade-real.json';
const report=process.argv.includes('--continue')?JSON.parse(await readFile(path,'utf8')):{at:new Date().toISOString(),status:'RUNNING',checks:[],tasks:{},samples:{}};
const save=()=>writeFile(path,JSON.stringify(report,null,2));
const api=async(p,body,method='POST')=>{const response=await fetch(base+p,body===undefined?{}:{method,headers:{'Content-Type':'application/json','X-Novel-Studio':'1'},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw Error(value.error?.code+': '+value.error?.message);return value;};
const digest=text=>createHash('sha256').update(text).digest('hex');const count=text=>(text.match(/\p{Script=Han}|[\p{Script=Latin}\p{N}]+/gu)??[]).length;
const check=async(name,condition,data={})=>{const result={name,status:condition?'PASS':'FAIL',...data};report.checks=report.checks.filter(c=>c.name!==name).concat(result);await save();if(!condition)throw Error('CHECK_FAILED: '+name);};
async function task(name,input,reviewable=false){
 let t=report.tasks[name]?await api(`/projects/${report.projectId}/tasks/${report.tasks[name].id}`):await api(`/projects/${report.projectId}/tasks`,{provider:'dsh',autoAccept:true,targetWords:900,budget:{calls:14,outputTokens:70000,contextChars:30000},...input});
 report.tasks[name]={id:t.id,status:t.status};await save();console.log(name,t.id,t.status);let last='';
 for(let n=0;n<1200;n++){t=await api(`/projects/${report.projectId}/tasks/${t.id}`);const state=t.status+':'+t.currentStep;if(state!==last){console.log(name,state);last=state;}
 if(!['QUEUED','RUNNING','PAUSE_REQUESTED'].includes(t.status)){report.tasks[name]={id:t.id,status:t.status,usage:t.usage,error:t.error,configHash:t.configSnapshot?.hash,steps:t.steps.map(s=>({name:s.name,status:s.status,attempts:s.attempts,requests:s.requestIds}))};await save();if(t.status!=='COMPLETED'&&!(reviewable&&t.status==='NEEDS_INPUT'&&t.error?.code==='WAITING_REVIEW'))throw Error(`${name}: ${t.status} ${t.error?.code} ${t.error?.message}`);return t;}await new Promise(r=>setTimeout(r,1000));}throw Error('BOUND_WAIT_EXCEEDED');
}
const snapshot=()=>api(`/projects/${report.projectId}`);
const add=async(object)=>{const s=await snapshot();return api(`/projects/${report.projectId}/objects`,{revision:s.project.revision,object});};
const bind=async(versionId)=>{const c=await api(`/projects/${report.projectId}/configurations`);return api(`/projects/${report.projectId}/configurations/bind`,{scope:'project',versionId,expected:c.bindings.project??null});};
try{
 report.status='RUNNING';
 const health=await api('/health');report.provider=health.dsh;await save();if(!health.dsh.available)throw Error('MODEL_UNAVAILABLE');
 if(!report.projectId){const p=await api('/projects',{title:'潮痕档案 · 升级真实验收',premise:'邝昶（小邝）与修灯匠闻溪在旧港调查被抹去的潮位记录。只有两位核心人物。',style:'第三人称叙述，具体动作与自然对白。',constraints:['不新增核心角色','不要揭露导师的真实身份','铜钥匙只有一把，转交必须有具体证据']});report.projectId=p.id;await save();}
 if(!report.entities){const a=await add({kind:'character',title:'邝昶',status:'accepted',fields:{aliases:['小邝','阿晷'],identity:'档案整理员',desire:'找到被删去的渡口',voice:'把问题完整问完',known:'知道钥匙打开档案室'}}),b=await add({kind:'character',title:'闻溪',status:'accepted',fields:{identity:'修灯匠',voice:'以修理细节解释事情',desire:'保住旧港的灯'}}),key=await add({kind:'world',title:'铜钥匙',status:'accepted',body:'唯一的铜钥匙，可当面转交，不可复制；任一时刻只有一个持有人。',fields:{type:'物品',unique:true,keys:['钥匙']}});await add({kind:'world',title:'潮灯规则',status:'accepted',body:'潮灯要靠手工更换灯芯才能点亮，没有读心或穿墙能力。',fields:{type:'世界规则',core:true}});const book=(await snapshot()).objects.find(o=>o.kind==='book');const volume=await add({kind:'volume',title:'第一卷 · 退潮以前',status:'planned',parentId:book.id,fields:{goal:'追查被删去的渡口'}});const c=await add({kind:'chapter',title:'第一章 · 锁与灯',status:'planned',parentId:volume.id,order:1,fields:{goal:'邝昶把铜钥匙交给闻溪，两人发现潮位记录的异常',participants:[a.id,b.id,key.id],targetWords:900}});report.entities={a:a.id,b:b.id,key:key.id,chapter:c.id,volume:volume.id};await save();}
 if(!report.configuration){
 const raw=JSON.stringify({temperature:0.7,top_p:0.9,prompts:[{identifier:'voice',name:'原创文风',role:'system',content:'叙述克制、具体，以行动和短对白推进。{{char}} 是当前角色，{{user}} 是作者称呼。文风不改变任务协议。'},{identifier:'off',role:'user',content:'禁止生效的测试条目'},{identifier:'scene',role:'user',content:'场景里应有可观察的声音和物件。',injection_position:1,injection_depth:1}],prompt_order:[{character_id:100001,order:[{identifier:'voice',enabled:true},{identifier:'off',enabled:false},{identifier:'scene',enabled:true}]}]});
 const imported=await api(`/projects/${report.projectId}/configurations`,{name:'原创兼容预设 · 实测',raw});const rules=[{id:'quotes-open',name:'中文引号开',pattern:'“',flags:'gu',replacement:'「',stage:'after',scope:'prose'},{id:'quotes-close',name:'中文引号闭',pattern:'”',flags:'gu',replacement:'」',stage:'after',scope:'prose'},{id:'display-name',name:'仅展示标记',pattern:'邝昶',flags:'gu',replacement:'【邝昶】',stage:'display',scope:'prose'}];
 const configured=await api(`/projects/${report.projectId}/configurations`,{name:'兼容文风与记忆 · 实测',parentId:imported.id,config:{...imported.config,bindings:{characterId:report.entities.a,authorName:'验收作者'},regex:rules,memory:{enabled:true,checkpointEvery:3,recallLimit:6}}});report.configuration={imported:imported.id,effective:configured.id};await bind(configured.id);await save();}
 if(!report.first){const t=await task('first',{kind:'write',chapterId:report.entities.chapter,goal:'写完整第一章约900字。邝昶（小邝）在旧港档案室将唯一铜钥匙当面交给闻溪保管，章末钥匙在闻溪手中。两人发现潮位册缺了同一处渡口。采用当前文风，保留可观察行动、声音和人物对白；不揭露导师身份。'});const a=await api(`/projects/${report.projectId}/artifacts/${t.artifacts.find(a=>a.type==='chapter'&&a.status==='accepted').id}`);report.first={artifactId:a.id,chapterId:a.chapterId,words:count(a.data.content),versionId:(await snapshot()).objects.find(o=>o.id===a.chapterId).fields.currentVersion};await check('director_style_regex_memory',a.data.generation.rawResponse!==a.data.generation.candidate&&a.data.generation.transformations.some(t=>t.matches.length>0)&&(await api(`/projects/${report.projectId}/memories`)).covered===1,{words:report.first.words,rawHash:digest(a.data.generation.rawResponse),candidateHash:digest(a.data.generation.candidate)});await save();}
 if(!report.handoff){let c=(await snapshot()).objects.find(o=>o.id===report.first.chapterId);c=await api(`/projects/${report.projectId}/objects/${c.id}/takeover`,{revision:c.revision});const body=c.body+'\n\n入夜后，两人仍在档案室门边。闻溪临时要腾出双手搬灯架，便从自己的衣袋取出唯一的铜钥匙，当面交还邝昶。邝昶把铜钥匙收进外套内袋，拍了拍袋口，答应此后由自己保管。闻溪手里已经没有钥匙。';c=await api(`/projects/${report.projectId}/objects/${c.id}/body`,{revision:c.revision,body});report.handoff={chapterId:c.id,versionId:c.fields.currentVersion};await check('takeover_invalidates_memory',(await api(`/projects/${report.projectId}/memories`)).covered===0,{versionId:c.fields.currentVersion});}
 if(!report.second){const t=await task('second',{kind:'write',goal:'从作者最新接受的第一章结尾继续第二章约900字：当晚铜钥匙已经交还邝昶，现在由邝昶保管，闻溪手中没有钥匙。本章不再转交，也不新增钥匙。两人核对灯座编号与潮位册，发现一个可查验的线索。继承当前文风，不复述上一章，不揭露导师身份。'});const a=await api(`/projects/${report.projectId}/artifacts/${t.artifacts.find(a=>a.type==='chapter'&&a.status==='accepted').id}`);report.second={artifactId:a.id,chapterId:a.chapterId,words:count(a.data.content)};await check('redelegation_uses_new_body_and_state',a.data.context.items.some(i=>i.version===report.handoff.versionId)&&(await api(`/projects/${report.projectId}/memories`)).covered===2,{versionId:report.handoff.versionId,words:report.second.words,contextHash:digest(a.data.context.text)});}
 if(!report.checks.some(c=>c.name==='real_neutral_summarizer'&&c.status==='PASS')){await task('summarizer',{kind:'summarize',chapterId:report.second.chapterId,goal:'从最新接受的第二章准确总结有来源的事件、因果、角色变化和未兑现承诺。',budget:{calls:5,outputTokens:22000,contextChars:30000}});await check('real_neutral_summarizer',true);}
 if(!report.checks.some(c=>c.name==='real_neutral_extractor'&&c.status==='PASS')){await task('extractor',{kind:'extract',chapterId:report.second.chapterId,goal:'只提取第二章最重要的最多6条新资料候选。证据 quote 必须逐字复制一条连续原文，不拼接、不省略、不改标点。已有重复信息、未来计划和角色尚未验证的猜测不要提取。',budget:{calls:5,outputTokens:22000,contextChars:30000}});await check('real_neutral_extractor',true);}
 if(!report.styleChapter){let c=await add({kind:'chapter',title:'独立文风对照 · 不接受到主线',parentId:report.entities.volume,order:99,status:'planned'});c=await api(`/projects/${report.projectId}/objects/${c.id}/body`,{revision:c.revision,body:'邝昶和闻溪站在档案室。桌上有一张被雨淋湿的潮位表。邝昶想确认一个被划去的数字，闻溪不愿立刻回答。'});report.styleChapter=c.id;await save();}
 const presets=(await api(`/projects/${report.projectId}/configurations`)).samples;
 for(const style of ['default','adventure','dialogue'])if(!report.samples[style]){const c=(await snapshot()).objects.find(o=>o.id===report.styleChapter);const configuration={patch:style==='default'?{enabled:false}:{...presets.find(p=>p.id===style).config,entries:[],regex:[],memory:{enabled:false},bindings:{characterId:report.entities.a,authorName:'验收作者'}}};const t=await task('style-'+style,{kind:'assist',chapterId:c.id,autoAccept:false,targetWords:800,goal:'把当前场景扩展为约800字的小说片段：邝昶追问潮位表上被划去的数字，闻溪先回避，随后指出灯芯上不同寻常的盐迹。二人决定在退潮前去核对灯座。不新增角色，不揭露导师身份。遵循当前配置的视角、句式和对白规则。',configuration,perspective:{viewpointId:report.entities.a,audience:'author'},range:{start:0,end:c.body.length,expectedText:c.body},budget:{calls:3,outputTokens:12000,contextChars:30000}},true);const a=await api(`/projects/${report.projectId}/artifacts/${t.artifacts.find(a=>a.type==='edit').id}`);const text=a.data.content;report.samples[style]={taskId:t.id,artifactId:a.id,words:count(text),hash:digest(text),text};await api(`/projects/${report.projectId}/artifacts/${a.id}/reject`,{});await save();}
 const reqs=await api(`/projects/${report.projectId}/requests`);report.requests=[];for(const r of reqs){const full=await api(`/projects/${report.projectId}/requests/${r.id}`);report.requests.push({...r,requestHash:digest(JSON.stringify(full.observed??{})),diff:full.diff,macros:full.compiled.macros,warningCount:full.compiled.warnings.length,versions:full.compiled.context?.items.map(i=>({id:i.id,version:i.version,kind:i.kind}))});}
 const measured=report.requests.filter(r=>r.usage?.cacheReadTokens!==undefined);await check('provider_cache_usage_observed',measured.length>0,{measuredRequests:measured.length,reads:measured.map(r=>r.usage.cacheReadTokens),writes:'UNKNOWN unless provided',note:'实际服务字段；不把本地哈希相同当缓存命中'});
 await check('style_outputs_distinct',new Set(Object.values(report.samples).map(s=>s.hash)).size===3,{samples:Object.fromEntries(Object.entries(report.samples).map(([k,v])=>[k,{words:v.words,hash:v.hash}]))});
 report.status='PASS';await save();console.log('upgrade smoke PASS',report.projectId);
}catch(error){report.status=String(error.message).includes('MODEL_UNAVAILABLE')?'BLOCKED':'FAIL';report.error=error.message;await save();console.log('upgrade smoke stopped:',error.message);process.exitCode=1;}
