import type { Domain } from './domain.js';
import { sourceGet,sourcePut,sourceList,assetsAt,boundaryOf } from './sources.js';
import { manifestSchema,type ImportManifest,type SourceAsset,type AdaptationSpec } from './source-contracts.js';
import { id,now,requireThat,projectSchema,type Project,type Source,type StoryObject,type ChapterVersion } from './contracts.js';
import { hash } from './store.js';
import { bindConfig,configVersion } from './config.js';
const staticCharacter=new Set(['identity','appearance','voice','desire','fear','boundaries','weakness','personality','group','organization','aliases']);
const dynamic=new Set(['location','health','holder','inventory','known','secret','level','marriage','death','status','arc','background','abilities','goal','growth']);
export function previewInheritance(domain:Domain,input:unknown){
 const raw=input as any;const spec=manifestSchema.parse({...raw,...(raw.mode==='independent'?{inheritPrefix:raw.inheritPrefix??false,inheritDynamics:raw.inheritDynamics??false,inheritPlot:raw.inheritPlot??false,categories:raw.categories??['character','world']}: {})});
 if(spec.configurationVersionId)requireThat(configVersion(domain.store,spec.configurationVersionId).applicable,'CONFIG_UNSUPPORTED','所选文风仅支持保留，不能启用');if(spec.inheritStyle)requireThat(spec.configurationVersionId,'STYLE_SELECTION','请选择明确的创作配置版本，不从原作推测作者文风');
 const version=sourceGet(domain.store,'source_versions',spec.versionId),run=sourceGet(domain.store,'source_runs',spec.runId);requireThat(run.versionId===version.id,'SOURCE_SCOPE','分析和来源版本不一致');const scope=boundaryOf(version,spec.boundary);requireThat(scope.cutoff<=run.cutoff,'SOURCE_SCOPE','分析截止点未覆盖所选位置');
 const chapters=new Set(scope.chapters.map(c=>c.id));const gaps=run.segments.filter(s=>chapters.has(s.chapterId)&&!['complete','split'].includes(s.state));
 const assets=assetsAt(domain,run.id,scope.cutoff),byId=new Map(assets.map(a=>[a.id,a]));const selected=new Map<string,{asset:SourceAsset;mode:'main'|'background';reason:string}>();const excluded:string[]=[],pending:{id:string;message:string}[]=[],conflicts:{id:string;message:string;code:string}[]=[],dropped:string[]=[];
 for(const key of Object.keys(spec.selection))requireThat(byId.has(key),'SOURCE_SELECTION','选择含截止范围外或过期素材');
 for(const a of assets){const choice=spec.selection[a.id];const allowed=spec.categories.includes(a.kind)&&(spec.inheritPlot||!['fact','event','foreshadow'].includes(a.kind));const mode=choice?.mode??(allowed?'main':'omit');
  if(mode==='exclude'){excluded.push(a.id);if(spec.inheritPrefix&&a.evidence.length&&!spec.overrides.some(o=>o.entityId===a.id&&o.retcon))conflicts.push({id:a.id,code:'HISTORY_EXCLUSION',message:`保留前缀中已出现「${a.name}」；明确排除此人不能等同于未加入角色管理。请前移分歧点、取消前缀继承或声明回溯改编。`});continue;}
  if(mode==='main'||mode==='background'){if(a.status!=='verified')pending.push({id:a.id,message:`${a.name}：${a.status==='ambiguous'?'同名/身份需要消歧':'引文存在但推断或不确定，不能自动当作正式事实'}`});else selected.set(a.id,{asset:a,mode,reason:choice?'作者选择':'推荐分类选择'});}
  else if(spec.inheritPrefix&&a.kind==='character')selected.set(a.id,{asset:a,mode:'background',reason:'保留前缀已出现的历史人物引用，不添加完整档案'});
 }
 // Resolve only the selected edges. Minimal references have no outward dependencies.
 for(const [sid,item] of [...selected]){if(item.mode==='background')continue;for(const ref of Object.values(item.asset.refs).flat()){
  if(selected.has(ref))continue;const target=byId.get(ref),decision=spec.dependencies[`${sid}:${ref}`]??spec.dependencies[sid];
  if(decision?.action==='drop'){selected.delete(sid);dropped.push(sid);break;}
  if(decision?.action==='replace'){requireThat(decision.replacement&&byId.has(decision.replacement),'DEPENDENCY','替代关联必须是允许范围内素材');if(!selected.has(decision.replacement))selected.set(decision.replacement,{asset:byId.get(decision.replacement)!,mode:'background',reason:`替代 ${item.asset.name} 的关联`});continue;}
  if(!target||excluded.includes(ref)){conflicts.push({id:sid,code:'DEPENDENCY',message:`「${item.asset.name}」依赖未解析或明确排除的实体；请选择丢弃或替代关联。`});continue;}
  selected.set(ref,{asset:target,mode:decision?.action==='include'?'main':'background',reason:`维持「${item.asset.name}」的${Object.keys(item.asset.refs).find(k=>[item.asset.refs[k]].flat().includes(ref))??'关联'}引用`});
 }}
 // Explicit include may have its own dependencies: ask, rather than unbounded closure.
 for(const [sid,item] of selected)if(item.mode==='main')for(const ref of Object.values(item.asset.refs).flat()){const decision=spec.dependencies[`${sid}:${ref}`]??spec.dependencies[sid];if(!selected.has(ref)&&decision?.action!=='replace')conflicts.push({id:sid,code:'DEPENDENCY',message:'完整补入的实体仍有未选择依赖；请显式选择背景引用或取消该关联。'});}
 for(const o of spec.overrides){requireThat(selected.has(o.entityId),'OVERRIDE','改编目标必须已选择');const a=byId.get(o.entityId)!;const prior=[a.fields[o.property],...assets.filter(f=>f.kind==='fact'&&f.refs.entityId===a.id&&f.fields.property===o.property).map(f=>f.fields.value)].filter(v=>v!==undefined);if(spec.template==='canonical')conflicts.push({id:a.id,code:'CANONICAL_OVERRIDE',message:'原作相容模板不改变继承事实；请选择指定分歧或平行设定。'});else if(spec.inheritPrefix&&prior.some(v=>String(v)!==o.value)&&!o.retcon)conflicts.push({id:a.id,code:'RETCON_REQUIRED',message:`「${a.name}」的${o.property}已在前缀中成立；前移分歧点或明确确认回溯改编及影响。`});}
 if(gaps.length&&!spec.allowGaps)conflicts.push({id:run.id,code:'COVERAGE_GAP',message:`还有${gaps.length}个片段未处理；可继续抽取，或明确接受带缺口启动。`});
 if(pending.length&&!spec.allowGaps)conflicts.push({id:run.id,code:'AMBIGUITY',message:'存在待消歧或未证实条目；先处理、排除，或明确带警告启动（不会接受这些结论）。'});
 const title=`${spec.mode==='continuation'?'接续':'改编'}基线：${scope.cutoff}处之前允许证据；${spec.template==='parallel'?'平行设定':spec.template==='divergent'?'指定分歧':'原作相容'}`;
 return {spec,version,run,scope,assets,selected:[...selected.values()],excluded,pending,conflicts,gaps,dropped,contract:[title,'后续原作、后期化名与完整结局不属于本书事实或必走大纲。','只以当前继承快照、作者改编与本书已接受正文判断一致性；不凭模型记忆补完官方设定。',...spec.overrides.map(o=>`作者明确改编：${byId.get(o.entityId)?.name} ${o.property}=${o.value}；${o.reason}${o.retcon?'（明确回溯改编，原文证据保留为旧历史）':''}`)].join('\n')};
}
export function saveManifest(domain:Domain,input:unknown,manifestId?:string,revision?:number){const preview=previewInheritance(domain,input);const old=manifestId?sourceGet(domain.store,'import_manifests',manifestId):undefined;requireThat(!old||old.status==='staging'&&old.revision===revision,'STALE','继承清单已更新或激活');const manifest:ImportManifest={id:old?.id??id('manifest'),workId:preview.version.workId,versionId:preview.version.id,revision:(old?.revision??0)+1,createdAt:old?.createdAt??now(),spec:preview.spec,analysisRevision:preview.run.revision,status:'staging',mapping:{}};sourcePut(domain.store,'import_manifests',manifest);return {manifest,preview};}
export function activateManifest(domain:Domain,manifestId:string,revision:number){
 const store=domain.store,m=sourceGet(store,'import_manifests',manifestId);if(m.status==='active')return domain.project(m.projectId!);requireThat(m.status==='staging'&&m.revision===revision,'STALE','继承清单已更新或取消');const preview=previewInheritance(domain,m.spec);requireThat(preview.run.revision===m.analysisRevision,'STALE','抽取结果已变化，请刷新继承预览并保存清单');requireThat(!preview.conflicts.length,'INHERITANCE_CONFLICT',preview.conflicts.map(c=>c.message).join('\n'),422);const sourceWork=sourceGet(store,'source_works',m.workId);
 return store.transaction(()=>{
  const p:Project={...projectSchema.parse({title:m.spec.title,premise:m.spec.goal}),id:id('project'),revision:1,createdAt:now(),updatedAt:now(),lineage:{workId:m.workId,versionId:m.versionId,manifestId:m.id,manifestRevision:m.revision,cutoff:preview.scope.cutoff,mode:m.spec.mode,template:m.spec.template,sourceTitle:sourceWork.title,author:sourceWork.author,origin:sourceWork.origin,rights:sourceWork.rights,contract:preview.contract}};store.put('projects',p);if(m.spec.configurationVersionId)bindConfig(store,'project:'+p.id,m.spec.configurationVersionId,null);
  const book=domain.addObject(p.id,{kind:'book',title:p.title,body:m.spec.goal,status:'planned'});const volumes=new Map<string,string>();
  if(m.spec.inheritPrefix)for(const c of preview.scope.chapters){let volume=volumes.get(c.volumeId);if(!volume){volume=domain.addObject(p.id,{kind:'volume',title:c.volumeTitle,parentId:book.id,order:volumes.size,status:'planned',locked:true,fields:{referenceOnly:true}}).id;volumes.set(c.volumeId,volume);}const body=preview.version.raw.slice(c.bodyStart,c.end);const o=domain.addObject(p.id,{kind:'chapter',title:c.title,body:body.slice(0,100000),parentId:volume,order:c.ordinal,status:'accepted',locked:true,fields:{referenceOnly:true,sourceChapterId:c.id,sourceVersionId:m.versionId,control:'reference'},source:{type:'import',sourceWorkId:m.workId,sourceVersionId:m.versionId,sourceChapterId:c.id,manifestId:m.id,provenance:'baseline',quote:'',start:c.bodyStart,end:c.end}});o.body=body;const v:ChapterVersion={id:id('version'),projectId:p.id,chapterId:o.id,content:body,chapterRevision:1,createdAt:now(),actor:'inherited-reference',accepted:true,summary:''};store.put('versions',v);o.fields.currentVersion=v.id;o.fields.extractionPending=false;store.put('objects',o);}
  const provenance=(a:SourceAsset):Source=>{const e=a.evidence[0];return {type:'import',quote:m.spec.inheritPrefix&&m.spec.inheritDynamics&&!m.spec.selection[a.id]?.fields?e.quote:'',start:e.start,end:e.end,time:e.storyTime,fromChapter:m.spec.inheritPrefix?e.ordinal:1,modality:e.modality,inference:e.inference,sourceWorkId:m.workId,sourceVersionId:m.versionId,sourceChapterId:e.chapterId,sourceAssetId:a.id,manifestId:m.id,provenance:'baseline',policy:a.manual?'author-resolved-inheritance':'evidence-inheritance'};};
  const fieldsFor=(a:SourceAsset,background=false)=>{if(background)return {backgroundReference:true,sourceKey:a.key};const allowed=m.spec.selection[a.id]?.fields;return Object.fromEntries(Object.entries(a.fields).filter(([key])=>(!allowed||allowed.includes(key))&&(m.spec.inheritDynamics||a.kind==='character'?m.spec.inheritDynamics||staticCharacter.has(key):!dynamic.has(key))));};
  const selected=preview.selected;const made=new Map<string,StoryObject>();
  for(const item of selected.filter(x=>['character','world'].includes(x.asset.kind))){const a=item.asset;const fields=fieldsFor(a,item.mode==='background');const o=domain.addObject(p.id,{kind:a.kind,title:a.name,body:item.mode==='background'?'原作历史背景引用':!m.spec.inheritDynamics?Object.entries(fields).map(([k,v])=>`${k}：${String(v)}`).join('；'):a.description,status:'accepted',fields:{...fields,sourceKey:a.key,inheritanceMode:item.mode},source:provenance(a)});m.mapping[a.id]=o.id;made.set(a.id,o);}
  const refsFor=(a:SourceAsset)=>Object.fromEntries(Object.entries(a.refs).map(([key,value])=>[key,Array.isArray(value)?value.map(v=>mapped(a.id,v)):mapped(a.id,value)]));
  const mapped=(sid:string,ref:string)=>{const d=m.spec.dependencies[`${sid}:${ref}`]??m.spec.dependencies[sid];const target=d?.action==='replace'?d.replacement!:ref;requireThat(m.mapping[target],'DEPENDENCY','激活时发现未解析引用，已回滚整个创建事务');return m.mapping[target];};
  for(const item of selected.filter(x=>!['character','world'].includes(x.asset.kind)).sort((a,b)=>['foreshadow','relationship','fact','event'].indexOf(a.asset.kind)-['foreshadow','relationship','fact','event'].indexOf(b.asset.kind))){const a=item.asset;if(item.mode==='background')continue;if(!m.spec.inheritDynamics&&a.kind==='fact'&&dynamic.has(String(a.fields.property)))continue;const refs=refsFor(a),o=domain.addObject(p.id,{kind:a.kind,title:a.name,body:a.description,status:'accepted',fields:{...fieldsFor(a),...refs,sourceKey:a.key},source:provenance(a)});m.mapping[a.id]=o.id;made.set(a.id,o);}
  for(const item of selected.filter(x=>['character','world'].includes(x.asset.kind)&&x.mode==='main')){const o=made.get(item.asset.id)!;const refs=refsFor(item.asset);if(refs.parentId){const parent=domain.object(p.id,String(refs.parentId));requireThat(parent.kind===o.kind,'DEPENDENCY','继承树上级类型不一致');o.parentId=parent.id;delete refs.parentId;}o.fields={...o.fields,...refs};store.put('objects',o);}
  for(const o of made.values()){const seen=new Set([o.id]);let parent=o.parentId;while(parent){requireThat(!seen.has(parent),'DEPENDENCY','继承树存在循环，创建已回滚');seen.add(parent);parent=domain.object(p.id,parent).parentId;}}
  for(const override of m.spec.overrides){const target=domain.object(p.id,m.mapping[override.entityId]);const before=structuredClone(target);target.fields[override.property]=override.value;target.body=`作者改编：${override.reason}；${override.property}=${override.value}。原始描述与证据保存在继承快照和变更记录中。`;target.revision++;target.source={type:'user',quote:override.reason,time:'本书开局',fromChapter:1,inference:false,modality:'objective',policy:'accepted-adaptation',provenance:'adaptation',manifestId:m.id,sourceWorkId:m.workId,sourceVersionId:m.versionId,sourceAssetId:override.entityId};store.put('objects',target);store.change(p.id,'adaptation.override',{before,after:target,reason:override.reason,retcon:override.retcon});for(const fact of store.objects(p.id,'fact').filter(f=>f.fields.entityId===target.id&&f.fields.property===override.property)){fact.status='revoked';store.put('objects',fact);}domain.addObject(p.id,{kind:'fact',title:`改编：${target.title} ${override.property}`,status:'accepted',body:override.reason,fields:{entityId:target.id,property:override.property,value:override.value},source:target.source});}
  const volume=domain.addObject(p.id,{kind:'volume',title:'本书 · 新的篇章',parentId:book.id,order:volumes.size+1,status:'planned'});domain.addObject(p.id,{kind:'chapter',title:`第${m.spec.inheritPrefix?preview.scope.chapters.length+1:1}章 · 新的起点`,parentId:volume.id,order:1,status:'planned',fields:{goal:m.spec.goal,targetWords:2000}});
  if(preview.gaps.length||preview.pending.length)domain.addObject(p.id,{kind:'idea',title:'继承准备缺口（作者明确带警告启动）',status:'candidate',body:`未处理${preview.gaps.length}段，未证实/歧义${preview.pending.length}项；不能编造缺失原作。`});
  m.status='active';m.projectId=p.id;sourcePut(store,'import_manifests',m);store.change(p.id,'source.activated',{manifestId:m.id,versionId:m.versionId,cutoff:preview.scope.cutoff,mapping:m.mapping,spec:m.spec,assets:selected.map(item=>item.mode==='background'?{...item.asset,description:'',fields:{},refs:{},profile:undefined}:item.asset),gaps:preview.gaps,contract:preview.contract});store.event(p.id,null,'source.activated','继承资料、映射、引用正文与索引在同一事务中就绪，可直接创作',{manifestId:m.id,sourceVersionId:m.versionId,selected:selected.length,background:selected.filter(s=>s.mode==='background').length});return p;
 });
}
