import type { Store } from './store.js';
import { id, now, requireThat, type CreativeTask } from './contracts.js';
import type { CompiledPrompt } from './compiler.js';
import { requestDiff } from './compiler.js';
import type { Transformation } from './text-pipeline.js';

export interface UsageRecord {uncachedInputTokens?:number;inputTokens?:number;outputTokens?:number;cacheReadTokens?:number;cacheWriteTokens?:number;totalTokens?:number;reasoningTokens?:number;serverCache:'REPORTED'|'UNKNOWN';firstTokenMs?:number;elapsedMs:number;}
export interface RequestSummary {id:string;projectId:string;taskId:string;stepKey:string;attempt:number;createdAt:string;status:'PREPARED'|'SENT'|'COMPLETED'|'FAILED'|'STALE';role:string;configHash:string;hash:string;stableHash:string;localCompilationCache:'HIT'|'MISS';localPrefixReuse?:boolean;usage?:UsageRecord;error?:{code:string;message:string};detailState:'available'|'cleared';detailBytes:number;clearedAt?:string;clearReason?:string;protectedReasons?:string[];}
export interface RequestDetail {compiled:CompiledPrompt;observed?:unknown;observedAt?:string;observedChars?:number;observedEstimatedTokens?:number;previousId?:string;diff?:ReturnType<typeof requestDiff>;rawResponse?:string;candidate?:string;syntaxRepair?:{removedTrailingClosers:number};transformations?:Transformation[];historical?:boolean;}
export interface RequestRecord extends Omit<RequestSummary,'role'|'configHash'|'hash'|'stableHash'|'localCompilationCache'|'detailState'|'detailBytes'>,RequestDetail {detailState?:'available';detailBytes?:number;}
export type StoredRequest=RequestSummary&Partial<RequestDetail>;
export const requestRetentionPolicy={detailLimit:100,summaryLimit:500,detailDays:90,summaryDays:365} as const;

function detailOf(record:RequestRecord):RequestDetail {return {compiled:record.compiled,observed:record.observed,observedAt:record.observedAt,observedChars:record.observedChars,observedEstimatedTokens:record.observedEstimatedTokens,previousId:record.previousId,diff:record.diff,rawResponse:record.rawResponse,candidate:record.candidate,syntaxRepair:record.syntaxRepair,transformations:record.transformations,historical:record.historical};}
function summaryOf(record:RequestRecord):RequestSummary {return {id:record.id,projectId:record.projectId,taskId:record.taskId,stepKey:record.stepKey,attempt:record.attempt,createdAt:record.createdAt,status:record.status,role:record.compiled.role,configHash:record.compiled.config.hash,hash:record.compiled.hash,stableHash:record.compiled.stableHash,localCompilationCache:record.compiled.localCompilationCache,localPrefixReuse:record.localPrefixReuse,usage:record.usage,error:record.error,detailState:'available',detailBytes:JSON.stringify(detailOf(record)).length};}
function parseSummary(row:Record<string,unknown>) {return JSON.parse(String(row.data)) as RequestSummary;}

export function requestIdsIn(value:unknown) {const result=new Set<string>();const visit=(item:unknown,key='')=>{if(typeof item==='string'&&/^requestIds?$/.test(key)&&item.startsWith('request_'))result.add(item);else if(Array.isArray(item))for(const child of item)visit(child,key==='requestIds'?'requestId':key);else if(item&&typeof item==='object')for(const [childKey,child] of Object.entries(item))visit(child,childKey);};visit(value);return [...result];}
function protection(store:Store,projectId:string) {const reasons=new Map<string,Set<string>>();const add=(requestId:string,reason:string)=>{if(!requestId.startsWith('request_'))return;const values=reasons.get(requestId)??new Set<string>();values.add(reason);reasons.set(requestId,values);};for(const row of store.db.prepare("SELECT id,json_extract(data,'$.steps') steps FROM tasks WHERE projectId=? AND json_extract(data,'$.status') IN ('QUEUED','RUNNING','PAUSE_REQUESTED','PAUSED','NEEDS_INPUT')").all(projectId))for(const step of JSON.parse(String(row.steps??'[]')))for(const requestId of step.requestIds??[])add(requestId,`活跃任务 ${row.id}`);for(const row of store.db.prepare("SELECT id,json_extract(data,'$.data') artifactData FROM artifacts WHERE projectId=? AND json_extract(data,'$.status')='pending'").all(projectId))for(const requestId of requestIdsIn(JSON.parse(String(row.artifactData??'{}'))))add(requestId,`待审成果 ${row.id}`);for(const row of store.db.prepare("SELECT id,json_extract(data,'$.requestIds') requestIds FROM versions WHERE projectId=? AND json_type(data,'$.requestIds') IS NOT NULL").all(projectId))for(const requestId of JSON.parse(String(row.requestIds??'[]')))add(requestId,`已接受正文版本 ${row.id}`);for(const row of store.db.prepare("SELECT v.id versionId,json_extract(a.data,'$.generation.requestId') requestId FROM versions v JOIN artifacts a ON a.id=v.commitKey WHERE v.projectId=? AND v.commitKey IS NOT NULL").all(projectId))if(row.requestId)add(String(row.requestId),`已接受正文版本 ${row.versionId}`);return reasons;}

export function requestSummaries(store:Store,projectId:string,options:{offset?:number;limit?:number;taskId?:string}={}) {const offset=Math.max(0,options.offset??0),limit=Math.min(200,Math.max(1,options.limit??100)),where=options.taskId?'projectId=? AND taskId=?':'projectId=?',params=options.taskId?[projectId,options.taskId]:[projectId];const total=Number(store.db.prepare(`SELECT COUNT(*) AS total FROM request_summaries WHERE ${where}`).get(...params)?.total??0);const rows=store.db.prepare(`SELECT data FROM request_summaries WHERE ${where} ORDER BY rowid DESC LIMIT ? OFFSET ?`).all(...params,limit,offset);const protectedIds=protection(store,projectId);const items=rows.map(parseSummary).map(summary=>({...summary,protectedReasons:[...(protectedIds.get(summary.id)??[])]}));return {items,total,nextOffset:offset+items.length<total?offset+items.length:undefined};}
export function requestList(store:Store,projectId:string):RequestRecord[] {const rows=store.db.prepare(`SELECT s.data summary,d.data detail FROM request_summaries s JOIN request_details d ON d.id=s.id WHERE s.projectId=? ORDER BY s.rowid DESC`).all(projectId);return rows.map(row=>({...JSON.parse(String(row.summary)),...JSON.parse(String(row.detail)),detailState:'available'}));}
export function writerRequestForArtifact(store:Store,projectId:string,taskId:string,content:string) {const rows=store.db.prepare("SELECT s.data summary,d.data detail FROM request_summaries s JOIN request_details d ON d.id=s.id WHERE s.projectId=? AND s.taskId=? AND json_extract(s.data,'$.role')='Writer' ORDER BY s.rowid DESC LIMIT 12").all(projectId,taskId);for(const row of rows){const detail=JSON.parse(String(row.detail));if(detail.candidate===content)return {...JSON.parse(String(row.summary)),...detail} as RequestRecord;}return undefined;}
export function requestExport(store:Store,projectId:string):StoredRequest[] {const rows=store.db.prepare(`SELECT s.data summary,d.data detail FROM request_summaries s LEFT JOIN request_details d ON d.id=s.id WHERE s.projectId=? ORDER BY s.rowid`).all(projectId);return rows.map(row=>({...JSON.parse(String(row.summary)),...(row.detail?JSON.parse(String(row.detail)):{} )}));}
export function requestGet(store:Store,projectId:string,requestId:string):StoredRequest {const row=store.db.prepare(`SELECT s.data summary,d.data detail FROM request_summaries s LEFT JOIN request_details d ON d.id=s.id WHERE s.id=? AND s.projectId=?`).get(requestId,projectId);requireThat(row,'NOT_FOUND','请求记录已过摘要保留范围或不属于本作品',404);return {...JSON.parse(String(row.summary)),...(row.detail?JSON.parse(String(row.detail)):{}),protectedReasons:[...(protection(store,projectId).get(requestId)??[])]};}

export function requestPut(store:Store,record:RequestRecord) {const summary=summaryOf(record),detail=detailOf(record);store.db.prepare(`INSERT INTO request_summaries(id,projectId,taskId,createdAt,status,detailState,data) VALUES(?,?,?,?,?,'available',?) ON CONFLICT(id) DO UPDATE SET taskId=excluded.taskId,status=excluded.status,detailState='available',data=excluded.data`).run(record.id,record.projectId,record.taskId,record.createdAt,record.status,JSON.stringify(summary));store.db.prepare('INSERT INTO request_details(id,data) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').run(record.id,JSON.stringify(detail));if(['COMPLETED','FAILED','STALE'].includes(record.status)){const age=store.db.prepare('SELECT COUNT(*) total,MIN(createdAt) oldest FROM request_summaries WHERE projectId=?').get(record.projectId);if(Number(age?.total)>requestRetentionPolicy.detailLimit||Date.parse(String(age?.oldest))<Date.now()-requestRetentionPolicy.detailDays*86_400_000)pruneRequests(store,record.projectId);}return record;}
export function requestRestore(store:Store,value:StoredRequest) {const hasDetail=!!value.compiled&&value.detailState!=='cleared';const summary:RequestSummary=hasDetail?summaryOf(value as RequestRecord):{id:value.id,projectId:value.projectId,taskId:value.taskId,stepKey:value.stepKey,attempt:value.attempt,createdAt:value.createdAt,status:value.status,role:value.role??'Unknown',configHash:value.configHash??'',hash:value.hash??'',stableHash:value.stableHash??'',localCompilationCache:value.localCompilationCache??'MISS',localPrefixReuse:value.localPrefixReuse,usage:value.usage,error:value.error,detailState:'cleared',detailBytes:value.detailBytes??0,clearedAt:value.clearedAt??now(),clearReason:value.clearReason??'备份中仅保留摘要'};store.db.prepare('INSERT INTO request_summaries(id,projectId,taskId,createdAt,status,detailState,data) VALUES(?,?,?,?,?,?,?)').run(summary.id,summary.projectId,summary.taskId,summary.createdAt,summary.status,summary.detailState,JSON.stringify(summary));if(hasDetail)store.db.prepare('INSERT INTO request_details(id,data) VALUES(?,?)').run(summary.id,JSON.stringify(detailOf(value as RequestRecord)));}

export function pruneRequests(store:Store,projectId:string,options:{before?:string;user?:boolean;removeSummaries?:boolean}={}) {const summaries=store.db.prepare('SELECT rowid,data FROM request_summaries WHERE projectId=? ORDER BY rowid DESC').all(projectId).map(row=>({rowid:Number(row.rowid),value:parseSummary(row)}));const protectedIds=protection(store,projectId),nowMs=Date.now(),detailCutoff=nowMs-requestRetentionPolicy.detailDays*86_400_000,summaryCutoff=nowMs-requestRetentionPolicy.summaryDays*86_400_000,before=options.before?Date.parse(options.before):undefined;let detailRank=0,summaryRank=0,detailsCleared=0,summariesRemoved=0;for(const entry of summaries){const summary=entry.value,isProtected=protectedIds.has(summary.id)||['PREPARED','SENT'].includes(summary.status);if(!isProtected){detailRank++;summaryRank++;}const created=Date.parse(summary.createdAt),clearForUser=!!options.user&&before!==undefined&&created<before,clearForPolicy=!options.user&&(detailRank>requestRetentionPolicy.detailLimit||created<detailCutoff);if(!isProtected&&summary.detailState==='available'&&(clearForUser||clearForPolicy)){store.db.prepare('DELETE FROM request_details WHERE id=?').run(summary.id);summary.detailState='cleared';summary.clearedAt=now();summary.clearReason=options.user?'作者主动清理请求详情':created<detailCutoff?`详情超过 ${requestRetentionPolicy.detailDays} 天`:`详情超过最近 ${requestRetentionPolicy.detailLimit} 条容量`;store.db.prepare("UPDATE request_summaries SET detailState='cleared',data=? WHERE id=?").run(JSON.stringify(summary),summary.id);detailsCleared++;}const removeForUser=!!options.user&&!!options.removeSummaries&&before!==undefined&&created<before,removeForPolicy=!options.user&&(summaryRank>requestRetentionPolicy.summaryLimit||created<summaryCutoff);if(!isProtected&&(removeForUser||removeForPolicy)){store.db.prepare('DELETE FROM request_summaries WHERE id=?').run(summary.id);summariesRemoved++;}}return {detailsCleared,summariesRemoved,protected:protectedIds.size,policy:requestRetentionPolicy};}
export function requestRetention(store:Store,projectId:string) {const protectedIds=protection(store,projectId);const row=store.db.prepare(`SELECT COUNT(*) summaries,SUM(CASE WHEN detailState='available' THEN 1 ELSE 0 END) availableDetails,SUM(CASE WHEN detailState='cleared' THEN 1 ELSE 0 END) clearedDetails,MIN(createdAt) oldestSummary FROM request_summaries WHERE projectId=?`).get(projectId) as Record<string,unknown>;return {policy:requestRetentionPolicy,summaries:Number(row?.summaries??0),availableDetails:Number(row?.availableDetails??0),clearedDetails:Number(row?.clearedDetails??0),protected:protectedIds.size,oldestSummary:row?.oldestSummary??null};}

export function beginRequest(store:Store,task:CreativeTask,stepKey:string,attempt:number,compiled:CompiledPrompt) {return requestPut(store,{id:id('request'),projectId:task.projectId,taskId:task.id,stepKey,attempt,createdAt:now(),status:'PREPARED',compiled});}
export function observeRequest(store:Store,record:RequestRecord,observed:unknown) {const row=store.db.prepare("SELECT s.data summary,d.data detail FROM request_summaries s JOIN request_details d ON d.id=s.id WHERE s.projectId=? AND s.id<>? AND json_extract(s.data,'$.role')=? AND json_type(d.data,'$.observed') IS NOT NULL ORDER BY s.rowid DESC LIMIT 1").get(record.projectId,record.id,record.compiled.role);const previous=row?{...JSON.parse(String(row.summary)),...JSON.parse(String(row.detail))} as RequestRecord:undefined;record.observed=observed;record.observedChars=JSON.stringify(observed).length;record.observedEstimatedTokens=Math.ceil(record.observedChars/2);record.observedAt=now();if(record.status==='PREPARED')record.status='SENT';record.previousId=previous?.id;record.diff=previous?requestDiff(previous.observed,observed):undefined;record.localPrefixReuse=previous?previous.compiled.stableHash===record.compiled.stableHash:undefined;return requestPut(store,record);}
