import { z } from 'zod';
export const sourceKinds=['character','world','relationship','fact','event','foreshadow'] as const;
const text=z.string().max(100000),short=z.string().max(2000);
export const evidenceSchema=z.object({quote:z.string().min(1).max(4000),start:z.number().int().nonnegative().optional(),modality:z.enum(['objective','knowledge','rumor','memory','dream','uncertain']).default('objective'),inference:z.boolean().default(false),storyTime:short.default('未知'),knownBy:z.array(z.string()).default([])});
export const discoveredSchema=z.object({entities:z.array(z.object({key:z.string().min(1).max(200),name:z.string().min(1).max(240),kind:z.enum(['character','world']),identity:short.default('未证实'),aliases:z.array(z.string().max(240)).max(20).default([]),evidence:evidenceSchema})).max(32),saturated:z.boolean()});
export const sourceExtractSchema=z.object({summary:z.string().max(2500),items:z.array(z.object({key:z.string().min(1).max(200),kind:z.enum(sourceKinds),name:z.string().min(1).max(240),description:short.default(''),fields:z.record(z.union([short,z.number(),z.boolean(),z.array(z.string().max(1000)),z.null()])).default({}),refs:z.record(z.union([z.string(),z.array(z.string())])).default({}),evidence:evidenceSchema})).max(48),saturated:z.boolean()});
export const profileSchema=z.object({identity:short,appearance:short,voice:short,desire:short,boundaries:short,uncertainties:z.array(short),evidence:z.array(evidenceSchema).max(20)});
export const sourceTaskSchema=z.object({runId:z.string(),versionId:z.string(),cutoffId:z.string().nullable(),batchSize:z.number().int().min(4).max(32).default(16),chunkChars:z.number().int().min(200).max(10000).default(4000),cloudAuthorized:z.boolean().default(false),profileIds:z.array(z.string()).optional(),analysisRevision:z.number().int().optional()});
export interface SourceWork {id:string;workspaceId:string;title:string;author:string;origin:string;rights:string;archived:boolean;revision:number;createdAt:string;}
export interface SourceChapter {id:string;title:string;ordinal:number;volumeId:string;volumeTitle:string;start:number;end:number;bodyStart:number;materialId:string;excluded:boolean;}
export interface SourceVersion {id:string;workId:string;version:number;createdAt:string;hash:string;raw:string;encoding:string;originalBase64?:string;chapters:SourceChapter[];warnings:string[];materials:{id:string;name:string;kind:string;stage:string;scope:'baseline'|'author-reference';start:number;end:number;encoding?:string;hash?:string;originalBase64?:string}[];}
export interface SourceEvidence extends z.infer<typeof evidenceSchema>{versionId:string;chapterId:string;ordinal:number;start:number;end:number;runId:string;}
export interface SourceAsset {id:string;workId:string;versionId:string;runId:string;revision:number;key:string;kind:typeof sourceKinds[number];name:string;identity:string;aliases:string[];description:string;fields:Record<string,any>;refs:Record<string,string|string[]>;evidence:SourceEvidence[];status:'verified'|'ambiguous'|'unverified'|'merged';profile?:any;manual:boolean;mergedInto?:string;invalidated?:boolean;}
export interface SourceSegment {id:string;chapterId:string;start:number;end:number;depth:number;state:'pending'|'discovered'|'complete'|'split'|'failed';discovery?:z.infer<typeof discoveredSchema>;summary?:string;error?:string;registryIds?:string[];registryHash?:string;}
export interface SourceRun {id:string;workId:string;versionId:string;taskId:string;cutoffId:string|null;cutoff:number;revision:number;segments:SourceSegment[];createdAt:string;analysisVersion:string;}
export const manifestSchema=z.object({versionId:z.string(),runId:z.string(),title:z.string().trim().min(1).max(160),mode:z.enum(['continuation','divergence','independent']),template:z.enum(['canonical','divergent','parallel']),boundary:z.object({kind:z.enum(['after-chapter','before-chapter','after-volume','before-volume','all-materials']),id:z.string().nullable()}),inheritPrefix:z.boolean().default(true),inheritDynamics:z.boolean().default(true),inheritPlot:z.boolean().default(true),inheritStyle:z.boolean().default(false),configurationVersionId:z.string().optional(),categories:z.array(z.enum(sourceKinds)).default([...sourceKinds]),selection:z.record(z.object({mode:z.enum(['main','background','omit','exclude']),fields:z.array(z.string()).optional()})).default({}),dependencies:z.record(z.object({action:z.enum(['background','include','drop','replace']),replacement:z.string().optional()})).default({}),overrides:z.array(z.object({entityId:z.string(),property:z.string().min(1).max(100),value:z.string().min(1).max(2000),reason:z.string().min(1).max(2000),retcon:z.boolean().default(false)})).default([]),allowGaps:z.boolean().default(false),goal:z.string().max(6000).default('从选定基线开始新的故事，不补写未经证实的原作历史。')}).strict();
export type AdaptationSpec=z.infer<typeof manifestSchema>;
const staticCharacter=new Set(['identity','appearance','voice','desire','fear','boundaries','weakness','personality','group','organization','aliases']);
const staticWorld=new Set(['identity','type','aliases','rule','rules','conditions','exceptions','cost','scope','unique','core','pinned','tags','力量规则','世界规则','条件','例外','代价','唯一性']);
export const dynamicSourceFields=new Set(['location','health','holder','inventory','known','secret','level','marriage','death','status','arc','background','abilities','goal','growth']);
// Explicit field choices override the template defaults, including custom attributes.
export function inheritedFields(a:Pick<SourceAsset,'id'|'kind'|'fields'>,spec:Pick<AdaptationSpec,'inheritDynamics'|'selection'>){
 const choice=spec.selection[a.id]?.fields;
 return Object.fromEntries(Object.entries(a.fields).filter(([key])=>choice?choice.includes(key):spec.inheritDynamics||a.kind==='character'?spec.inheritDynamics||staticCharacter.has(key):a.kind==='world'?staticWorld.has(key):!dynamicSourceFields.has(key)));
}
export interface ImportManifest {id:string;workId:string;versionId:string;revision:number;createdAt:string;spec:AdaptationSpec;analysisRevision:number;status:'staging'|'active'|'canceled';projectId?:string;mapping:Record<string,string>;}
